import type { CertificationInfo } from '@/types';

export const CERTIFICATIONS: CertificationInfo[] = [
  { id: 'MWBE', label: 'Minority and Women-Owned Business Enterprise', shortLabel: 'MWBE', description: 'Combined minority and women-owned certification', source: 'NYS ESD / NYC SBS' },
  { id: 'MBE', label: 'Minority Business Enterprise', shortLabel: 'MBE', description: 'At least 51% owned by minority group members', source: 'NYS ESD / NYC SBS' },
  { id: 'WBE', label: 'Women-Owned Business Enterprise', shortLabel: 'WBE', description: 'At least 51% owned by women', source: 'NYS ESD / NYC SBS' },
  { id: 'DBE', label: 'Disadvantaged Business Enterprise', shortLabel: 'DBE', description: 'Socially and economically disadvantaged individuals', source: 'US DOT / NYS DOT' },
  { id: 'SBE', label: 'Small Business Enterprise', shortLabel: 'SBE', description: 'Meets SBA size standards for small business', source: 'SBA / NYC SBS' },
  { id: 'SDVOB', label: 'Service-Disabled Veteran-Owned Business', shortLabel: 'SDVOB', description: 'Owned by service-disabled veterans (NYS program)', source: 'NYS OGS' },
  { id: 'SECTION_3', label: 'Section 3 Business', shortLabel: 'Section 3', description: 'HUD Section 3 eligible business concern', source: 'HUD' },
  { id: 'SBA_8A', label: 'SBA 8(a) Business Development Program', shortLabel: '8(a)', description: 'SBA program for socially disadvantaged entrepreneurs', source: 'SBA' },
  { id: 'HUBZONE', label: 'Historically Underutilized Business Zone', shortLabel: 'HUBZone', description: 'Located in designated HUBZone areas', source: 'SBA' },
  { id: 'SDVOSB', label: 'Service-Disabled Veteran-Owned Small Business', shortLabel: 'SDVOSB', description: 'Federal veteran-owned small business program', source: 'VA / SBA' },
  { id: 'WOSB', label: 'Women-Owned Small Business (Federal)', shortLabel: 'WOSB', description: 'Federal women-owned small business certification', source: 'SBA' },
  { id: 'EDWOSB', label: 'Economically Disadvantaged Women-Owned Small Business', shortLabel: 'EDWOSB', description: 'Economically disadvantaged women-owned business', source: 'SBA' },
  { id: 'LBE', label: 'Local Business Enterprise', shortLabel: 'LBE', description: 'Business located within the contracting jurisdiction', source: 'NYC SBS' },
  { id: 'EBE', label: 'Emerging Business Enterprise', shortLabel: 'EBE', description: 'Newer businesses meeting size/revenue thresholds', source: 'NYC SBS' },
  { id: 'NYS_CERTIFIED_MBE', label: 'NYS Certified Minority Business Enterprise', shortLabel: 'NYS MBE', description: 'New York State certified minority-owned business', source: 'NYS ESD' },
  { id: 'NYS_CERTIFIED_WBE', label: 'NYS Certified Women Business Enterprise', shortLabel: 'NYS WBE', description: 'New York State certified women-owned business', source: 'NYS ESD' },
  { id: 'NYS_CERTIFIED_SDVOB', label: 'NYS Certified SDVOB', shortLabel: 'NYS SDVOB', description: 'New York State certified service-disabled veteran-owned', source: 'NYS OGS' },
  { id: 'NYC_MBE', label: 'NYC Certified MBE', shortLabel: 'NYC MBE', description: 'NYC Small Business Services certified MBE', source: 'NYC SBS' },
  { id: 'NYC_WBE', label: 'NYC Certified WBE', shortLabel: 'NYC WBE', description: 'NYC Small Business Services certified WBE', source: 'NYC SBS' },
  { id: 'NYC_EBE', label: 'NYC Emerging Business Enterprise', shortLabel: 'NYC EBE', description: 'NYC emerging business certification', source: 'NYC SBS' },
  { id: 'NYC_LBE', label: 'NYC Local Business Enterprise', shortLabel: 'NYC LBE', description: 'NYC locally-based business certification', source: 'NYC SBS' },
  { id: 'NYSSD', label: 'NYS Service-Disabled', shortLabel: 'NYSSD', description: 'NYS specific service-disabled classification', source: 'NYS OGS' },
  { id: 'PANYNJ_MBE', label: 'Port Authority MBE', shortLabel: 'PANYNJ MBE', description: 'Port Authority of NY/NJ minority business', source: 'PANYNJ' },
  { id: 'PANYNJ_WBE', label: 'Port Authority WBE', shortLabel: 'PANYNJ WBE', description: 'Port Authority of NY/NJ women-owned business', source: 'PANYNJ' },
  { id: 'SBA_WOSB', label: 'SBA Women-Owned Small Business', shortLabel: 'SBA WOSB', description: 'SBA certified women-owned small business', source: 'SBA' },
  { id: 'SBA_EDWOSB', label: 'SBA Economically Disadvantaged WOSB', shortLabel: 'SBA EDWOSB', description: 'SBA economically disadvantaged WOSB', source: 'SBA' },
];

export const CERT_COLORS: Record<string, string> = {
  MWBE: '#1A6B3C',
  MBE: '#0A5EB0',
  WBE: '#9C27B0',
  DBE: '#E65100',
  SBE: '#00838F',
  SDVOB: '#2E7D32',
  SECTION_3: '#4527A0',
  SBA_8A: '#C62828',
  HUBZONE: '#1565C0',
  SDVOSB: '#33691E',
  WOSB: '#AD1457',
  EDWOSB: '#880E4F',
  LBE: '#00695C',
  EBE: '#F57F17',
  NYS_CERTIFIED_MBE: '#1A237E',
  NYS_CERTIFIED_WBE: '#7B1FA2',
  NYS_CERTIFIED_SDVOB: '#1B5E20',
  NYC_MBE: '#283593',
  NYC_WBE: '#6A1B9A',
  NYC_EBE: '#E65100',
  NYC_LBE: '#004D40',
  NYSSD: '#2E7D32',
  PANYNJ_MBE: '#0D47A1',
  PANYNJ_WBE: '#4A148C',
  SBA_WOSB: '#B71C1C',
  SBA_EDWOSB: '#880E4F',
};
