export interface TemplateTask {
  id: string;
  name: string;
  phase: string;
  duration: number;
  predecessorIds: string[];
  isMilestone: boolean;
  isCriticalPath: boolean;
  crewSize: number;
}

export interface ScheduleTemplate {
  id: string;
  name: string;
  taskCount: number;
  typicalDuration: string;
  tasks: TemplateTask[];
}

export const SCHEDULE_TEMPLATES: ScheduleTemplate[] = [
  {
    id: 'kitchen-remodel',
    name: 'Kitchen Remodel',
    taskCount: 18,
    typicalDuration: '6 weeks',
    tasks: [
      { id: 'kr-1', name: 'Project Start', phase: 'General', duration: 0, predecessorIds: [], isMilestone: true, isCriticalPath: true, crewSize: 0 },
      { id: 'kr-2', name: 'Demolition', phase: 'Demo', duration: 2, predecessorIds: ['kr-1'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'kr-3', name: 'Rough Plumbing', phase: 'Plumbing', duration: 2, predecessorIds: ['kr-2'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'kr-4', name: 'Rough Electrical', phase: 'Electrical', duration: 2, predecessorIds: ['kr-2'], isMilestone: false, isCriticalPath: false, crewSize: 2 },
      { id: 'kr-5', name: 'HVAC Rough-In', phase: 'HVAC', duration: 1, predecessorIds: ['kr-2'], isMilestone: false, isCriticalPath: false, crewSize: 2 },
      { id: 'kr-6', name: 'Framing Modifications', phase: 'Framing', duration: 2, predecessorIds: ['kr-3', 'kr-4'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'kr-7', name: 'Rough Inspection', phase: 'Inspections', duration: 1, predecessorIds: ['kr-6'], isMilestone: true, isCriticalPath: true, crewSize: 0 },
      { id: 'kr-8', name: 'Insulation', phase: 'Insulation', duration: 1, predecessorIds: ['kr-7'], isMilestone: false, isCriticalPath: false, crewSize: 2 },
      { id: 'kr-9', name: 'Drywall', phase: 'Drywall', duration: 3, predecessorIds: ['kr-8'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'kr-10', name: 'Prime & Paint', phase: 'Finishes', duration: 2, predecessorIds: ['kr-9'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'kr-11', name: 'Cabinet Installation', phase: 'Interior', duration: 2, predecessorIds: ['kr-10'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'kr-12', name: 'Countertop Installation', phase: 'Interior', duration: 1, predecessorIds: ['kr-11'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'kr-13', name: 'Backsplash Tile', phase: 'Finishes', duration: 2, predecessorIds: ['kr-12'], isMilestone: false, isCriticalPath: false, crewSize: 2 },
      { id: 'kr-14', name: 'Finish Plumbing', phase: 'Plumbing', duration: 1, predecessorIds: ['kr-12'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'kr-15', name: 'Finish Electrical', phase: 'Electrical', duration: 1, predecessorIds: ['kr-12'], isMilestone: false, isCriticalPath: false, crewSize: 2 },
      { id: 'kr-16', name: 'Appliance Installation', phase: 'Interior', duration: 1, predecessorIds: ['kr-14', 'kr-15'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'kr-17', name: 'Final Inspection', phase: 'Inspections', duration: 1, predecessorIds: ['kr-16', 'kr-13'], isMilestone: true, isCriticalPath: true, crewSize: 0 },
      { id: 'kr-18', name: 'Project Complete', phase: 'General', duration: 0, predecessorIds: ['kr-17'], isMilestone: true, isCriticalPath: true, crewSize: 0 },
    ],
  },
  {
    id: 'bathroom-remodel',
    name: 'Bathroom Remodel',
    taskCount: 12,
    typicalDuration: '3 weeks',
    tasks: [
      { id: 'br-1', name: 'Project Start', phase: 'General', duration: 0, predecessorIds: [], isMilestone: true, isCriticalPath: true, crewSize: 0 },
      { id: 'br-2', name: 'Demolition', phase: 'Demo', duration: 1, predecessorIds: ['br-1'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'br-3', name: 'Rough Plumbing', phase: 'Plumbing', duration: 2, predecessorIds: ['br-2'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'br-4', name: 'Rough Electrical', phase: 'Electrical', duration: 1, predecessorIds: ['br-2'], isMilestone: false, isCriticalPath: false, crewSize: 1 },
      { id: 'br-5', name: 'Waterproofing', phase: 'General', duration: 1, predecessorIds: ['br-3'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'br-6', name: 'Tile Installation', phase: 'Finishes', duration: 3, predecessorIds: ['br-5'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'br-7', name: 'Vanity & Mirror', phase: 'Interior', duration: 1, predecessorIds: ['br-6'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'br-8', name: 'Finish Plumbing', phase: 'Plumbing', duration: 1, predecessorIds: ['br-7'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'br-9', name: 'Finish Electrical', phase: 'Electrical', duration: 1, predecessorIds: ['br-7'], isMilestone: false, isCriticalPath: false, crewSize: 1 },
      { id: 'br-10', name: 'Paint & Trim', phase: 'Finishes', duration: 1, predecessorIds: ['br-8', 'br-9'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'br-11', name: 'Final Inspection', phase: 'Inspections', duration: 1, predecessorIds: ['br-10'], isMilestone: true, isCriticalPath: true, crewSize: 0 },
      { id: 'br-12', name: 'Project Complete', phase: 'General', duration: 0, predecessorIds: ['br-11'], isMilestone: true, isCriticalPath: true, crewSize: 0 },
    ],
  },
  {
    id: 'basement-finish',
    name: 'Basement Finish',
    taskCount: 20,
    typicalDuration: '8 weeks',
    tasks: [
      { id: 'bf-1', name: 'Project Start', phase: 'General', duration: 0, predecessorIds: [], isMilestone: true, isCriticalPath: true, crewSize: 0 },
      { id: 'bf-2', name: 'Layout & Design Review', phase: 'General', duration: 1, predecessorIds: ['bf-1'], isMilestone: false, isCriticalPath: true, crewSize: 1 },
      { id: 'bf-3', name: 'Waterproofing & Drainage', phase: 'Site Work', duration: 3, predecessorIds: ['bf-2'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'bf-4', name: 'Framing Walls', phase: 'Framing', duration: 4, predecessorIds: ['bf-3'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'bf-5', name: 'Rough Plumbing', phase: 'Plumbing', duration: 2, predecessorIds: ['bf-4'], isMilestone: false, isCriticalPath: false, crewSize: 2 },
      { id: 'bf-6', name: 'Rough Electrical', phase: 'Electrical', duration: 3, predecessorIds: ['bf-4'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'bf-7', name: 'HVAC Ductwork', phase: 'HVAC', duration: 2, predecessorIds: ['bf-4'], isMilestone: false, isCriticalPath: false, crewSize: 2 },
      { id: 'bf-8', name: 'Rough Inspection', phase: 'Inspections', duration: 1, predecessorIds: ['bf-5', 'bf-6', 'bf-7'], isMilestone: true, isCriticalPath: true, crewSize: 0 },
      { id: 'bf-9', name: 'Insulation', phase: 'Insulation', duration: 2, predecessorIds: ['bf-8'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'bf-10', name: 'Drywall Hang', phase: 'Drywall', duration: 3, predecessorIds: ['bf-9'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'bf-11', name: 'Drywall Tape & Mud', phase: 'Drywall', duration: 3, predecessorIds: ['bf-10'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'bf-12', name: 'Prime & Paint', phase: 'Finishes', duration: 3, predecessorIds: ['bf-11'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'bf-13', name: 'Flooring Installation', phase: 'Finishes', duration: 3, predecessorIds: ['bf-12'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'bf-14', name: 'Trim & Doors', phase: 'Interior', duration: 2, predecessorIds: ['bf-13'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'bf-15', name: 'Bathroom Tile', phase: 'Finishes', duration: 3, predecessorIds: ['bf-12'], isMilestone: false, isCriticalPath: false, crewSize: 2 },
      { id: 'bf-16', name: 'Finish Plumbing', phase: 'Plumbing', duration: 1, predecessorIds: ['bf-15'], isMilestone: false, isCriticalPath: false, crewSize: 2 },
      { id: 'bf-17', name: 'Finish Electrical', phase: 'Electrical', duration: 1, predecessorIds: ['bf-14'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'bf-18', name: 'Final Cleanup', phase: 'General', duration: 1, predecessorIds: ['bf-16', 'bf-17'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'bf-19', name: 'Final Inspection', phase: 'Inspections', duration: 1, predecessorIds: ['bf-18'], isMilestone: true, isCriticalPath: true, crewSize: 0 },
      { id: 'bf-20', name: 'Project Complete', phase: 'General', duration: 0, predecessorIds: ['bf-19'], isMilestone: true, isCriticalPath: true, crewSize: 0 },
    ],
  },
  {
    id: 'roof-replacement',
    name: 'Roof Replacement',
    taskCount: 8,
    typicalDuration: '1 week',
    tasks: [
      { id: 'rr-1', name: 'Project Start', phase: 'General', duration: 0, predecessorIds: [], isMilestone: true, isCriticalPath: true, crewSize: 0 },
      { id: 'rr-2', name: 'Material Delivery', phase: 'General', duration: 1, predecessorIds: ['rr-1'], isMilestone: false, isCriticalPath: true, crewSize: 1 },
      { id: 'rr-3', name: 'Tear-Off Existing Roof', phase: 'Demo', duration: 1, predecessorIds: ['rr-2'], isMilestone: false, isCriticalPath: true, crewSize: 5 },
      { id: 'rr-4', name: 'Inspect & Repair Decking', phase: 'Framing', duration: 1, predecessorIds: ['rr-3'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'rr-5', name: 'Install Underlayment & Flashing', phase: 'Roofing', duration: 1, predecessorIds: ['rr-4'], isMilestone: false, isCriticalPath: true, crewSize: 4 },
      { id: 'rr-6', name: 'Install Shingles', phase: 'Roofing', duration: 2, predecessorIds: ['rr-5'], isMilestone: false, isCriticalPath: true, crewSize: 5 },
      { id: 'rr-7', name: 'Cleanup & Final Inspection', phase: 'Inspections', duration: 1, predecessorIds: ['rr-6'], isMilestone: true, isCriticalPath: true, crewSize: 2 },
      { id: 'rr-8', name: 'Project Complete', phase: 'General', duration: 0, predecessorIds: ['rr-7'], isMilestone: true, isCriticalPath: true, crewSize: 0 },
    ],
  },
  {
    id: 'new-home',
    name: 'New Home Construction',
    taskCount: 30,
    typicalDuration: '26 weeks',
    tasks: [
      { id: 'nh-1', name: 'Project Start', phase: 'General', duration: 0, predecessorIds: [], isMilestone: true, isCriticalPath: true, crewSize: 0 },
      { id: 'nh-2', name: 'Permits & Survey', phase: 'General', duration: 5, predecessorIds: ['nh-1'], isMilestone: false, isCriticalPath: true, crewSize: 1 },
      { id: 'nh-3', name: 'Site Clearing & Grading', phase: 'Site Work', duration: 3, predecessorIds: ['nh-2'], isMilestone: false, isCriticalPath: true, crewSize: 4 },
      { id: 'nh-4', name: 'Excavation', phase: 'Site Work', duration: 2, predecessorIds: ['nh-3'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'nh-5', name: 'Foundation Forms & Pour', phase: 'Foundation', duration: 5, predecessorIds: ['nh-4'], isMilestone: false, isCriticalPath: true, crewSize: 5 },
      { id: 'nh-6', name: 'Foundation Cure & Strip', phase: 'Foundation', duration: 5, predecessorIds: ['nh-5'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'nh-7', name: 'Foundation Inspection', phase: 'Inspections', duration: 1, predecessorIds: ['nh-6'], isMilestone: true, isCriticalPath: true, crewSize: 0 },
      { id: 'nh-8', name: 'Backfill & Waterproof', phase: 'Site Work', duration: 2, predecessorIds: ['nh-7'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'nh-9', name: 'Framing — First Floor', phase: 'Framing', duration: 8, predecessorIds: ['nh-8'], isMilestone: false, isCriticalPath: true, crewSize: 6 },
      { id: 'nh-10', name: 'Framing — Second Floor', phase: 'Framing', duration: 6, predecessorIds: ['nh-9'], isMilestone: false, isCriticalPath: true, crewSize: 6 },
      { id: 'nh-11', name: 'Roof Framing & Sheathing', phase: 'Roofing', duration: 5, predecessorIds: ['nh-10'], isMilestone: false, isCriticalPath: true, crewSize: 5 },
      { id: 'nh-12', name: 'Roofing', phase: 'Roofing', duration: 3, predecessorIds: ['nh-11'], isMilestone: false, isCriticalPath: true, crewSize: 4 },
      { id: 'nh-13', name: 'Windows & Exterior Doors', phase: 'Framing', duration: 3, predecessorIds: ['nh-11'], isMilestone: false, isCriticalPath: false, crewSize: 3 },
      { id: 'nh-14', name: 'Rough Plumbing', phase: 'Plumbing', duration: 5, predecessorIds: ['nh-12'], isMilestone: false, isCriticalPath: false, crewSize: 3 },
      { id: 'nh-15', name: 'Rough Electrical', phase: 'Electrical', duration: 5, predecessorIds: ['nh-12'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'nh-16', name: 'HVAC Rough-In', phase: 'HVAC', duration: 4, predecessorIds: ['nh-12'], isMilestone: false, isCriticalPath: false, crewSize: 3 },
      { id: 'nh-17', name: 'Rough Inspection', phase: 'Inspections', duration: 1, predecessorIds: ['nh-14', 'nh-15', 'nh-16'], isMilestone: true, isCriticalPath: true, crewSize: 0 },
      { id: 'nh-18', name: 'Insulation', phase: 'Insulation', duration: 3, predecessorIds: ['nh-17'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'nh-19', name: 'Drywall', phase: 'Drywall', duration: 8, predecessorIds: ['nh-18'], isMilestone: false, isCriticalPath: true, crewSize: 4 },
      { id: 'nh-20', name: 'Exterior Siding', phase: 'Finishes', duration: 5, predecessorIds: ['nh-13'], isMilestone: false, isCriticalPath: false, crewSize: 3 },
      { id: 'nh-21', name: 'Interior Paint', phase: 'Finishes', duration: 5, predecessorIds: ['nh-19'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'nh-22', name: 'Cabinets & Countertops', phase: 'Interior', duration: 4, predecessorIds: ['nh-21'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'nh-23', name: 'Flooring', phase: 'Finishes', duration: 5, predecessorIds: ['nh-21'], isMilestone: false, isCriticalPath: false, crewSize: 3 },
      { id: 'nh-24', name: 'Trim & Millwork', phase: 'Interior', duration: 4, predecessorIds: ['nh-22', 'nh-23'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'nh-25', name: 'Finish Plumbing', phase: 'Plumbing', duration: 2, predecessorIds: ['nh-24'], isMilestone: false, isCriticalPath: false, crewSize: 2 },
      { id: 'nh-26', name: 'Finish Electrical', phase: 'Electrical', duration: 2, predecessorIds: ['nh-24'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'nh-27', name: 'Landscaping & Driveway', phase: 'Landscaping', duration: 5, predecessorIds: ['nh-20'], isMilestone: false, isCriticalPath: false, crewSize: 4 },
      { id: 'nh-28', name: 'Final Cleanup', phase: 'General', duration: 2, predecessorIds: ['nh-25', 'nh-26', 'nh-27'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'nh-29', name: 'Final Inspection & CO', phase: 'Inspections', duration: 1, predecessorIds: ['nh-28'], isMilestone: true, isCriticalPath: true, crewSize: 0 },
      { id: 'nh-30', name: 'Project Complete', phase: 'General', duration: 0, predecessorIds: ['nh-29'], isMilestone: true, isCriticalPath: true, crewSize: 0 },
    ],
  },
  {
    id: 'commercial-ti',
    name: 'Commercial Tenant Improvement',
    taskCount: 22,
    typicalDuration: '10 weeks',
    tasks: [
      { id: 'ct-1', name: 'Project Start', phase: 'General', duration: 0, predecessorIds: [], isMilestone: true, isCriticalPath: true, crewSize: 0 },
      { id: 'ct-2', name: 'Permits & Plan Review', phase: 'General', duration: 5, predecessorIds: ['ct-1'], isMilestone: false, isCriticalPath: true, crewSize: 1 },
      { id: 'ct-3', name: 'Demolition', phase: 'Demo', duration: 3, predecessorIds: ['ct-2'], isMilestone: false, isCriticalPath: true, crewSize: 4 },
      { id: 'ct-4', name: 'Framing', phase: 'Framing', duration: 5, predecessorIds: ['ct-3'], isMilestone: false, isCriticalPath: true, crewSize: 4 },
      { id: 'ct-5', name: 'Rough Plumbing', phase: 'Plumbing', duration: 3, predecessorIds: ['ct-4'], isMilestone: false, isCriticalPath: false, crewSize: 2 },
      { id: 'ct-6', name: 'Rough Electrical', phase: 'Electrical', duration: 4, predecessorIds: ['ct-4'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'ct-7', name: 'HVAC Rough-In', phase: 'HVAC', duration: 3, predecessorIds: ['ct-4'], isMilestone: false, isCriticalPath: false, crewSize: 3 },
      { id: 'ct-8', name: 'Fire Sprinkler', phase: 'MEP', duration: 2, predecessorIds: ['ct-4'], isMilestone: false, isCriticalPath: false, crewSize: 2 },
      { id: 'ct-9', name: 'Rough Inspection', phase: 'Inspections', duration: 1, predecessorIds: ['ct-5', 'ct-6', 'ct-7', 'ct-8'], isMilestone: true, isCriticalPath: true, crewSize: 0 },
      { id: 'ct-10', name: 'Insulation', phase: 'Insulation', duration: 2, predecessorIds: ['ct-9'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'ct-11', name: 'Drywall', phase: 'Drywall', duration: 5, predecessorIds: ['ct-10'], isMilestone: false, isCriticalPath: true, crewSize: 4 },
      { id: 'ct-12', name: 'Ceiling Grid', phase: 'Interior', duration: 3, predecessorIds: ['ct-11'], isMilestone: false, isCriticalPath: false, crewSize: 3 },
      { id: 'ct-13', name: 'Paint', phase: 'Finishes', duration: 3, predecessorIds: ['ct-11'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'ct-14', name: 'Flooring', phase: 'Finishes', duration: 4, predecessorIds: ['ct-13'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'ct-15', name: 'Millwork & Casework', phase: 'Interior', duration: 3, predecessorIds: ['ct-14'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'ct-16', name: 'Finish Plumbing', phase: 'Plumbing', duration: 2, predecessorIds: ['ct-15'], isMilestone: false, isCriticalPath: false, crewSize: 2 },
      { id: 'ct-17', name: 'Finish Electrical', phase: 'Electrical', duration: 2, predecessorIds: ['ct-15'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'ct-18', name: 'HVAC Start-Up', phase: 'HVAC', duration: 1, predecessorIds: ['ct-12'], isMilestone: false, isCriticalPath: false, crewSize: 2 },
      { id: 'ct-19', name: 'Signage', phase: 'General', duration: 2, predecessorIds: ['ct-13'], isMilestone: false, isCriticalPath: false, crewSize: 2 },
      { id: 'ct-20', name: 'Final Cleanup', phase: 'General', duration: 1, predecessorIds: ['ct-16', 'ct-17', 'ct-18', 'ct-19'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'ct-21', name: 'Final Inspection & CO', phase: 'Inspections', duration: 1, predecessorIds: ['ct-20'], isMilestone: true, isCriticalPath: true, crewSize: 0 },
      { id: 'ct-22', name: 'Project Complete', phase: 'General', duration: 0, predecessorIds: ['ct-21'], isMilestone: true, isCriticalPath: true, crewSize: 0 },
    ],
  },
  {
    id: 'exterior-renovation',
    name: 'Exterior Renovation',
    taskCount: 15,
    typicalDuration: '4 weeks',
    tasks: [
      { id: 'er-1', name: 'Project Start', phase: 'General', duration: 0, predecessorIds: [], isMilestone: true, isCriticalPath: true, crewSize: 0 },
      { id: 'er-2', name: 'Scaffolding Setup', phase: 'Site Work', duration: 1, predecessorIds: ['er-1'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'er-3', name: 'Remove Old Siding', phase: 'Demo', duration: 3, predecessorIds: ['er-2'], isMilestone: false, isCriticalPath: true, crewSize: 4 },
      { id: 'er-4', name: 'Repair Sheathing', phase: 'Framing', duration: 2, predecessorIds: ['er-3'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'er-5', name: 'Housewrap & Flashing', phase: 'General', duration: 1, predecessorIds: ['er-4'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'er-6', name: 'Window Replacement', phase: 'Framing', duration: 2, predecessorIds: ['er-5'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'er-7', name: 'New Siding Install', phase: 'Finishes', duration: 5, predecessorIds: ['er-6'], isMilestone: false, isCriticalPath: true, crewSize: 4 },
      { id: 'er-8', name: 'Soffit & Fascia', phase: 'Finishes', duration: 2, predecessorIds: ['er-7'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'er-9', name: 'Gutters', phase: 'Finishes', duration: 1, predecessorIds: ['er-8'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'er-10', name: 'Exterior Paint & Caulk', phase: 'Finishes', duration: 2, predecessorIds: ['er-9'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'er-11', name: 'Deck/Porch Repair', phase: 'Finishes', duration: 3, predecessorIds: ['er-5'], isMilestone: false, isCriticalPath: false, crewSize: 3 },
      { id: 'er-12', name: 'Landscaping Repair', phase: 'Landscaping', duration: 2, predecessorIds: ['er-10', 'er-11'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'er-13', name: 'Scaffolding Removal', phase: 'Site Work', duration: 1, predecessorIds: ['er-10'], isMilestone: false, isCriticalPath: false, crewSize: 3 },
      { id: 'er-14', name: 'Final Walkthrough', phase: 'Inspections', duration: 1, predecessorIds: ['er-12', 'er-13'], isMilestone: true, isCriticalPath: true, crewSize: 1 },
      { id: 'er-15', name: 'Project Complete', phase: 'General', duration: 0, predecessorIds: ['er-14'], isMilestone: true, isCriticalPath: true, crewSize: 0 },
    ],
  },
  {
    id: 'parking-lot',
    name: 'Parking Lot',
    taskCount: 12,
    typicalDuration: '3 weeks',
    tasks: [
      { id: 'pl-1', name: 'Project Start', phase: 'General', duration: 0, predecessorIds: [], isMilestone: true, isCriticalPath: true, crewSize: 0 },
      { id: 'pl-2', name: 'Site Survey & Layout', phase: 'Site Work', duration: 1, predecessorIds: ['pl-1'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'pl-3', name: 'Demolition & Removal', phase: 'Demo', duration: 2, predecessorIds: ['pl-2'], isMilestone: false, isCriticalPath: true, crewSize: 4 },
      { id: 'pl-4', name: 'Grading & Compaction', phase: 'Site Work', duration: 2, predecessorIds: ['pl-3'], isMilestone: false, isCriticalPath: true, crewSize: 4 },
      { id: 'pl-5', name: 'Storm Drainage', phase: 'Site Work', duration: 2, predecessorIds: ['pl-4'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'pl-6', name: 'Aggregate Base', phase: 'Foundation', duration: 2, predecessorIds: ['pl-5'], isMilestone: false, isCriticalPath: true, crewSize: 4 },
      { id: 'pl-7', name: 'Curb & Gutter', phase: 'Foundation', duration: 2, predecessorIds: ['pl-6'], isMilestone: false, isCriticalPath: true, crewSize: 3 },
      { id: 'pl-8', name: 'Asphalt Paving', phase: 'Finishes', duration: 2, predecessorIds: ['pl-7'], isMilestone: false, isCriticalPath: true, crewSize: 5 },
      { id: 'pl-9', name: 'Striping & Signage', phase: 'Finishes', duration: 1, predecessorIds: ['pl-8'], isMilestone: false, isCriticalPath: true, crewSize: 2 },
      { id: 'pl-10', name: 'Lighting', phase: 'Electrical', duration: 2, predecessorIds: ['pl-7'], isMilestone: false, isCriticalPath: false, crewSize: 2 },
      { id: 'pl-11', name: 'Final Inspection', phase: 'Inspections', duration: 1, predecessorIds: ['pl-9', 'pl-10'], isMilestone: true, isCriticalPath: true, crewSize: 0 },
      { id: 'pl-12', name: 'Project Complete', phase: 'General', duration: 0, predecessorIds: ['pl-11'], isMilestone: true, isCriticalPath: true, crewSize: 0 },
    ],
  },
];
