const { withXcodeProject } = require('expo/config-plugins');

/**
 * Quote the command substitutions in the generated Xcode shell script phases.
 *
 * Both the React Native iOS template and `@sentry/react-native`'s Expo plugin
 * (v8.10.0, `plugin/build/withSentryIOS.js`) emit UNQUOTED backtick
 * substitutions into the "Bundle React Native code and images" and
 * "Upload Debug Symbols to Sentry" build phases, e.g.
 *
 *   /bin/sh `"$NODE_BINARY" --print "...sentry-xcode.sh"` `"$NODE_BINARY" --print "...react-native-xcode.sh"`
 *
 * `--print` returns an ABSOLUTE path. If any directory on that path contains a
 * space — this repo lives in "MAGE ID - CLAUDE" — the unquoted substitution
 * word-splits and the phase dies with:
 *
 *   /bin/sh: /Users/<user>/Desktop/MAGE: No such file or directory
 *
 * In Debug the phase body is a no-op (SKIP_BUNDLING=1), so the failure looks
 * cosmetic — but it still fails the phase, which cancels every LATER phase in
 * the target: "[CP] Embed Pods Frameworks" (hermes, React, ReactNativeDependencies),
 * "[CP] Copy Pods Resources" (the pod resource bundles) and the EXConstants
 * manifest never install. In Release it breaks JS bundling outright.
 *
 * `ios/` is gitignored and regenerated by `expo prebuild`, so patching
 * project.pbxproj by hand does not survive. This plugin re-applies the fix on
 * every prebuild. It must be listed AFTER "@sentry/react-native/expo" in
 * app.json so it runs on the already-injected Sentry script.
 *
 * The rewrite is `\`cmd\`` -> `"$(cmd)"`, which is POSIX-identical apart from
 * suppressing word splitting (double quotes nest freely inside `$( )`).
 */

const PHASES_TO_FIX = ['Bundle React Native code and images', 'Upload Debug Symbols to Sentry'];

/**
 * Rewrite every backtick command substitution as a double-quoted `$( )`.
 * Idempotent: a script with no backticks is returned unchanged.
 * @param {string} script raw shell source
 * @returns {string}
 */
function quoteBacktickSubstitutions(script) {
  if (typeof script !== 'string' || !script.includes('`')) return script;
  return script.replace(/`([^`]+)`/g, (_match, inner) => `"$(${inner})"`);
}

const withQuotedXcodeScriptPaths = config =>
  withXcodeProject(config, cfg => {
    const xcodeProject = cfg.modResults;
    for (const phaseName of PHASES_TO_FIX) {
      const phase = xcodeProject.pbxItemByComment(phaseName, 'PBXShellScriptBuildPhase');
      if (!phase || typeof phase.shellScript !== 'string') continue;
      // pbxproj stores shellScript as a JSON-escaped string literal.
      const source = JSON.parse(phase.shellScript);
      const quoted = quoteBacktickSubstitutions(source);
      if (quoted !== source) {
        phase.shellScript = JSON.stringify(quoted);
      }
    }
    return cfg;
  });

module.exports = withQuotedXcodeScriptPaths;
module.exports.quoteBacktickSubstitutions = quoteBacktickSubstitutions;
module.exports.PHASES_TO_FIX = PHASES_TO_FIX;
