const { withXcodeProject, withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Quote the command substitutions in the generated Xcode shell script phases.
 *
 * Both the React Native iOS template and `@sentry/react-native`'s Expo plugin
 * (v8.10.0, `plugin/build/withSentryIOS.js`) emit UNQUOTED backtick
 * substitutions into the "Bundle React Native code and images" and
 * "Upload Debug Symbols to Sentry" build phases, e.g.
 *
 *   /bin/sh `"$NODE_BINARY" --print "...sentry-xcode.sh"` `"$NODE_BINARY" --print "...react-native-xcode.sh"`
 *
 * `--print` returns an ABSOLUTE path. If any directory on that path contains a
 * space — this repo lives in "MAGE ID - CLAUDE" — the unquoted substitution
 * word-splits and the phase dies with:
 *
 *   /bin/sh: /Users/<user>/Desktop/MAGE: No such file or directory
 *
 * In Debug the phase body is a no-op (SKIP_BUNDLING=1), so the failure looks
 * cosmetic — but it still fails the phase, which cancels every LATER phase in
 * the target: "[CP] Embed Pods Frameworks" (hermes, React, ReactNativeDependencies),
 * "[CP] Copy Pods Resources" (the pod resource bundles) and the EXConstants
 * manifest never install. In Release it breaks JS bundling outright.
 *
 * `ios/` is gitignored and regenerated by `expo prebuild`, so patching
 * project.pbxproj by hand does not survive. This plugin re-applies the fix on
 * every prebuild. It must be listed AFTER "@sentry/react-native/expo" in
 * app.json so it runs on the already-injected Sentry script.
 *
 * The rewrite is `\`cmd\`` -> `"$(cmd)"`, which is POSIX-identical apart from
 * suppressing word splitting (double quotes nest freely inside `$( )`).
 *
 * ── 2026-09-06: quoting the backticks was NOT sufficient ────────────────────
 * Verified by actually running a Release build (the first one since the iOS
 * build fix; docs/START-HERE.md said none had been). Three more instances of
 * the same class had to be closed before the app would launch:
 *
 * 1. `sentry-xcode.sh` takes the react-native-xcode.sh path as $1 and, on the
 *    SENTRY_DISABLE_AUTO_UPLOAD path, runs `/bin/sh -c "$REACT_NATIVE_XCODE"`.
 *    `sh -c` RE-PARSES that string, so a correctly-quoted argument splits all
 *    over again one level down. Fixed by wrapping the argument in literal
 *    single quotes so it survives the second parse (harmless without spaces).
 *
 * 2. CocoaPods emits `bash -l -c "$PODS_TARGET_SRCROOT/../scripts/<x>.sh"` for
 *    expo-constants' app.config phase and expo-updates' resources phase — same
 *    `-c` re-parse. Fixed in the Podfile post_install below, because
 *    Pods.xcodeproj is regenerated by `pod install`, not by prebuild.
 *
 * 3. expo-updates' and expo-constants' own scripts run
 *    `basename $PROJECT_DIR` unquoted. That one is inside node_modules, so it
 *    is re-applied by scripts/patch-ios-space-paths.sh on postinstall. It is
 *    the nastiest of the set: the garbage basename fails a `!= "Pods"` guard,
 *    the script exits 0, app.manifest is never written, THE BUILD SUCCEEDS,
 *    and the app dies at launch with "The embedded manifest is invalid or
 *    could not be read."
 *
 * All of it disappears if the checkout path has no spaces.
 */

const PHASES_TO_FIX = ['Bundle React Native code and images', 'Upload Debug Symbols to Sentry'];

/**
 * Rewrite every backtick command substitution as a double-quoted `$( )`.
 * Idempotent: a script with no backticks is returned unchanged.
 * @param {string} script raw shell source
 * @returns {string}
 */
function quoteBacktickSubstitutions(script) {
  if (typeof script !== 'string' || !script.includes('`')) return script;
  return script.replace(/`([^`]+)`/g, (_match, inner) => `"$(${inner})"`);
}

/**
 * `sentry-xcode.sh` does `/bin/sh -c "$REACT_NATIVE_XCODE"`, re-parsing its own
 * argument. Wrap that argument in literal single quotes so the second parse
 * keeps the path whole. No-op when already quoted.
 * @param {string} script
 * @returns {string}
 */
function singleQuoteReactNativeXcodeArg(script) {
  if (typeof script !== 'string') return script;
  if (!script.includes('react-native-xcode.sh')) return script;
  // Deterministic, not a regex: the argument is the final `"$( … )"` on the
  // line that names react-native-xcode.sh. Regexes get this wrong because the
  // same line carries a second, earlier `"$( … )"` for sentry-xcode.sh.
  const lines = script.split('\n');
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i];
    if (!line.includes('react-native-xcode.sh')) continue;
    // Already done. Without this, a second pass finds the EARLIER `"$(` (the
    // sentry-xcode.sh one) and wraps the wrong argument.
    if (line.includes('"\'$(')) return script;
    const open = line.lastIndexOf('"$(');
    if (open === -1) continue;
    if (line.startsWith('"\'', open)) continue; // already single-quoted
    const close = line.lastIndexOf(')"');
    if (close <= open) continue;
    const inner = line.slice(open + 1, close + 1); // the $( … ) itself
    lines[i] = `${line.slice(0, open)}"'${inner}'"${line.slice(close + 2)}`;
    return lines.join('\n');
  }
  return script;
}

/** Quote the `bash -l -c "<unquoted path>"` phases CocoaPods writes. */
const PODFILE_MARKER = '# withQuotedXcodeScriptPaths: quote bash -l -c paths';
const PODFILE_SNIPPET = `
    ${PODFILE_MARKER}
    # CocoaPods emits: bash -l -c "$PODS_TARGET_SRCROOT/../scripts/<x>.sh"
    # \`bash -c\` re-parses that string, so a checkout path containing a space
    # word-splits and the phase dies before a single file compiles. Re-quote the
    # inner path. Harmless when the path has no spaces.
    installer.pods_project.targets.each do |target|
      target.build_phases.each do |phase|
        next unless phase.respond_to?(:shell_script) && phase.shell_script
        next unless phase.shell_script.include?('bash -l -c "$PODS_TARGET_SRCROOT')
        phase.shell_script = phase.shell_script.gsub(
          /bash -l -c "(\\$PODS_TARGET_SRCROOT[^"]*)"/,
          'bash -l -c "\\\\"\\1\\\\""
        )
      end
    end
    installer.pods_project.save
`;

const withQuotedPodfileScriptPaths = config =>
  withDangerousMod(config, [
    'ios',
    cfg => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      if (!fs.existsSync(podfile)) return cfg;
      let src = fs.readFileSync(podfile, 'utf8');
      if (src.includes(PODFILE_MARKER)) return cfg;
      // Append inside the existing `post_install do |installer|` block.
      const idx = src.indexOf('post_install do |installer|');
      if (idx === -1) return cfg;
      const close = src.indexOf('\n  end', idx);
      if (close === -1) return cfg;
      src = src.slice(0, close) + '\n' + PODFILE_SNIPPET + src.slice(close);
      fs.writeFileSync(podfile, src);
      return cfg;
    },
  ]);

const withQuotedXcodeProjectPaths = config =>
  withXcodeProject(config, cfg => {
    const xcodeProject = cfg.modResults;
    for (const phaseName of PHASES_TO_FIX) {
      const phase = xcodeProject.pbxItemByComment(phaseName, 'PBXShellScriptBuildPhase');
      if (!phase || typeof phase.shellScript !== 'string') continue;
      // pbxproj stores shellScript as a JSON-escaped string literal.
      const source = JSON.parse(phase.shellScript);
      let quoted = quoteBacktickSubstitutions(source);
      quoted = singleQuoteReactNativeXcodeArg(quoted);
      if (quoted !== source) {
        phase.shellScript = JSON.stringify(quoted);
      }
    }
    return cfg;
  });

const withQuotedXcodeScriptPaths = config =>
  withQuotedPodfileScriptPaths(withQuotedXcodeProjectPaths(config));

module.exports = withQuotedXcodeScriptPaths;
module.exports.quoteBacktickSubstitutions = quoteBacktickSubstitutions;
module.exports.singleQuoteReactNativeXcodeArg = singleQuoteReactNativeXcodeArg;
module.exports.PHASES_TO_FIX = PHASES_TO_FIX;
