const { withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Force `:modular_headers => true` on the transitive Google/Firebase pods that
 * ship WITHOUT a module map.
 *
 * `@react-native-google-signin/google-signin` (v16, used in login/signup/auth)
 * pulls `GoogleSignIn` 9.x, which depends on the Swift pod `AppCheckCore` 11.x.
 * A Swift pod integrated as a STATIC LIBRARY can only `import` an Objective-C
 * dependency if that dependency defines a Clang module — and two of
 * AppCheckCore's deps, `GoogleUtilities` and `RecaptchaInterop`, do not. EAS's
 * `pod install` (strict) aborts the whole install with:
 *
 *   [!] The Swift pod `AppCheckCore` depends upon `GoogleUtilities` and
 *   `RecaptchaInterop`, which do not define modules. To opt into those targets
 *   generating module maps ... set `use_modular_headers!` globally in your
 *   Podfile, or specify `:modular_headers => true` for particular dependencies.
 *   pod install exited with non-zero code: 1
 *
 * A local `pod install` (CocoaPods 1.16.2) happened not to trip this, which is
 * why five EAS builds died at "Install pods" while local always succeeded.
 *
 * We do NOT use `use_modular_headers!` globally: with React Native's pods
 * (non-modular `#import`s across React-Core et al.) a global flip has broken
 * compilation for others. Instead we declare ONLY the two named offenders with
 * modular headers. Declaring a transitive pod explicitly is the supported way to
 * attach the flag; no version is pinned, so CocoaPods still resolves the version
 * AppCheckCore requires.
 *
 * `ios/` is gitignored and regenerated by `expo prebuild`, so this re-applies on
 * every prebuild. Idempotent: re-running never duplicates the lines.
 */

const MODULAR_HEADER_PODS = ['GoogleUtilities', 'RecaptchaInterop'];

/**
 * Insert `pod '<name>', :modular_headers => true` for each pod, immediately
 * after the first `target '...' do` line, unless already present.
 * @param {string} contents raw Podfile source
 * @returns {string}
 */
function addModularHeaders(contents) {
  const targetLine = /^(target\s+['"][^'"]+['"]\s+do[^\n]*)$/m;
  const match = contents.match(targetLine);
  if (!match) return contents;

  const additions = MODULAR_HEADER_PODS
    .filter(name => !new RegExp(`pod\\s+['"]${name}['"]\\s*,\\s*:modular_headers\\s*=>\\s*true`).test(contents))
    .map(name => `  pod '${name}', :modular_headers => true`);

  if (additions.length === 0) return contents;

  return contents.replace(targetLine, `${match[1]}\n${additions.join('\n')}`);
}

const withGoogleModularHeaders = config =>
  withDangerousMod(config, [
    'ios',
    cfg => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      const source = fs.readFileSync(podfile, 'utf8');
      const patched = addModularHeaders(source);
      if (patched !== source) fs.writeFileSync(podfile, patched);
      return cfg;
    },
  ]);

module.exports = withGoogleModularHeaders;
module.exports.addModularHeaders = addModularHeaders;
module.exports.MODULAR_HEADER_PODS = MODULAR_HEADER_PODS;
