// utils/automation/eventToScheduleWork.ts
//
// THE FACTORY (pure, no side effects). Turns an automation event — "this
// inspection must be booked ahead of that gating task" — into DRAFT
// ScheduleTask(s) the caller commits. It does NOT mutate the schedule, does
// NOT persist, and invents NO scheduling math: it expresses the linkage in the
// existing CPM dependency/lag model (utils/scheduleEngine.ts) and lets the
// engine place the tasks on commit.
//
// Contract (locked by the spec — Phase-2 units build against this verbatim):
//
//   eventToScheduleWork(req: ScheduleWorkRequest, schedule: ProjectSchedule)
//     => { tasks: ScheduleTask[]; unresolved: boolean }
//
// Behaviour:
//   • Produces a DRAFT inspection task (isAutoGenerated + sourceEventRef).
//   • RESOLVED (gating task found): the inspection PRECEDES the gating task
//     with the lead-time LAG. Expressed as an FS + lagDays link — the gating
//     task gains a dependency on the inspection ({ type:'FS', lagDays:lead }),
//     so CPM keeps the inspection lead-time days ahead of it. `tasks` contains
//     BOTH the new draft inspection AND the patched gating task (the caller
//     merges these into schedule.tasks). unresolved=false.
//   • UNRESOLVED (no id / hint matches nothing): the task is anchored SNET
//     (start-no-earlier) on its computed book-by date so it never silently
//     floats. unresolved=true. The caller surfaces "couldn't link — pick a
//     predecessor".
//   • IDEMPOTENT on sourceEventRef: if schedule.tasks already contains a task
//     with the same sourceEventRef, that existing task is returned as-is and
//     nothing new is created (never double-creates).
//
// PURE: no Date.now(), no random, no I/O. The only clock input is the
// schedule's own startDate (the calendar anchor CPM already uses); when it is
// absent the unresolved book-by date is omitted rather than invented.

import type { ScheduleTask, ProjectSchedule, DependencyLink } from '@/types';
import { getDepLinks } from '@/utils/scheduleEngine';

const MS_DAY = 86400000;

/**
 * The event contract. A caller (roadmap→schedule adapter, RFI trigger, …)
 * describes a piece of work that must be booked ahead of a gating task.
 *
 *   kind           — automation kind (mirrors leadTimeLibrary LeadTimeKind,
 *                    but kept a free string so new verticals don't need a
 *                    library entry to fire the factory).
 *   gatingTaskId   — exact id of the task this work must precede (preferred).
 *   gatingTaskHint — fuzzy fallback (title/phase keyword) when no id is known.
 *   leadTimeDays   — book-ahead lead (the FS lag). Sourced from
 *                    leadTimeLibrary by the caller so provenance stays there.
 *   whoActs        — who performs the booked work (gc | sub | owner).
 *   sourceEventRef — audit + idempotency handle (feature + source record id).
 *   title          — human title for the draft task.
 */
export interface ScheduleWorkRequest {
  kind: string;
  gatingTaskId?: string;
  gatingTaskHint?: string;
  leadTimeDays: number;
  whoActs: 'gc' | 'sub' | 'owner';
  sourceEventRef: { feature: string; id: string };
  title: string;
}

export interface ScheduleWorkResult {
  tasks: ScheduleTask[];
  unresolved: boolean;
}

/**
 * Deterministic id for an auto-task derived from its sourceEventRef. Keeping
 * the id a pure function of the ref (rather than a UUID) is what makes the
 * factory idempotent even across separate runs / processes: the same event
 * always yields the same task id, so a caller that keys by id also dedups.
 */
function autoTaskId(ref: { feature: string; id: string }): string {
  return `auto:${ref.feature}:${ref.id}`;
}

function sameRef(
  a: { feature: string; id: string } | undefined,
  b: { feature: string; id: string },
): boolean {
  return !!a && a.feature === b.feature && a.id === b.id;
}

/**
 * Resolve the gating task: exact id first, then a case-insensitive
 * title/phase substring on the hint (mirrors permitRoadmap.resolveGatingTask
 * so the two engines agree). Returns null when nothing matches.
 */
function resolveGatingTask(req: ScheduleWorkRequest, tasks: ScheduleTask[]): ScheduleTask | null {
  if (req.gatingTaskId) {
    const byId = tasks.find((t) => t.id === req.gatingTaskId);
    if (byId) return byId;
  }
  const hint = (req.gatingTaskHint || '').trim().toLowerCase();
  if (!hint) return null;
  return (
    tasks.find(
      (t) =>
        (t.title || '').toLowerCase().includes(hint) ||
        (t.phase || '').toLowerCase().includes(hint),
    ) ?? null
  );
}

function toISODate(ms: number): string {
  const d = new Date(ms);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

/**
 * Compute the book-by calendar date (ISO YYYY-MM-DD) for the UNRESOLVED path.
 * We have no gating task to subtract the lead from, so the honest, deterministic
 * book-by is the schedule's own start anchor pushed out by the lead time:
 * "book at least `lead` days from the schedule start." This is a real date the
 * reviewer can act on, not a silent float.
 *
 * Returns undefined when the schedule has no (valid) startDate — we never
 * invent a calendar anchor (that would flip CPM raw-day/calendar mode and
 * silently move dates). In that case the SNET anchor is set with no date and
 * the reviewer picks a predecessor.
 */
function computeBookByISO(
  schedule: ProjectSchedule,
  leadTimeDays: number,
): string | undefined {
  if (!schedule.startDate) return undefined;
  // Parse the ISO date as LOCAL midnight (not UTC) so lead-day arithmetic can't
  // drift a day across timezones: `new Date('2026-09-01')` is UTC midnight,
  // which reads back as the previous day in negative-offset zones. Split the
  // Y-M-D and build a local Date so the book-by date is stable everywhere.
  const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(schedule.startDate);
  if (!m) return undefined;
  const base = new Date(Number(m[1]), Number(m[2]) - 1, Number(m[3]));
  if (isNaN(base.getTime())) return undefined;
  return toISODate(base.getTime() + leadTimeDays * MS_DAY);
}

/**
 * Base DRAFT task shared by both paths. Duration 1 (an inspection/booking is
 * a point event), status not_started, progress 0, marked auto-generated and
 * stamped with the sourceEventRef for audit + idempotency.
 */
function baseDraftTask(req: ScheduleWorkRequest): ScheduleTask {
  return {
    id: autoTaskId(req.sourceEventRef),
    title: req.title,
    phase: 'Inspections',
    durationDays: 1,
    startDay: 1,
    progress: 0,
    crew: req.whoActs,
    dependencies: [],
    notes: '',
    status: 'not_started',
    isAutoGenerated: true,
    sourceEventRef: { ...req.sourceEventRef },
  };
}

/**
 * eventToScheduleWork — see file header for the full contract.
 */
export function eventToScheduleWork(
  req: ScheduleWorkRequest,
  schedule: ProjectSchedule,
): ScheduleWorkResult {
  const tasks = schedule.tasks ?? [];

  // ── IDEMPOTENCY: never double-create on the same sourceEventRef ──
  const existing = tasks.find((t) => sameRef(t.sourceEventRef, req.sourceEventRef));
  if (existing) {
    return { tasks: [existing], unresolved: false };
  }

  const gating = resolveGatingTask(req, tasks);
  const lead = Math.max(0, Math.round(req.leadTimeDays || 0));

  // ── UNRESOLVED: anchor SNET on the computed book-by date, never float ──
  if (!gating) {
    const draft = baseDraftTask(req);
    draft.anchorType = 'start-no-earlier';
    const bookBy = computeBookByISO(schedule, lead);
    if (bookBy) draft.anchorDate = bookBy;
    draft.notes = 'Auto-scheduled: could not link to a gating task — pick a predecessor.';
    return { tasks: [draft], unresolved: true };
  }

  // ── RESOLVED: inspection precedes the gating task by the lead-time lag ──
  // Expressed in the existing CPM model as an FS + lagDays dependency ON THE
  // GATING TASK (gating depends on the inspection). We do NOT reimplement
  // placement — CPM's recalculateStartDays honours the FS+lag and keeps the
  // inspection `lead` days ahead of the gating task's start.
  const draft = baseDraftTask(req);

  const newLink: DependencyLink = {
    taskId: draft.id,
    type: 'FS',
    lagDays: lead,
  };

  // Patch the gating task with the new predecessor link — normalized through
  // getDepLinks so a task that only had the legacy `dependencies` array gets a
  // complete dependencyLinks set (no dependency silently dropped).
  const existingLinks = getDepLinks(gating);
  const alreadyLinked = existingLinks.some((l) => l.taskId === draft.id);
  const patchedGating: ScheduleTask = {
    ...gating,
    dependencies: alreadyLinked
      ? gating.dependencies
      : [...gating.dependencies, draft.id],
    dependencyLinks: alreadyLinked ? existingLinks : [...existingLinks, newLink],
  };

  return { tasks: [draft, patchedGating], unresolved: false };
}
