// utils/automation/roadmapToScheduleWork.ts
//
// ROADMAP → SCHEDULE ADAPTER (pure, no side effects). Turns each
// `RoadmapInspection` from the permit roadmap (utils/permitRoadmap.ts) into a
// factory `ScheduleWorkRequest` and runs the FACTORY (eventToScheduleWork) to
// produce DRAFT tasks the review sheet presents. It invents NO scheduling math
// and NO lead times of its own:
//
//   • lead time comes from leadTimeLibrary (with provenance) unless the
//     inspection already carries an explicit `leadTimeDays` — an authored value
//     always wins over a library default, because it is more specific.
//   • linkage/placement is entirely eventToScheduleWork's job (FS+lag / SNET).
//
// The output is a per-inspection ReviewLine: the draft task(s) plus the
// provenance the sheet renders as a chip, plus whether the gating task
// resolved. Nothing here mutates the schedule or persists — the review sheet
// commits on confirm.
//
// PURE: no Date.now(), no random, no I/O. Idempotency is inherited from the
// factory (keyed on sourceEventRef): re-running the roadmap never double-adds.

import type {
  ProjectSchedule,
  RoadmapInspection,
  ScheduleTask,
} from '@/types';
import {
  eventToScheduleWork,
  type ScheduleWorkRequest,
} from '@/utils/automation/eventToScheduleWork';
import {
  getLeadTime,
  type LeadTime,
  type LeadTimeKind,
} from '@/utils/automation/leadTimeLibrary';

/** The feature tag stamped on every sourceEventRef this adapter produces.
 *  Kept a single exported constant so the sheet + tests never re-type it. */
export const ROADMAP_FEATURE = 'permitRoadmap';

/**
 * One reviewable line in the sheet — the draft tasks the factory produced for a
 * single roadmap inspection, plus everything the UI needs to render honestly:
 *   inspection  — the source record (title/description drive the row copy).
 *   draftTask   — the NEW draft inspection task (isAutoGenerated + sourceEventRef).
 *   tasks       — the full factory output (draft + any patched gating task) the
 *                 caller merges into schedule.tasks on commit.
 *   leadTime    — the resolved lead + its provenance (source/confidence chip).
 *   unresolved  — true when no gating task matched (SNET book-by, "pick a
 *                 predecessor"); surfaced so the sheet can flag it.
 */
export interface ReviewLine {
  inspection: RoadmapInspection;
  draftTask: ScheduleTask;
  tasks: ScheduleTask[];
  leadTime: LeadTime;
  unresolved: boolean;
}

/**
 * Map a roadmap inspection `type` onto a leadTimeLibrary kind. Inspections are
 * DOB/AHJ inspections, so the honest default kind is `dob_inspection`; a few
 * recognizable keywords route to the more specific kinds. Anything unknown
 * stays `dob_inspection` (the conservative inspection default) rather than
 * guessing a narrower kind.
 */
function inspectionKind(insp: RoadmapInspection): LeadTimeKind {
  const t = `${insp.type} ${insp.title}`.toLowerCase();
  if (t.includes('permit') && t.includes('review')) return 'permit_review';
  if (t.includes('submittal')) return 'submittal_review';
  if (t.includes('rfi')) return 'rfi_response';
  return 'dob_inspection';
}

/**
 * Build the factory request for one inspection. The gating link prefers the
 * explicit `gatesTaskId`, falling back to the fuzzy `gatesTaskHint` — exactly
 * the resolution order the factory (and permitRoadmap.resolveGatingTask) use.
 */
function toRequest(
  insp: RoadmapInspection,
  leadTimeDays: number,
): ScheduleWorkRequest {
  return {
    kind: inspectionKind(insp),
    gatingTaskId: insp.gatesTaskId,
    gatingTaskHint: insp.gatesTaskHint,
    leadTimeDays,
    whoActs: 'gc',
    sourceEventRef: { feature: ROADMAP_FEATURE, id: insp.id },
    title: insp.title,
  };
}

/**
 * Resolve the lead time for an inspection WITH provenance.
 *
 * An authored `leadTimeDays` on the inspection is the most specific signal we
 * have, so it wins and is reported `source: 'jurisdiction'` (it came grounded
 * in the roadmap's jurisdiction context) — never silently relabeled 'default'.
 * When the inspection carries no positive authored lead, we fall back to the
 * library default for its kind, carrying that provenance through untouched.
 */
function resolveLead(
  insp: RoadmapInspection,
  jurisdiction?: string,
): LeadTime {
  const authored = Math.round(insp.leadTimeDays);
  if (Number.isFinite(authored) && authored > 0) {
    return { days: authored, source: 'jurisdiction', confidence: 'high' };
  }
  return getLeadTime(inspectionKind(insp), jurisdiction);
}

/**
 * Turn a roadmap's inspections into review lines against the current schedule.
 *
 * PURE. Runs the factory per inspection and threads each result into a
 * ReviewLine. The `schedule` is read only (for gating-task resolution +
 * idempotency); nothing is mutated. The caller (review sheet) decides what to
 * commit and does so through the existing schedule mutation + CPM recompute.
 *
 * `jurisdiction` (optional) is passed to the lead-time library so a grounded
 * override can win over the default — same signature the rest of the engine
 * uses. Absent = library defaults.
 */
export function roadmapToScheduleWork(
  inspections: RoadmapInspection[],
  schedule: ProjectSchedule,
  jurisdiction?: string,
): ReviewLine[] {
  const lines: ReviewLine[] = [];
  for (const insp of inspections) {
    const leadTime = resolveLead(insp, jurisdiction);
    const req = toRequest(insp, leadTime.days);
    const result = eventToScheduleWork(req, schedule);

    // The draft inspection is the task carrying THIS inspection's
    // sourceEventRef. The factory may also return a patched gating task in the
    // resolved path; that one is not the draft. On the idempotent path the
    // single returned task is the pre-existing draft.
    const draftTask =
      result.tasks.find(
        (t) =>
          t.sourceEventRef?.feature === ROADMAP_FEATURE &&
          t.sourceEventRef?.id === insp.id,
      ) ?? result.tasks[0];

    lines.push({
      inspection: insp,
      draftTask,
      tasks: result.tasks,
      leadTime,
      unresolved: result.unresolved,
    });
  }
  return lines;
}

/**
 * Flatten review lines into the task list to COMMIT. Idempotent: a draft whose
 * id already exists in the current schedule is not re-added, and a patched
 * gating task REPLACES its prior version (so the new dependency link lands
 * without duplicating the row). The caller feeds the result to the existing
 * schedule mutation, which runs CPM recompute — we do NOT place tasks here.
 */
export function mergeReviewLines(
  lines: ReviewLine[],
  currentTasks: ScheduleTask[],
): ScheduleTask[] {
  const byId = new Map<string, ScheduleTask>();
  for (const t of currentTasks) byId.set(t.id, t);
  // Factory output overwrites by id — a patched gating task replaces its
  // original, a draft is added once. Map semantics give us idempotency for
  // free (same id never duplicated).
  for (const line of lines) {
    for (const t of line.tasks) byId.set(t.id, t);
  }
  return Array.from(byId.values());
}
