/**
 * Render coverage — the AUTOMATION REVIEW SHEET + ZONING CONFIRM-GATE, mounted
 * for real (spec Components 5 + 6, unit E).
 *
 * The discipline this closes: the automation engine produces DRAFT tasks
 * (isAutoGenerated, sourceEventRef) via eventToScheduleWork; the review sheet is
 * the ONLY thing that turns those drafts into a real schedule mutation, and it
 * must NOT do so until (a) the contractor presses Confirm and (b) the project's
 * zoning is confirmed (never auto-scheduling on a guessed district). A sheet
 * that committed on mount, or committed while zoning is a guess, would be
 * presenting a guess as truth — the exact thing the spec forbids.
 *
 * This mounts the real component inside the real ThemeProvider with a seeded
 * roadmap + schedule run through the real adapter (roadmapToScheduleWork), and
 * asserts:
 *   (a) draft tasks render — one row per roadmap inspection, provenance chip
 *       present;
 *   (b) nothing commits until Confirm is pressed — onConfirm fires zero times on
 *       mount and on Cancel, exactly once on Confirm;
 *   (c) the zoning confirm-gate BLOCKS the flow until confirmed — while zoning
 *       is a guess, pressing Confirm is inert; confirming zoning unblocks it.
 */

import React from 'react';
import { render, fireEvent } from '@testing-library/react-native';
import { SafeAreaProvider } from 'react-native-safe-area-context';
import { ThemeProvider } from '@/contexts/ThemeContext';
import { AutoScheduleReviewSheet } from '@/components/automation/AutoScheduleReviewSheet';
import {
  roadmapToScheduleWork,
  ROADMAP_FEATURE,
  type ReviewLine,
} from '@/utils/automation/roadmapToScheduleWork';
import type { ProjectSchedule, RoadmapInspection, ScheduleTask } from '@/types';

const METRICS = {
  frame: { x: 0, y: 0, width: 390, height: 844 },
  insets: { top: 47, left: 0, right: 0, bottom: 34 },
};

function Wrapper({ children }: { children: React.ReactNode }) {
  return (
    <SafeAreaProvider initialMetrics={METRICS}>
      <ThemeProvider>{children}</ThemeProvider>
    </SafeAreaProvider>
  );
}

/** A minimal but real schedule: one framing task the roadmap can gate against,
 *  plus one task no inspection will match (to force an unresolved line). */
function seedSchedule(): ProjectSchedule {
  const tasks: ScheduleTask[] = [
    {
      id: 'task-framing',
      title: 'Framing',
      phase: 'Structure',
      durationDays: 10,
      startDay: 5,
      progress: 0,
      crew: 'framing',
      dependencies: [],
      notes: '',
      status: 'not_started',
    },
    {
      id: 'task-drywall',
      title: 'Drywall',
      phase: 'Interior',
      durationDays: 6,
      startDay: 20,
      progress: 0,
      crew: 'finish',
      dependencies: [],
      notes: '',
      status: 'not_started',
    },
  ];
  return {
    id: 'sched-1',
    name: 'Test schedule',
    projectId: 'proj-1',
    startDate: '2026-09-01',
    workingDaysPerWeek: 5,
    bufferDays: 0,
    tasks,
    totalDurationDays: 30,
    criticalPathDays: 30,
    laborAlignmentScore: 1,
    riskItems: [],
    updatedAt: '2026-08-19T00:00:00.000Z',
  };
}

/** Two inspections: one gates the framing task (RESOLVED), one gates a hint that
 *  matches nothing (UNRESOLVED — anchored to its book-by date). */
function seedInspections(): RoadmapInspection[] {
  return [
    {
      id: 'insp-framing',
      type: 'framing_inspection',
      title: 'Framing / rough inspection',
      description: 'DOB framing inspection before closing walls.',
      gatesTaskHint: 'Framing',
      leadTimeDays: 8,
      status: 'pending',
    },
    {
      id: 'insp-orphan',
      type: 'final_inspection',
      title: 'Certificate of Occupancy inspection',
      description: 'Final CO inspection — no matching task yet.',
      gatesTaskHint: 'this-phrase-matches-nothing',
      leadTimeDays: 10,
      status: 'pending',
    },
  ];
}

function buildLines(): ReviewLine[] {
  return roadmapToScheduleWork(seedInspections(), seedSchedule());
}

describe('automation review sheet — adapter produces reviewable draft lines', () => {
  it('turns each roadmap inspection into a draft line with provenance', () => {
    const lines = buildLines();
    expect(lines).toHaveLength(2);

    // Every draft task is auto-generated, stamped with the roadmap
    // sourceEventRef, and carries a lead time with provenance.
    for (const line of lines) {
      expect(line.draftTask.isAutoGenerated).toBe(true);
      expect(line.draftTask.sourceEventRef).toEqual({
        feature: ROADMAP_FEATURE,
        id: line.inspection.id,
      });
      expect(line.leadTime.days).toBeGreaterThan(0);
      expect(line.leadTime.source).toBeTruthy();
      expect(line.leadTime.confidence).toBeTruthy();
    }
  });

  it('surfaces an AI-authored inspection lead as ai_estimate/low — NEVER jurisdiction/high (the honesty blocker)', () => {
    // Both seeded inspections carry an authored leadTimeDays (8 and 10). Those
    // are LLM outputs from generateRoadmap, grounded only in free-text location
    // — there is NO jurisdiction dataset behind them. Stamping them
    // 'jurisdiction'/'high' would present a guess as truth (the spec's cardinal
    // violation). They MUST surface as an honest AI estimate the contractor
    // confirms.
    const lines = buildLines();
    for (const line of lines) {
      const authored = Math.round(line.inspection.leadTimeDays);
      expect(authored).toBeGreaterThan(0);
      // The days carry the authored value...
      expect(line.leadTime.days).toBe(authored);
      // ...but the PROVENANCE is honest: an unverified AI guess, low confidence.
      expect(line.leadTime.source).toBe('ai_estimate');
      expect(line.leadTime.confidence).toBe('low');
      // And it is EXACTLY NOT the dishonest label the reviewer rejected.
      expect(line.leadTime.source).not.toBe('jurisdiction');
      expect(line.leadTime.confidence).not.toBe('high');
    }
  });

  it('resolves the framing inspection to the framing task and orphans the CO one', () => {
    const lines = buildLines();
    const framing = lines.find((l) => l.inspection.id === 'insp-framing')!;
    const orphan = lines.find((l) => l.inspection.id === 'insp-orphan')!;

    // Resolved: factory returned the draft AND the patched gating task; the
    // draft is NOT anchored (it hangs off the FS+lag link instead).
    expect(framing.unresolved).toBe(false);
    expect(framing.tasks.some((t) => t.id === 'task-framing')).toBe(true);

    // Unresolved: no gating task matched, so it is anchored SNET on its book-by
    // date rather than silently floating.
    expect(orphan.unresolved).toBe(true);
    expect(orphan.draftTask.anchorType).toBe('start-no-earlier');
  });

  it('is idempotent — re-running against a schedule that already has the drafts adds nothing new', () => {
    const schedule = seedSchedule();
    const lines = buildLines();
    // Commit the drafts into the schedule, then re-run the adapter.
    const committed = schedule.tasks.concat(lines.map((l) => l.draftTask));
    const rerun = roadmapToScheduleWork(seedInspections(), {
      ...schedule,
      tasks: committed,
    });
    // Same draft ids come back — the factory returns the existing tasks, never
    // a second copy.
    for (const line of rerun) {
      const priorIds = committed.filter(
        (t) => t.sourceEventRef?.id === line.inspection.id,
      );
      expect(priorIds).toHaveLength(1);
      expect(line.draftTask.id).toBe(priorIds[0].id);
    }
  });
});

describe('automation review sheet — (a) draft tasks render', () => {
  it('renders one row per inspection with the lead-time provenance chip', () => {
    const lines = buildLines();
    const tree = render(
      <AutoScheduleReviewSheet
        lines={lines}
        zoning={{ district: 'R-5', status: 'confirmed' }}
        onConfirm={jest.fn()}
        onCancel={jest.fn()}
      />,
      { wrapper: Wrapper },
    );

    // The sheet mounted, not the empty branch.
    expect(tree.getByTestId('auto-schedule-review-sheet')).toBeTruthy();
    expect(tree.getByTestId('review-sheet-title')).toBeTruthy();

    // A row per inspection, each showing its draft title + a provenance chip.
    for (const line of lines) {
      expect(tree.getByTestId(`review-row-${line.inspection.id}`)).toBeTruthy();
      expect(
        tree.getByTestId(`review-row-title-${line.inspection.id}`),
      ).toBeTruthy();
    }
    expect(tree.getAllByTestId('lead-time-chip')).toHaveLength(lines.length);

    // The unresolved CO inspection is flagged in the row, not silently dropped.
    expect(tree.getByTestId('review-row-unresolved-insp-orphan')).toBeTruthy();
    expect(tree.getByTestId('unresolved-note')).toBeTruthy();
  });

  it('renders the AI-authored lead chip HONESTLY — "AI estimate · confirm", never "Jurisdiction · high"', () => {
    const lines = buildLines();
    const tree = render(
      <AutoScheduleReviewSheet
        lines={lines}
        zoning={{ district: 'R-5', status: 'confirmed' }}
        onConfirm={jest.fn()}
        onCancel={jest.fn()}
      />,
      { wrapper: Wrapper },
    );

    const chips = tree.getAllByTestId('lead-time-chip');
    expect(chips).toHaveLength(lines.length);
    for (const chip of chips) {
      const text = chip.props.children?.props?.children ?? '';
      // Honest AI-estimate chip copy: names it a guess and asks for confirmation.
      expect(text).toContain('AI estimate');
      expect(text).toContain('confirm');
      // Must NEVER dress an AI guess up as a grounded jurisdiction fact.
      expect(text).not.toContain('Jurisdiction');
      expect(text).not.toContain('high confidence');
    }
  });
});

describe('automation review sheet — (b) nothing commits until confirm', () => {
  it('does NOT call onConfirm on mount', () => {
    const onConfirm = jest.fn();
    render(
      <AutoScheduleReviewSheet
        lines={buildLines()}
        zoning={{ district: 'R-5', status: 'confirmed' }}
        onConfirm={onConfirm}
        onCancel={jest.fn()}
      />,
      { wrapper: Wrapper },
    );
    expect(onConfirm).not.toHaveBeenCalled();
  });

  it('does NOT call onConfirm when Cancel is pressed', () => {
    const onConfirm = jest.fn();
    const onCancel = jest.fn();
    const tree = render(
      <AutoScheduleReviewSheet
        lines={buildLines()}
        zoning={{ district: 'R-5', status: 'confirmed' }}
        onConfirm={onConfirm}
        onCancel={onCancel}
      />,
      { wrapper: Wrapper },
    );
    fireEvent.press(tree.getByTestId('review-cancel-btn'));
    expect(onCancel).toHaveBeenCalledTimes(1);
    expect(onConfirm).not.toHaveBeenCalled();
  });

  it('calls onConfirm EXACTLY once, with the lines, when Confirm is pressed (zoning confirmed)', () => {
    const lines = buildLines();
    const onConfirm = jest.fn();
    const tree = render(
      <AutoScheduleReviewSheet
        lines={lines}
        zoning={{ district: 'R-5', status: 'confirmed' }}
        onConfirm={onConfirm}
        onCancel={jest.fn()}
      />,
      { wrapper: Wrapper },
    );
    fireEvent.press(tree.getByTestId('review-confirm-btn'));
    expect(onConfirm).toHaveBeenCalledTimes(1);
    expect(onConfirm).toHaveBeenCalledWith(lines);
  });
});

describe('automation review sheet — (c) zoning confirm-gate blocks the flow', () => {
  it('shows the gate banner and does NOT commit while zoning is a guess', () => {
    const onConfirm = jest.fn();
    const tree = render(
      <AutoScheduleReviewSheet
        lines={buildLines()}
        zoning={{ district: 'R-5', status: 'guess' }}
        onConfirm={onConfirm}
        onCancel={jest.fn()}
        onConfirmZoning={jest.fn()}
      />,
      { wrapper: Wrapper },
    );

    // The gate is visible; the confirmed chip is not.
    expect(tree.getByTestId('zoning-gate-banner')).toBeTruthy();
    expect(tree.queryByTestId('zoning-confirmed-chip')).toBeNull();

    // The confirm button is disabled AND pressing it is inert (belt + braces:
    // the handler guards in code, not only via the disabled prop).
    const confirmBtn = tree.getByTestId('review-confirm-btn');
    expect(confirmBtn.props.accessibilityState?.disabled).toBe(true);
    fireEvent.press(confirmBtn);
    expect(onConfirm).not.toHaveBeenCalled();
  });

  it('treats ABSENT zoning as a guess (fail-closed) — flow blocked', () => {
    const onConfirm = jest.fn();
    const tree = render(
      <AutoScheduleReviewSheet
        lines={buildLines()}
        onConfirm={onConfirm}
        onCancel={jest.fn()}
      />,
      { wrapper: Wrapper },
    );
    expect(tree.getByTestId('zoning-gate-banner')).toBeTruthy();
    fireEvent.press(tree.getByTestId('review-confirm-btn'));
    expect(onConfirm).not.toHaveBeenCalled();
  });

  it('confirming zoning fires onConfirmZoning and unblocks commit on the next render', () => {
    const onConfirm = jest.fn();
    const onConfirmZoning = jest.fn();

    // First render: blocked. Pressing the zoning-confirm button calls the
    // caller's handler (which, in the app, stamps zoningConfirmedAt).
    const tree = render(
      <AutoScheduleReviewSheet
        lines={buildLines()}
        zoning={{ district: 'R-5', status: 'guess' }}
        onConfirm={onConfirm}
        onCancel={jest.fn()}
        onConfirmZoning={onConfirmZoning}
      />,
      { wrapper: Wrapper },
    );
    fireEvent.press(tree.getByTestId('confirm-zoning-btn'));
    expect(onConfirmZoning).toHaveBeenCalledTimes(1);
    // Still blocked until the parent flips the prop — confirm remains inert.
    fireEvent.press(tree.getByTestId('review-confirm-btn'));
    expect(onConfirm).not.toHaveBeenCalled();

    // Re-render with zoning now confirmed (as the parent would after the stamp).
    tree.rerender(
      <AutoScheduleReviewSheet
        lines={buildLines()}
        zoning={{ district: 'R-5', status: 'confirmed' }}
        onConfirm={onConfirm}
        onCancel={jest.fn()}
        onConfirmZoning={onConfirmZoning}
      />,
    );
    // Gate is gone, confirmed chip shows, and Confirm now commits.
    expect(tree.getByTestId('zoning-confirmed-chip')).toBeTruthy();
    expect(tree.queryByTestId('zoning-gate-banner')).toBeNull();
    fireEvent.press(tree.getByTestId('review-confirm-btn'));
    expect(onConfirm).toHaveBeenCalledTimes(1);
  });
});
