// components/livingModel/styles.ts — the shared look of the Living Model screens.
// Theme tokens only: no colour is written here. Flat: no gradient, no blur.
import { StyleSheet } from 'react-native';
import type { ThemeColors } from '@/constants/colors';
import { Layout, Tokens } from '@/constants/designTokens';
import { Type } from '@/constants/typography';
import { cardSurface } from '@/components/ui/Card';
import { labelOn } from '@/components/ui/ink';

export const makeLivingModelStyles = (t: ThemeColors) => StyleSheet.create({
  screen: { flex: 1, backgroundColor: t.bg },
  header: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 8, paddingHorizontal: 12, paddingBottom: 8 },
  backBtn: { width: 40, height: 40, alignItems: 'center' as const, justifyContent: 'center' as const },
  headerName: { ...Type.serifHeadline, color: t.text },
  headerSub: { fontSize: Type.caption1.fontSize, color: t.textMuted },
  tabs: { paddingHorizontal: 16, paddingBottom: 10 },
  body: { paddingHorizontal: 16, paddingBottom: 32, gap: 12 },
  bodyWide: { flexDirection: 'row' as const, alignItems: 'flex-start' as const, gap: 16 },
  // `stack` is a column inside the scrolling page (no flex: a flex: 1 child of a scroll view has no height). `colMain` is the wide layout's main column, in a row.
  stack: { gap: 12 },
  colMain: { flex: 1, gap: 12, minWidth: 0 },
  narrow: { width: '100%' as const, maxWidth: Layout.page.form, gap: 12 },
  colSide: { width: 340, gap: 12 },
  panel: { ...cardSurface(t, { pad: 14 }), gap: 10 },
  panelHeading: { fontSize: Type.subhead.fontSize, fontWeight: '700' as const, color: t.text },
  eyebrow: { fontSize: Type.caption2.fontSize, fontWeight: '700' as const, letterSpacing: 0.8, color: t.textMuted, textTransform: 'uppercase' as const },
  para: { fontSize: Type.subhead.fontSize, lineHeight: 21, color: t.textSecondary },
  note: { fontSize: Type.caption1.fontSize, lineHeight: 18, color: t.textMuted },
  noteStrong: { fontSize: Type.caption1.fontSize, lineHeight: 18, color: t.text, fontWeight: '600' as const },
  warn: { fontSize: Type.caption1.fontSize, lineHeight: 18, color: t.warningLabel },
  honesty: { gap: 2 },
  toolbar: { flexDirection: 'row' as const, flexWrap: 'wrap' as const, alignItems: 'center' as const, gap: 8 },
  toolBtn: { ...cardSurface(t, { radius: 'full', pad: 'none' }), flexDirection: 'row' as const, alignItems: 'center' as const, gap: 6, minHeight: 36, paddingHorizontal: 12 },
  toolBtnOn: { borderColor: t.accent, backgroundColor: t.accentSoft },
  toolBtnOff: { opacity: 0.4 },
  toolBtnText: { fontSize: Type.caption1.fontSize, fontWeight: '600' as const, color: t.text },
  toolBtnTextOn: { color: t.accentLabel },
  iconBtn: { ...cardSurface(t, { radius: 'full', pad: 'none' }), width: 36, height: 36, alignItems: 'center' as const, justifyContent: 'center' as const },
  planBox: { borderRadius: Tokens.radius.lg, borderWidth: 1, borderColor: t.line, backgroundColor: t.surfaceAlt, overflow: 'hidden' as const },
  planLabel: { position: 'absolute' as const, alignItems: 'center' as const },
  planLabelName: { fontSize: Type.caption1.fontSize, fontWeight: '700' as const, color: t.text, textAlign: 'center' as const },
  planLabelSub: { fontSize: Type.caption2.fontSize, color: t.textSecondary, textAlign: 'center' as const },
  row: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 10, paddingVertical: 10, borderTopWidth: 1, borderTopColor: t.line },
  rowFirst: { borderTopWidth: 0, paddingTop: 0 },
  rowOn: { backgroundColor: t.accentSoft, marginHorizontal: -8, paddingHorizontal: 8, borderRadius: Tokens.radius.md, borderTopColor: 'transparent' as const },
  rowMain: { flex: 1, gap: 2, minWidth: 0 },
  rowLabel: { fontSize: Type.subhead.fontSize, fontWeight: '600' as const, color: t.text },
  rowSub: { fontSize: Type.caption1.fontSize, color: t.textMuted },
  rowValue: { fontSize: Type.subhead.fontSize, fontWeight: '700' as const, color: t.text },
  swatch: { width: 12, height: 12, borderRadius: Tokens.radius.full },
  tick: { width: 22, height: 22, borderRadius: Tokens.radius.sm, borderWidth: 1.5, borderColor: t.line, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: t.bg },
  tickOn: { borderColor: t.accent, backgroundColor: t.accentFill },
  suggestBox: { borderRadius: Tokens.radius.md, borderWidth: 1, borderColor: t.accent, borderStyle: 'dashed' as const, padding: 10, gap: 8 },
  suggestList: { maxHeight: 220 },
  suggestLine: { fontSize: Type.caption1.fontSize, lineHeight: 20, color: t.textSecondary },
  taskRow: { paddingVertical: 10, borderTopWidth: 1, borderTopColor: t.line, gap: 8 },
  taskRowTop: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 10 },
  taskTick: { flex: 1, flexDirection: 'row' as const, alignItems: 'center' as const, gap: 10, minWidth: 0 },
  stageBtn: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 6, minHeight: 32, maxWidth: 190, paddingHorizontal: 10, borderRadius: Tokens.radius.full, borderWidth: 1, borderColor: t.line },
  stageBtnText: { fontSize: Type.caption1.fontSize, fontWeight: '600' as const, color: t.textSecondary, flexShrink: 1 },
  stagePicker: { flexDirection: 'row' as const, flexWrap: 'wrap' as const, gap: 8, paddingLeft: 32 },
  noStart: { gap: 8, alignItems: 'flex-start' as const },
  suggestTag: { fontSize: Type.caption2.fontSize, fontWeight: '700' as const, color: t.accentLabel },
  field: { gap: 6 },
  fieldLabel: { fontSize: Type.caption1.fontSize, fontWeight: '600' as const, color: t.textSecondary },
  input: { borderWidth: 1, borderColor: t.line, borderRadius: Tokens.radius.md, paddingHorizontal: 12, paddingVertical: 10, fontSize: Type.body.fontSize, color: t.text, backgroundColor: t.bg },
  fieldRow: { flexDirection: 'row' as const, gap: 10 },
  fieldCell: { flex: 1, gap: 6 },
  chips: { flexDirection: 'row' as const, flexWrap: 'wrap' as const, gap: 8 },
  chip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: Tokens.radius.full, borderWidth: 1.5, borderColor: t.line },
  chipOn: { borderColor: t.accent, backgroundColor: t.accentSoft },
  chipText: { fontSize: Type.caption1.fontSize, fontWeight: '600' as const, color: t.textSecondary },
  chipTextOn: { color: t.accentLabel },
  sheetBody: { padding: 16, gap: 14 },
  empty: { alignItems: 'center' as const, gap: 6, paddingVertical: 28, paddingHorizontal: 16 },
  emptyName: { fontSize: Type.headline.fontSize, fontWeight: '700' as const, color: t.text },
  // replay
  stage3d: { borderRadius: Tokens.radius.lg, borderWidth: 1, borderColor: t.line, backgroundColor: t.bg, overflow: 'hidden' as const },
  hud: { position: 'absolute' as const, left: 12, top: 12, ...cardSurface(t, { pad: 12 }), gap: 6, maxWidth: 300 },
  hudWeek: { ...Type.serifHeadline, color: t.text },
  todayTag: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: Tokens.radius.sm, backgroundColor: t.accentFill },
  todayTagText: { fontSize: Type.caption2.fontSize, fontWeight: '700' as const, color: labelOn(t.accentFill), letterSpacing: 0.6, textTransform: 'uppercase' as const },
  hudRow: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 8, flexWrap: 'wrap' as const },
  legend: { flexDirection: 'row' as const, flexWrap: 'wrap' as const, columnGap: 12, rowGap: 4 },
  legendItem: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 6 },
  legendText: { fontSize: Type.caption1.fontSize, color: t.textSecondary },
  viewBtns: { position: 'absolute' as const, right: 12, bottom: 12, flexDirection: 'row' as const, gap: 8 },
  stageNote: { position: 'absolute' as const, left: 12, bottom: 12 },
  stageLost: { position: 'absolute' as const, left: 12, right: 12, bottom: 56, ...cardSurface(t, { pad: 12 }), gap: 10, alignItems: 'flex-start' as const },
  pin: { position: 'absolute' as const, left: 0, top: 0, ...cardSurface(t, { pad: 'none', radius: 'md' }), paddingHorizontal: 8, paddingVertical: 4, alignItems: 'center' as const },
  pinHead: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 5 },
  pinDot: { width: 9, height: 9, borderWidth: 1, borderColor: t.line },
  pinOn: { borderColor: t.accent, borderWidth: 2 },
  pinName: { fontSize: Type.caption1.fontSize, fontWeight: '700' as const, color: t.text },
  pinSub: { fontSize: Type.caption2.fontSize, color: t.textSecondary },
  controls: { ...cardSurface(t, { pad: 12 }), gap: 10 },
  controlsTop: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 10, flexWrap: 'wrap' as const },
  playBtn: { width: 44, height: 44, borderRadius: Tokens.radius.full, alignItems: 'center' as const, justifyContent: 'center' as const, backgroundColor: t.accentFill },
  weekText: { fontSize: Type.subhead.fontSize, fontWeight: '700' as const, color: t.text },
  spacer: { flex: 1 },
  modeSeg: { minWidth: 232 },
  track: { height: 34, justifyContent: 'center' as const },
  trackRail: { height: 12, borderRadius: Tokens.radius.full, backgroundColor: t.surfaceAlt, overflow: 'hidden' as const, flexDirection: 'row' as const },
  trackPast: { position: 'absolute' as const, left: 0, top: 11, height: 12, borderRadius: Tokens.radius.full, backgroundColor: t.accent },
  trackPlan: { position: 'absolute' as const, top: 11, height: 12, backgroundColor: t.accentSoft },
  trackToday: { position: 'absolute' as const, top: 2, width: 2, height: 30, backgroundColor: t.text },
  trackKnob: { position: 'absolute' as const, top: 5, width: 24, height: 24, borderRadius: Tokens.radius.full, marginLeft: -12, backgroundColor: t.accentFill, borderWidth: 3, borderColor: t.surface },
  ticks: { flexDirection: 'row' as const, justifyContent: 'space-between' as const },
  tickText: { fontSize: Type.caption2.fontSize, color: t.textMuted },
  bar: { height: 8, borderRadius: Tokens.radius.full, backgroundColor: t.surfaceAlt, overflow: 'hidden' as const },
  barFill: { height: 8, borderRadius: Tokens.radius.full, backgroundColor: t.success },
  barFillPlan: { height: 8, borderRadius: Tokens.radius.full, backgroundColor: t.accent },
  nextBox: { borderRadius: Tokens.radius.md, backgroundColor: t.accentSoft, padding: 10, gap: 2 },
  nextText: { fontSize: Type.subhead.fontSize, color: t.text },
  doneText: { fontSize: Type.caption1.fontSize, fontWeight: '700' as const, color: t.successLabel },
  mutedValue: { fontSize: Type.caption1.fontSize, fontWeight: '600' as const, color: t.textMuted },
  blocked: { ...cardSurface(t, { pad: 16 }), margin: 16, gap: 12 },
  ownerRow: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 12, marginTop: 10 },
});
