// i18n/catalog/en/ai.ask.generated.ts — GENERATED by scripts/i18n-extract.ts (surface ai.ask).
// Do not edit by hand: change the inline English at the t()/tn() call site, then run
//   bun run scripts/i18n-extract.ts --surface ai.ask

import type { EnCatalog } from '../../types';

export const EN: EnCatalog = {
  "ai.ask.action.answerInstead": "Answer instead",
  "ai.ask.action.estimateFirst": "Build the estimate",
  "ai.ask.action.forJob": "For {job}",
  "ai.ask.action.honesty": "From what you typed. Nothing is saved until you check it and tap Build it.",
  "ai.ask.action.howtoTitle": "Want me to do it?",
  "ai.ask.action.label.estimateEdit": "Change the estimate",
  "ai.ask.action.lead.many": "I can do these. Start each one when you're ready.",
  "ai.ask.action.lead.one": "I can do that.",
  "ai.ask.action.nothing": "Nothing was saved.",
  "ai.ask.action.openAgain": "Open again",
  "ai.ask.action.openResult": "Open",
  "ai.ask.action.opened": "Opened {label}",
  "ai.ask.action.pickJobNext": "You'll pick the job next",
  "ai.ask.action.pickTitle": "Which job?",
  "ai.ask.action.saved": "Saved: {label}",
  "ai.ask.action.savedNoLabel": "Saved",
  "ai.ask.action.scheduleLeaves": "Opens the schedule. Ask closes on this phone.",
  "ai.ask.action.start": "Start",
  "ai.ask.action.startA11y": "Start {label}",
  "ai.ask.look.emptyHint": "Ask about your jobs, or tell MAGE to start something, like a daily report or a schedule.",
  "ai.ask.look.emptyTitle": "What do you need?",
  "ai.ask.look.jumpLatest": "Jump to latest",
  "ai.ask.look.placeholder": "Ask a question or say what to do",
  "ai.ask.look.sendHintBusy": "Wait for the answer to finish",
  "ai.ask.look.sendHintEmpty": "Type a question to send",
  "ai.ask.look.sources": "Sources",
  "ai.ask.look.stillThinking": "Still working on it",
  "ai.ask.look.thinking": "Reading your records",
  "ai.ask.look.thinkingA11y": "MAGE is reading your records",
  "ai.ask.look.title": "Ask MAGE",
};
