// i18n/catalog/en/common.errors.generated.ts — GENERATED by scripts/i18n-extract.ts (surface common.errors).
// Do not edit by hand: change the inline English at the t()/tn() call site, then run
//   bun run scripts/i18n-extract.ts --surface common.errors

import type { EnCatalog } from '../../types';

export const EN: EnCatalog = {
  "common.error.body.cancelled": "MAGE stopped trying. Nothing was changed. Start it again when you're ready.",
  "common.error.body.conflict": "Something with the same number or name is already saved. Change it, then try again.",
  "common.error.body.notFound": "The record it needs isn't there any more. It may have been deleted on another device. Go back, reopen the screen, then try again.",
  "common.error.body.offline": "This device isn't reaching the network. Check your signal or Wi-Fi, then try again.",
  "common.error.body.permission": "This sign-in doesn't have access to that record. Ask whoever owns the account to give you access.",
  "common.error.body.rateLimit": "Too many requests went out in a short window. Wait about a minute, then try again.",
  "common.error.body.schema": "This build of the app is asking the server for something it doesn't have yet. Close the app fully, reopen it to pick up the latest update, then try again.",
  "common.error.body.server": "The server returned an error.",
  "common.error.body.session": "The server no longer recognizes this sign-in, even though the app still looks signed in. Sign out and back in from Settings, then try again.",
  "common.error.body.timeout": "The server didn't answer in time. Try again in a moment.",
  "common.error.body.unknown": "MAGE couldn't finish that.",
  "common.error.keptOnDevice": "Nothing you entered was lost. It's still on this device.",
  "common.error.notSaved": "What you entered was not saved.",
  "common.error.reference": "(Reference: {code})",
  "common.error.supportNoReference": "Try again in a moment. If it keeps happening, tell support what you were doing when it failed.",
  "common.error.supportWithReference": "Try again in a moment. If it keeps happening, send support the reference below.",
  "common.error.title.cancelled": "Cancelled",
  "common.error.title.conflict": "That already exists.",
  "common.error.title.notFound": "That record is gone.",
  "common.error.title.offline": "You're offline.",
  "common.error.title.permission": "Not Allowed",
  "common.error.title.rateLimit": "Request Limit Reached",
  "common.error.title.schema": "MAGE needs to update.",
  "common.error.title.server": "MAGE hit a problem.",
  "common.error.title.session": "Signed Out",
  "common.error.title.timeout": "That took too long.",
  "common.error.title.unknown": "That didn't go through.",
};
