// i18n/catalog/en/common.moments.generated.ts — GENERATED by scripts/i18n-extract.ts (surface common.moments).
// Do not edit by hand: change the inline English at the t()/tn() call site, then run
//   bun run scripts/i18n-extract.ts --surface common.moments

import type { EnCatalog } from '../../types';

export const EN: EnCatalog = {
  "common.moment.binding": "Binding",
  "common.moment.cancel": "Cancel",
  "common.moment.chipAwaiting": "Awaiting your signature",
  "common.moment.chipAwaitingCountersign": "Signed · awaiting countersignature",
  "common.moment.chipEmailNotSent": "Signed · Email not sent",
  "common.moment.chipSentAwaiting": "Sent · awaiting {to}",
  "common.moment.clear": "Clear",
  "common.moment.counterSignNote": "They counter-sign from their portal link. The contract is binding when they sign.",
  "common.moment.done": "Done",
  "common.moment.earlierPending": "An earlier change to this record hasn't sent yet. Try again in a moment.",
  "common.moment.earlierUnsaved": "An earlier change to this record is under Not saved. Retry it first.",
  "common.moment.legalQueuedFallback": "Not signed. Signing needs a connection, so nothing was signed.",
  "common.moment.lineConsent": "Check the consent box",
  "common.moment.lineName": "Type your full legal name",
  "common.moment.lineSign": "Sign above the line",
  "common.moment.localOnlyNext": "Sign in to send it to your account.",
  "common.moment.localOnlyTitle": "Saved on this phone only",
  "common.moment.locked": "Locked",
  "common.moment.offlineCertifying": "You're offline. Certifying needs a connection.",
  "common.moment.offlineSigning": "You're offline. Signing needs a connection.",
  "common.moment.queued": "Saved on this phone · sends when online",
  "common.moment.refusedFallback": "Not saved. Something went wrong on our side.",
  "common.moment.rowSent": "Sent",
  "common.moment.rowSigned": "Signed",
  "common.moment.rowTerms": "Terms",
  "common.moment.rowTo": "To",
  "common.moment.sentTo": "Sent to {to}",
  "common.moment.shareLinkInstead": "Share the link instead.",
  "common.moment.signHere": "Sign here",
  "common.moment.signedEmailNotSent": "Signed. Email not sent.",
  "common.moment.signing": "Signing…",
  "common.moment.srHint": "Double-tap, then confirm",
  "common.moment.timeoutFallback": "No answer yet. Check the record before trying again.",
  "common.moment.transportFallback": "Not saved. The connection dropped, so nothing was saved.",
  "common.moment.transportUnknown": "No answer yet. The connection dropped, so it may still go through.",
};
