// i18n/catalog/en/common.tutorial.generated.ts — GENERATED by scripts/i18n-extract.ts (surface common.tutorial).
// Do not edit by hand: change the inline English at the t()/tn() call site, then run
//   bun run scripts/i18n-extract.ts --surface common.tutorial

import type { EnCatalog } from '../../types';

export const EN: EnCatalog = {};
