// i18n/catalog/en/desk.sidebar.generated.ts — GENERATED by scripts/i18n-extract.ts (surface desk.sidebar).
// Do not edit by hand: change the inline English at the t()/tn() call site, then run
//   bun run scripts/i18n-extract.ts --surface desk.sidebar

import type { EnCatalog } from '../../types';

export const EN: EnCatalog = {};
