// i18n/catalog/en/desk.crew-register.generated.ts — GENERATED by scripts/i18n-extract.ts (surface desk.crew-register).
// Do not edit by hand: change the inline English at the t()/tn() call site, then run
//   bun run scripts/i18n-extract.ts --surface desk.crew-register

import type { EnCatalog } from '../../types';

export const EN: EnCatalog = {};
