// i18n/catalog/en/field.home.generated.ts — GENERATED by scripts/i18n-extract.ts (surface field.home).
// Do not edit by hand: change the inline English at the t()/tn() call site, then run
//   bun run scripts/i18n-extract.ts --surface field.home

import type { EnCatalog } from '../../types';

export const EN: EnCatalog = {
  "field.home.moreOnSite": "+{todayOnSiteHidden} more on site today",
  "field.home.moreOnSiteA11y": { one: "{count} more project on site today. Opens summary.", other: "{count} more projects on site today. Opens summary." },
  "field.home.moreTasks": "+{count} more",
  "field.home.qfu.inProgress": "{task} is now in progress",
  "field.home.qfu.issueLogged": "Issue logged on {task}",
  "field.home.qfu.markedComplete": "{task} marked complete",
  "field.home.qfu.noSchedule": "No schedule on this project.",
  "field.home.qfu.noteAdded": "Note added to {task}",
  "field.home.qfu.pickProject": "Pick a project with a schedule first.",
  "field.home.qfu.placeholder": "\"drywall done floor 3\" or \"framing 80%\"",
  "field.home.qfu.project": "Project",
  "field.home.qfu.taskCount": { one: "{count} task", other: "{count} tasks" },
  "field.home.qfu.taskGone": "Not saved. {task} is no longer on this schedule. Pull to refresh and try again.",
  "field.home.qfu.title": "Quick Field Update",
  "field.home.qfu.viewOnly": "Not saved. You have view-only access to {project}. Ask the project owner for field or editor access.",
  "field.home.todayOnSite": "TODAY ON SITE",
};
