// i18n/catalog/en/field.shell.generated.ts — GENERATED by scripts/i18n-extract.ts (surface field.shell).
// Do not edit by hand: change the inline English at the t()/tn() call site, then run
//   bun run scripts/i18n-extract.ts --surface field.shell

import type { EnCatalog } from '../../types';

export const EN: EnCatalog = {
  "nav.title.crew": "Crew",
  "nav.title.dailyReport": "Daily Report",
  "nav.title.deliveries": "Deliveries",
  "nav.title.materialReceipt": "Material Receipt",
  "nav.title.photoTriage": "Photo Triage",
  "nav.title.punchList": "Punch List",
  "nav.title.safety": "Safety",
  "nav.title.safetyCertifications": "Certifications",
  "nav.title.safetyForms": "Forms Library",
  "nav.title.safetyHazards": "Hazard Log",
  "nav.title.safetyIncidents": "Incidents",
  "nav.title.safetyInspections": "Inspections",
  "nav.title.safetyJha": "JHAs",
  "nav.title.safetyOsha": "OSHA 300 Log",
  "nav.title.safetyToolbox": "Toolbox Talks",
  "nav.title.tabA11yPosition": "{label}, tab, {position} of {count}",
  "nav.title.timeTracking": "Time Tracking",
  "nav.title.tomorrowLineup": "Tomorrow's Lineup",
};
