// i18n/catalog/en/field.daily-report.generated.ts — GENERATED by scripts/i18n-extract.ts (surface field.daily-report).
// Do not edit by hand: change the inline English at the t()/tn() call site, then run
//   bun run scripts/i18n-extract.ts --surface field.daily-report

import type { EnCatalog } from '../../types';

export const EN: EnCatalog = {
  "field.dfr.card.daysLogged": "{filed} of {expected} working days logged",
  "field.dfr.card.daysMissing": { one: "{count} day missing", other: "{count} days missing" },
  "field.dfr.card.eyebrow": "Daily report · last 30 days",
  "field.dfr.card.gapManyProjects": "{projects} projects have gaps in the last 30 days — {days} working days between them.",
  "field.dfr.card.gapOneProject": { one: "{count} working day in the last 30 has no daily report.", other: "{count} working days in the last 30 have no daily report." },
  "field.dfr.card.more": "+{overflow} more",
  "field.dfr.card.noWorkDays": "{days} with no work on site",
  "field.dfr.card.openDailyReport": "Open daily report.",
  "field.dfr.card.openReportFor": "Open a report for {day}.",
  "field.dfr.card.openVoiceNote": "Open the voice note to finish it.",
  "field.dfr.card.opensDay": "opens {day}",
  "field.dfr.card.owedToday": { one: "{count} project has no daily report for today.", other: "{count} projects have no daily report for today." },
  "field.dfr.card.rowA11y": "{name}: {state}. {logged}. {action}",
  "field.dfr.card.todayNotFiled": "Today not filed",
  "field.dfr.card.voiceToFinish": { one: "{count} project has a voice note to finish.", other: "{count} projects have a voice note to finish." },
  "field.dfr.card.voiceToday": { one: "{count} project has only a voice note for today. Finish it to file the day.", other: "{count} projects have only a voice note for today. Finish it to file the day." },
  "field.dfr.card.why": "A daily report is worth more for being complete than for being detailed. If nothing happened on site, file the day and say so — that still counts. Tap a project with a gap to file its most recent missing day, dated the day it covers.",
};
