// i18n/catalog/en/field.photos.generated.ts — GENERATED by scripts/i18n-extract.ts (surface field.photos).
// Do not edit by hand: change the inline English at the t()/tn() call site, then run
//   bun run scripts/i18n-extract.ts --surface field.photos

import type { EnCatalog } from '../../types';

export const EN: EnCatalog = {};
