// i18n/catalog/en/field.time-clock.generated.ts — GENERATED by scripts/i18n-extract.ts (surface field.time-clock).
// Do not edit by hand: change the inline English at the t()/tn() call site, then run
//   bun run scripts/i18n-extract.ts --surface field.time-clock

import type { EnCatalog } from '../../types';

export const EN: EnCatalog = {};
