// i18n/catalog/en/money.co-proof.generated.ts — GENERATED by scripts/i18n-extract.ts (surface money.co-proof).
// Do not edit by hand: change the inline English at the t()/tn() call site, then run
//   bun run scripts/i18n-extract.ts --surface money.co-proof

import type { EnCatalog } from '../../types';

export const EN: EnCatalog = {
  "money.coProof.busy": "Building the packet…",
  "money.coProof.button": "Proof Packet",
  "money.coProof.failBody": "Couldn't build the proof packet. Try again.",
  "money.coProof.failTitle": "Could Not Make the Packet",
};
