// i18n/catalog/en/money.cost-xray.generated.ts — GENERATED by scripts/i18n-extract.ts (surface money.cost-xray).
// Do not edit by hand: change the inline English at the t()/tn() call site, then run
//   bun run scripts/i18n-extract.ts --surface money.cost-xray

import type { EnCatalog } from '../../types';

export const EN: EnCatalog = {
  "money.costXray.walkPricedTotal": "Priced on your costs: {amount} expected",
};
