// i18n/catalog/en/office.notices.generated.ts — GENERATED by scripts/i18n-extract.ts (surface office.notices).
// Do not edit by hand: change the inline English at the t()/tn() call site, then run
//   bun run scripts/i18n-extract.ts --surface office.notices

import type { EnCatalog } from '../../types';

export const EN: EnCatalog = {
  "office.notices.legal.reacceptAgreeBody": "By tapping I Agree you agree to the Terms of Service and the Privacy Policy.",
  "office.notices.legal.reacceptAgreeLabel": "I Agree",
  "office.notices.legal.reacceptBody": "To keep using MAGE ID, read the Terms of Service and the Privacy Policy and agree to them.",
  "office.notices.legal.reacceptChangedFirstBody": "This is the first time MAGE ID asks you to agree inside the app. The Terms of Service are dated May 12, 2026 and the Privacy Policy is dated October 4, 2026.",
  "office.notices.legal.reacceptChangedHeadingLabel": "What Changed",
  "office.notices.legal.reacceptPrivacyLinkLabel": "Read the Privacy Policy",
  "office.notices.legal.reacceptSignOutLabel": "Sign Out",
  "office.notices.legal.reacceptTermsLinkLabel": "Read the Terms of Service",
  "office.notices.legal.reacceptTitle": "Please read and agree to continue",
  "office.notices.scan.ackLabel": "I Understand",
  "office.notices.scan.body": "A scan is a first measure. It can be off by an inch or more. Check before you order, cut, price or build from it.",
  "office.notices.scan.title": "Before you rely on a scan",
};
