// i18n/catalog/en/office.protect.generated.ts — GENERATED by scripts/i18n-extract.ts (surface office.protect).
// Do not edit by hand: change the inline English at the t()/tn() call site, then run
//   bun run scripts/i18n-extract.ts --surface office.protect

import type { EnCatalog } from '../../types';

export const EN: EnCatalog = {
  "office.protect.agreeAnd": "and",
  "office.protect.agreeLead": "By continuing you agree to our",
  "office.protect.privacyPolicy": "Privacy Policy",
  "office.protect.templateNotice": "This is a starting template, not legal advice. It is not written for your state or your job. Have your own attorney review it before you use it.",
  "office.protect.termsOfService": "Terms of Service",
};
