// i18n/catalog/en/office.ny-contract.generated.ts — GENERATED by scripts/i18n-extract.ts (surface office.ny-contract).
// Do not edit by hand: change the inline English at the t()/tn() call site, then run
//   bun run scripts/i18n-extract.ts --surface office.ny-contract

import type { EnCatalog } from '../../types';

export const EN: EnCatalog = {
  "office.nyContract.alert.body": { one: "{count} item on the New York checklist is missing. You can still send it.", other: "{count} items on the New York checklist are missing. You can still send it." },
  "office.nyContract.alert.continue": "Continue",
  "office.nyContract.alert.review": "Review the list",
  "office.nyContract.alert.title": "Some New York items are missing",
  "office.nyContract.allFound": "Nothing missing. Check the flagged items with your counsel.",
  "office.nyContract.counsel": "To be confirmed by counsel",
  "office.nyContract.disclaimer": "This is a checklist, not legal advice.",
  "office.nyContract.maybe.amount": "New York’s rule covers contracts over $500 with the same owner. Check whether this project counts.",
  "office.nyContract.maybe.newHome": "New York’s rule covers work on existing homes. It may not apply to building a new home.",
  "office.nyContract.maybe.noState": "The jobsite address has no state. If the jobsite is in New York, this list applies.",
  "office.nyContract.openProfile": "Open company profile",
  "office.nyContract.reminder": "Give the owner a signed copy before work starts.",
  "office.nyContract.status.check": "Found wording, check it",
  "office.nyContract.status.found": "Found",
  "office.nyContract.status.missing": "Missing",
  "office.nyContract.summary": "{missing} missing · {check} to check",
  "office.nyContract.title": "New York contract checklist",
};
