// i18n/catalog/en/office.client-messages.generated.ts — GENERATED by scripts/i18n-extract.ts (surface office.client-messages).
// Do not edit by hand: change the inline English at the t()/tn() call site, then run
//   bun run scripts/i18n-extract.ts --surface office.client-messages

import type { EnCatalog } from '../../types';

export const EN: EnCatalog = {
  "office.clientMessages.attach.a11y": "Attach a photo or PDF",
  "office.clientMessages.attach.choosePdf": "Choose a PDF",
  "office.clientMessages.attach.choosePhotos": "Choose photos",
  "office.clientMessages.attach.sheetTitle": "Attach",
  "office.clientMessages.attach.takePhoto": "Take photo",
  "office.clientMessages.coPrefill.files": "Files: {names}",
  "office.clientMessages.fail.gone": "The file is no longer on this device. Remove the message and attach the file again.",
  "office.clientMessages.fail.refused": "The server didn't accept this file. Check that the client portal is on, then retry.",
  "office.clientMessages.fail.server": "The upload didn't finish. Retry when you have a good connection.",
  "office.clientMessages.fail.typeMismatch": "This file isn't the photo or PDF it says it is, so it wasn't sent.",
  "office.clientMessages.fail.writeFailed": "The files are uploaded but the message didn't send. Retry.",
  "office.clientMessages.open.failed": "Couldn't open the file. Check your connection and try again.",
  "office.clientMessages.open.popupBlocked": "Your browser blocked the new tab. Allow pop-ups for MAGE ID, then try again.",
  "office.clientMessages.pdf.a11y": "{name}, PDF, {size}. Opens the file.",
  "office.clientMessages.pdf.meta": "PDF · {size}",
  "office.clientMessages.photo.a11y": "Photo {name}. Opens full screen.",
  "office.clientMessages.photo.loadFailed": "Couldn't load this photo.",
  "office.clientMessages.photo.more": "+{count}",
  "office.clientMessages.refuse.cameraDenied": "MAGE ID needs camera access to take a photo. Turn it on in Settings.",
  "office.clientMessages.refuse.count": "A message can carry up to 10 files.",
  "office.clientMessages.refuse.empty": "{name} is empty, so it can't be sent.",
  "office.clientMessages.refuse.photosDenied": "MAGE ID needs photo access to attach a photo. Turn it on in Settings.",
  "office.clientMessages.refuse.size": "{name} is {size}. Files can be up to 20 MB.",
  "office.clientMessages.refuse.type": "{name} can't be sent. Send a photo (JPG, PNG or WebP) or a PDF.",
  "office.clientMessages.remove.body": "It was never sent. Its text and files are removed from this device.",
  "office.clientMessages.remove.title": "Remove this message?",
  "office.clientMessages.share": "Save or share",
  "office.clientMessages.share.unavailable": "Sharing isn't available on this device.",
  "office.clientMessages.state.notSent": "Not sent",
  "office.clientMessages.state.queued": "Waiting to send",
  "office.clientMessages.state.sending": "Sending…",
  "office.clientMessages.state.uploading": { one: "Uploading…", other: "Uploading {done} of {count}…" },
  "office.clientMessages.state.waitingNetwork": "Waiting for a connection. It sends when you're back online.",
  "office.clientMessages.state.waitingNetworkWeb": "Waiting for a connection. Keep this page open and it sends when you're back online.",
  "office.clientMessages.tray.remove.a11y": "Remove {name}",
};
