// i18n/catalog/en/office.living-model-phone.generated.ts — GENERATED by scripts/i18n-extract.ts (surface office.living-model-phone).
// Do not edit by hand: change the inline English at the t()/tn() call site, then run
//   bun run scripts/i18n-extract.ts --surface office.living-model-phone

import type { EnCatalog } from '../../types';

export const EN: EnCatalog = {
  "office.livingModelPhone.couldNotStartBody": "The 3D view could not start on this phone. The same replay is drawn flat below.",
  "office.livingModelPhone.modelA11yBody": "Schematic 3D model of the job. The room list below reads each room.",
  "office.livingModelPhone.needsNewVersionBody": "3D needs the newest version of the app.",
  "office.livingModelPhone.touchHelpSub": "Drag to turn. Use two fingers to move. Pinch to zoom. Tap a room to pick it",
};
