// i18n/catalog/en/office.project-health.generated.ts — GENERATED by scripts/i18n-extract.ts (surface office.project-health).
// Do not edit by hand: change the inline English at the t()/tn() call site, then run
//   bun run scripts/i18n-extract.ts --surface office.project-health

import type { EnCatalog } from '../../types';

export const EN: EnCatalog = {
  "office.projectHealth.legend.bubble": "The bubble moves right when the finish slips past the baseline.",
  "office.projectHealth.legend.colour": "The color is margin risk.",
  "office.projectHealth.legend.empty": "A gray, hollow level means there is not enough data yet.",
  "office.projectHealth.legend.listed": "Open punch, late RFIs and late tasks are listed, not drawn.",
  "office.projectHealth.title": "Project Health",
};
