// i18n/catalog/en/office.whoson.generated.ts — GENERATED by scripts/i18n-extract.ts (surface office.whoson).
// Do not edit by hand: change the inline English at the t()/tn() call site, then run
//   bun run scripts/i18n-extract.ts --surface office.whoson

import type { EnCatalog } from '../../types';

export const EN: EnCatalog = {
  "office.whoson.choice.body": "On a project someone shared with you, the project owner sees when you have it open and when you were last seen online there. On a project you own, your team members see when you have it open. Nothing is shown until you choose, and you can change it in Settings.",
  "office.whoson.choice.no": "Don't show it",
  "office.whoson.choice.title": "Show when you have a project open?",
  "office.whoson.choice.yes": "Show it",
  "office.whoson.empty.body": "Team members show up here after they accept your invite to this project, not when they only download MAGE ID.",
  "office.whoson.foot.gaps": "Work done without a signal, or on an older app version, doesn't show here. A team member can also choose not to show it.",
  "office.whoson.foot.meaning": "\"Has it open\" means the project is on that person's screen right now. It doesn't show what they are doing.",
  "office.whoson.foot.who": "Clients and subs who use a link instead of an account aren't listed here. Names and companies are what each person typed on their own profile; the email is the one you invited.",
  "office.whoson.owner.line": "Project owner: {name}",
  "office.whoson.owner.lineCompany": "Project owner: {name}, {company}",
  "office.whoson.row.joined": "Joined {date}",
  "office.whoson.row.joinedFromInvite": "Joined from your invite · {date}",
  "office.whoson.row.nameCompany": "{name} · {company}",
  "office.whoson.row.open": "Has it open now",
  "office.whoson.row.seenAt": "Last seen online here {date}, {time}",
  "office.whoson.row.seenDate": "Last seen online here {date}",
  "office.whoson.row.seenHr": { one: "Last seen online here 1 hr ago", other: "Last seen online here {count} hr ago" },
  "office.whoson.row.seenMin": { one: "Last seen online here 1 min ago", other: "Last seen online here {count} min ago" },
  "office.whoson.share.failed": "Couldn't save that. Try again.",
  "office.whoson.share.helper": "The project owner sees when you have their project open and when you were last seen online there. Your team members see when you have your project open. Turn it off and they stop seeing both, and your last seen times are deleted.",
  "office.whoson.share.label": "Show when I have a project open",
  "office.whoson.share.offlineWeb": "Needs a connection.",
  "office.whoson.stack.a11y": "Team on this project: {count}.",
  "office.whoson.stack.a11yEmpty": "No team members yet. Open the Team section.",
  "office.whoson.stack.a11yMember": "Team on this project.",
  "office.whoson.stack.a11yOpen": { one: "1 has it open now.", other: "{count} have it open now." },
  "office.whoson.stack.choose": "Choose what's shown",
  "office.whoson.stack.empty": "No team members yet",
  "office.whoson.stack.invite": "Invite",
  "office.whoson.stack.open": { one: "1 has it open", other: "{count} have it open" },
  "office.whoson.stack.ownerOpen": "The project owner has it open",
};
