// i18n/catalog/en/office.manage-sub.generated.ts — GENERATED by scripts/i18n-extract.ts (surface office.manage-sub).
// Do not edit by hand: change the inline English at the t()/tn() call site, then run
//   bun run scripts/i18n-extract.ts --surface office.manage-sub

import type { EnCatalog } from '../../types';

export const EN: EnCatalog = {
  "office.manageSub.apple.body": "You subscribed on iPhone. Manage it in your Apple account settings.",
  "office.manageSub.apple.downgrade": "You subscribed on iPhone. To switch to Free, cancel the subscription in your Apple account settings. Nothing is deleted.",
  "office.manageSub.apple.fallback": "On your iPhone, open the Settings app, tap your name, then Subscriptions.",
  "office.manageSub.byHand.body": "Email help@mageid.app to change or cancel. Nothing is deleted.",
  "office.manageSub.byHand.downgrade": "Your plan was turned on by MAGE ID, so there is no store subscription to cancel. Email help@mageid.app to switch to Free. Nothing is deleted.",
  "office.manageSub.byHand.fallback": "Email help@mageid.app to change or cancel your plan. Nothing is deleted.",
  "office.manageSub.byHand.label": "Your Plan Was Turned On by MAGE ID",
  "office.manageSub.elsewhere.body": "This plan was not bought on this phone. Manage it where you subscribed.",
  "office.manageSub.elsewhere.downgrade": "This plan was not bought on this phone. To switch to Free, cancel it where you subscribed. Nothing is deleted.",
  "office.manageSub.elsewhereWeb.body": "You subscribed in the web app. Manage it there, in Settings, Manage Subscription.",
  "office.manageSub.elsewhereWeb.downgrade": "You subscribed in the web app. To switch to Free, cancel the plan there, in Settings, Manage Subscription. Nothing is deleted.",
  "office.manageSub.email.body": "To change or cancel your plan, email help@mageid.app.",
  "office.manageSub.email.downgrade": "To switch to Free, email help@mageid.app. Nothing is deleted.",
  "office.manageSub.endsOn": "Ends on {date}",
  "office.manageSub.google.body": "You subscribed on Android. Manage it in your Google Play subscriptions.",
  "office.manageSub.google.downgrade": "You subscribed on Android. To switch to Free, cancel the subscription in Google Play. Nothing is deleted.",
  "office.manageSub.google.fallback": "On your Android phone, open Google Play, then Subscriptions.",
  "office.manageSub.label": "Manage Subscription",
  "office.manageSub.none.body": "There is no paid subscription on this account.",
  "office.manageSub.none.downgrade": "There is no paid subscription on this account, so there is nothing to cancel.",
  "office.manageSub.none.label": "No Paid Subscription",
  "office.manageSub.plan.downgrade": "Your {plan} plan can’t be changed from this screen. Nothing is deleted when a plan ends.",
  "office.manageSub.plan.label": "{plan} plan",
  "office.manageSub.renewsOn": "Renews on {date}",
  "office.manageSub.storeAndroid.body": "Opens your Google Play subscriptions, where you can change or cancel your plan.",
  "office.manageSub.storeAndroid.downgrade": "To switch to Free, cancel your subscription in your Google Play subscriptions. Manage Subscription on this screen opens them. Nothing is deleted.",
  "office.manageSub.storeAndroid.fallback": "Open Google Play, then Subscriptions to manage your MAGE ID plan.",
  "office.manageSub.storeIos.body": "Opens your App Store subscriptions, where you can change or cancel your plan.",
  "office.manageSub.storeIos.downgrade": "To switch to Free, cancel your subscription in your App Store subscriptions. Manage Subscription on this screen opens them. Nothing is deleted.",
  "office.manageSub.storeIos.fallback": "Open the Settings app, tap your name, then Subscriptions to manage your MAGE ID plan.",
  "office.manageSub.web.body": "Opens your billing page in a new tab, where you can change or cancel your plan.",
  "office.manageSub.web.downgrade": "To switch to Free, cancel your plan on your billing page. Manage Subscription on this screen opens it. Nothing is deleted.",
  "office.manageSub.web.fallback": "The billing page did not open. To change or cancel your plan, email help@mageid.app.",
};
