// i18n/catalog/en/schedule.lateness.generated.ts — GENERATED by scripts/i18n-extract.ts (surface schedule.lateness).
// Do not edit by hand: change the inline English at the t()/tn() call site, then run
//   bun run scripts/i18n-extract.ts --surface schedule.lateness

import type { EnCatalog } from '../../types';

export const EN: EnCatalog = {
  "schedule.lateness.applied": "+{days}d for {sub}'s track record",
  "schedule.lateness.evidence": { one: "Ran a median {median} working day over plan on your last {jobs} jobs.", other: "Ran a median {median} working days over plan on your last {jobs} jobs." },
  "schedule.lateness.evidenceResidual": { one: "Ran a median {median} working day over plan on your last {jobs} jobs, {days} beyond your usual {trade} pace.", other: "Ran a median {median} working days over plan on your last {jobs} jobs, {days} beyond your usual {trade} pace." },
  "schedule.lateness.fromContacts": "(from contacts)",
  "schedule.lateness.fromRecords": "From your records",
  "schedule.lateness.noSubs": "No subs yet. Add one from the Subs tab.",
  "schedule.lateness.offer": "Add {days}d for {sub}",
  "schedule.lateness.rowExcused": { one: "{count} task left out because a logged delay was not this sub's doing.", other: "{count} tasks left out because logged delays were not this sub's doing." },
  "schedule.lateness.rowLabel": "Runs long?",
  "schedule.lateness.rowLearned": { one: "Ran a median {days} working day over plan on your last {jobs} jobs ({tasks} tasks).", other: "Ran a median {days} working days over plan on your last {jobs} jobs ({tasks} tasks)." },
  "schedule.lateness.rowNotEnough": "Not enough history yet — {have} of {need} finished jobs with start and finish dates.",
  "schedule.lateness.rowOnPlan": "Finished on plan across your last {jobs} jobs.",
  "schedule.lateness.subFallback": "Sub",
  "schedule.lateness.supplierLate": { one: "{supplier} was late on {late} of their last {n} loads, by {avg} day on average.", other: "{supplier} was late on {late} of their last {n} loads, by {avg} days on average." },
  "schedule.lateness.switch": "Suggest extra days for this sub",
  "schedule.lateness.undo": "Undo",
  "schedule.lateness.undoA11y": "Remove the {days} extra days",
};
