// i18n/catalog/en/settings.learn.generated.ts — GENERATED by scripts/i18n-extract.ts (surface settings.learn).
// Do not edit by hand: change the inline English at the t()/tn() call site, then run
//   bun run scripts/i18n-extract.ts --surface settings.learn

import type { EnCatalog } from '../../types';

export const EN: EnCatalog = {};
