// i18n/catalog/en/unassigned.generated.ts — GENERATED by scripts/i18n-extract.ts (keys NO surface owns (must stay empty: i18n-extract --check fails otherwise)).
// Do not edit by hand: change the inline English at the t()/tn() call site, then run
//   bun run scripts/i18n-extract.ts --check

import type { EnCatalog } from '../../types';

export const EN: EnCatalog = {};
