// utils/recipientNotice.ts — the Notice To Recipients (PROTECT-TEXT, 2026-10-09).
//
// WHY: papers that leave the app used to say "generated by MAGE ID" or "Built
// with MAGE ID" in small grey italic. That puts MAGE ID in the author's seat in
// front of a bank, a surety, an owner or an architect who never agreed to
// anything. The contractor is the author. This file holds the ONE wording and
// the ONE helper every document builder, email layout and no-account page uses,
// so the sentence cannot drift from surface to surface.
//
// The wording is a draft for counsel (design-previews/legal/TERMS-DRAFT-CLAUSES.md,
// "Notice To Recipients"). Change it HERE and nowhere else;
// scripts/validate-protections.ts pins every surface to this text.
//
// PURE: no React Native, no Expo, no DOM. The static pages under marketing/
// cannot import it, so they carry the same two sentences as literals and the
// validator pins them equal to RECIPIENT_NOTICE_PARTS below.
//
// SIGNED RECORDS: the notice is page furniture. It is never written into a
// signer's consent record, a proposal's documentText or any other string a
// stored hash is taken over (those are hashed as DATA: see
// utils/portalOwnerCore.ts buildCOConsentRecord and utils/portalSnapshot.ts).
// A sealed PDF or sealed HTML is stored as bytes at the moment it is sealed, so
// a document sealed before this change keeps the footer it was sealed with.

/** What the notice says when the account has no company name on file. */
export const RECIPIENT_NOTICE_NO_COMPANY = 'the sender';

/** The two sentences, split around the company name. The static pages pin to these. */
export const RECIPIENT_NOTICE_PARTS = {
  before: 'Prepared by ',
  after: ' using MAGE ID software.',
  second: 'MAGE ID did not prepare, review or check this document and makes no statement to the reader about its contents.',
} as const;

/** The same notice in Spanish. Draft: a legal translator has not read it. */
export const RECIPIENT_NOTICE_PARTS_ES = {
  before: 'Preparado por ',
  after: ' con el software MAGE ID.',
  second: 'MAGE ID no preparó, revisó ni verificó este documento y no hace ninguna declaración al lector sobre su contenido.',
} as const;

export type RecipientNoticeLang = 'en' | 'es';

function cleanCompany(company: string | null | undefined): string {
  const c = String(company ?? '').replace(/\s+/g, ' ').trim();
  // "MAGE ID" is the old fallback some builders passed when the profile had no
  // company name. MAGE ID is never the author, so it never fills this blank.
  if (!c || /^mage\s*id$/i.test(c)) return RECIPIENT_NOTICE_NO_COMPANY;
  return c;
}

/** The notice as plain text. */
export function recipientNoticeText(company: string | null | undefined, lang: RecipientNoticeLang = 'en'): string {
  const p = lang === 'es' ? RECIPIENT_NOTICE_PARTS_ES : RECIPIENT_NOTICE_PARTS;
  const who = cleanCompany(company) === RECIPIENT_NOTICE_NO_COMPANY && lang === 'es' ? 'el remitente' : cleanCompany(company);
  return `${p.before}${who}${p.after} ${p.second}`;
}

function escHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c] as string));
}

/** A CSS string literal: safe inside `content: "..."` and inside a <style> tag. */
function cssString(s: string): string {
  return s
    .replace(/\\/g, '\\5C ')
    .replace(/"/g, '\\22 ')
    .replace(/</g, '\\3C ')
    .replace(/>/g, '\\3E ')
    .replace(/[\r\n\f]+/g, ' ');
}

/** The attribute every rendered notice carries. Builders and validators find it by this. */
export const RECIPIENT_NOTICE_MARK = 'data-recipient-notice';

/**
 * The notice as an HTML block: body size, ink colour, never grey, never italic.
 * Inline styles only, so it reads the same inside any document's own CSS and
 * inside an email client.
 */
export function recipientNoticeHtml(company: string | null | undefined, lang: RecipientNoticeLang = 'en'): string {
  return `<div ${RECIPIENT_NOTICE_MARK}="1" style="margin-top:24px;padding-top:12px;border-top:1px solid #0B0D10;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;font-size:12px;line-height:1.5;font-style:normal;font-weight:400;color:#0B0D10;text-align:left;page-break-inside:avoid;break-inside:avoid">${escHtml(recipientNoticeText(company, lang))}</div>`;
}

/**
 * The same sentence as a running footer on EVERY printed page, for print
 * engines that draw CSS page-margin boxes (Chrome, so the web app). iOS print
 * (WebKit) ignores the rule, which is why the block above is always in the
 * document as well.
 */
export function recipientNoticePageCss(company: string | null | undefined, lang: RecipientNoticeLang = 'en'): string {
  return `<style ${RECIPIENT_NOTICE_MARK}-page="1">@page { @bottom-center { content: "${cssString(recipientNoticeText(company, lang))}"; font-family: Helvetica, Arial, sans-serif; font-size: 8pt; line-height: 1.3; color: #0B0D10; } }</style>`;
}

/**
 * The mark of a document that prints its OWN Notice To Recipients on page one
 * and in a footer that repeats on every page (the Pay Period Record,
 * utils/proofPack/html.ts, whose longer notice is pinned word for word by
 * scripts/validate-proof-pack.ts). Such a document is left exactly as built.
 */
export const OWN_NOTICE_MARK = 'data-notice="page-footer"';

/** True when this HTML already carries the notice block, or its own repeating notice. */
export function hasRecipientNotice(html: string): boolean {
  return html.includes(`${RECIPIENT_NOTICE_MARK}="1"`) || html.includes(OWN_NOTICE_MARK);
}

/**
 * Put the notice on a finished HTML document: the block as the last thing in
 * the body (the document's footer, outside any form body) and the running
 * page footer in the head. Idempotent: a document that already has the block
 * is returned unchanged, so a builder that composes another builder's output
 * never prints it twice.
 */
export function withRecipientNotice(
  html: string,
  company: string | null | undefined,
  lang: RecipientNoticeLang = 'en',
  opts: { /** false when the document already repeats the first sentence on every page itself (the pay application's provenance line). */ pageFooter?: boolean } = {},
): string {
  if (hasRecipientNotice(html)) return html;
  const block = recipientNoticeHtml(company, lang);
  const pageCss = recipientNoticePageCss(company, lang);
  let out = html;
  const bodyEnd = out.lastIndexOf('</body>');
  out = bodyEnd >= 0 ? `${out.slice(0, bodyEnd)}${block}\n${out.slice(bodyEnd)}` : `${out}${block}`;
  if (opts.pageFooter === false) return out;
  const headEnd = out.indexOf('</head>');
  out = headEnd >= 0 ? `${out.slice(0, headEnd)}${pageCss}\n${out.slice(headEnd)}` : `${pageCss}${out}`;
  return out;
}
