// validate-event-to-schedule-work.ts — pins utils/automation/eventToScheduleWork.ts.
//
// Invariants (from the spec):
//   • DRAFT provenance: every produced task is isAutoGenerated + carries the
//     sourceEventRef.
//   • RESOLVED: inspection precedes the gating task by the lead-time LAG,
//     expressed FS + lagDays, and CPM (recalculateStartDays) actually places
//     it `lead` days ahead of the gating task's start.
//   • IDEMPOTENT: re-running with a task already bearing the same
//     sourceEventRef returns the existing task and creates nothing new.
//   • UNRESOLVED: no gating match → task anchored SNET (start-no-earlier) on
//     the computed book-by date, unresolved=true (never silently floats).
// Run: bun run scripts/validate-event-to-schedule-work.ts
import { eventToScheduleWork } from '../utils/automation/eventToScheduleWork';
import type { ScheduleWorkRequest } from '../utils/automation/eventToScheduleWork';
import { recalculateStartDays } from '../utils/scheduleEngine';
import type { ScheduleTask, ProjectSchedule } from '../types';

let pass = 0, fail = 0;
function ok(name: string, cond: boolean, detail?: string) {
  if (cond) { pass++; console.log('  ✓', name); }
  else { fail++; console.log('  ✗', name, detail ? `\n      ${detail}` : ''); }
}

function task(id: string, over: Partial<ScheduleTask> = {}): ScheduleTask {
  return {
    id, title: id, phase: 'General', durationDays: 3, startDay: 10, progress: 0,
    crew: '', dependencies: [], notes: '', status: 'not_started', ...over,
  };
}

function schedule(tasks: ScheduleTask[], startDate?: string): ProjectSchedule {
  return {
    id: 's1', name: 'S', projectId: 'p1',
    ...(startDate ? { startDate } : {}),
    workingDaysPerWeek: 5, bufferDays: 3, tasks,
    totalDurationDays: 20, criticalPathDays: 20, laborAlignmentScore: 80,
    riskItems: [], updatedAt: '2026-08-19T00:00:00.000Z',
  };
}

const REQ = (over: Partial<ScheduleWorkRequest> = {}): ScheduleWorkRequest => ({
  kind: 'dob_inspection',
  leadTimeDays: 7,
  whoActs: 'gc',
  sourceEventRef: { feature: 'permitRoadmap', id: 'insp-1' },
  title: 'Framing inspection',
  ...over,
});

console.log('\nevent → schedule work factory:');

// ── RESOLVED by id: FS + lag, draft provenance ──
{
  const gating = task('framing', { title: 'Framing', startDay: 20, durationDays: 5 });
  const sch = schedule([gating]);
  const res = eventToScheduleWork(REQ({ gatingTaskId: 'framing' }), sch);

  ok('resolved: unresolved=false', res.unresolved === false);
  ok('resolved: returns draft + patched gating', res.tasks.length === 2, `got ${res.tasks.length}`);

  const draft = res.tasks.find((t) => t.isAutoGenerated);
  const patched = res.tasks.find((t) => t.id === 'framing');
  ok('resolved: draft is auto-generated', !!draft && draft.isAutoGenerated === true);
  ok('resolved: draft carries sourceEventRef',
    !!draft && draft.sourceEventRef?.feature === 'permitRoadmap' && draft.sourceEventRef?.id === 'insp-1');
  ok('resolved: draft not committed as done', !!draft && draft.status === 'not_started' && draft.progress === 0);

  // the gating task now depends on the draft via FS + lag = leadTimeDays
  const link = patched?.dependencyLinks?.find((l) => l.taskId === draft!.id);
  ok('resolved: gating gains FS link to draft', !!link && link.type === 'FS');
  ok('resolved: lag equals lead time (7)', !!link && link.lagDays === 7, `got ${link?.lagDays}`);
  ok('resolved: gating.dependencies includes draft', !!patched && patched.dependencies.includes(draft!.id));

  // CPM actually honours the FS+lag: the gating task cannot start until
  // lead-time days after the inspection ends. The inspection is a bare
  // predecessor (no floor), so CPM binds the gating start to it exactly:
  //   gating.start == insp.end + lag.
  const resolved = recalculateStartDays([draft!, patched!]);
  const d = resolved.find((t) => t.id === draft!.id)!;
  const g = resolved.find((t) => t.id === 'framing')!;
  const inspEnd = d.startDay + d.durationDays; // FS convention in this engine
  ok('CPM: gating starts exactly lead-days after inspection ends (FS+lag honoured)',
    g.startDay === inspEnd + 7,
    `gatingStart=${g.startDay} inspEnd=${inspEnd}`);
  ok('CPM: FS+lag is a real floor (gating never starts before insp.end + lag)',
    g.startDay >= inspEnd + 7);
}

// ── IDEMPOTENT on sourceEventRef ──
{
  const gating = task('framing', { title: 'Framing', startDay: 20 });
  const first = eventToScheduleWork(REQ({ gatingTaskId: 'framing' }), schedule([gating]));
  const draft = first.tasks.find((t) => t.isAutoGenerated)!;

  // second run: the draft already lives in the schedule
  const gatingPatched = first.tasks.find((t) => t.id === 'framing')!;
  const sch2 = schedule([gatingPatched, draft]);
  const second = eventToScheduleWork(REQ({ gatingTaskId: 'framing' }), sch2);

  ok('idempotent: returns exactly one task', second.tasks.length === 1, `got ${second.tasks.length}`);
  ok('idempotent: returns the SAME existing task', second.tasks[0].id === draft.id);
  ok('idempotent: no duplicate created',
    sch2.tasks.filter((t) => t.sourceEventRef?.id === 'insp-1').length === 1);
  ok('idempotent: unresolved=false', second.unresolved === false);
}

// ── UNRESOLVED: SNET on computed book-by date, never floats ──
{
  const sch = schedule([task('demo', { title: 'Demo' })], '2026-09-01');
  const res = eventToScheduleWork(REQ({ gatingTaskHint: 'nonexistent-phase' }), sch);

  ok('unresolved: unresolved=true', res.unresolved === true);
  ok('unresolved: one draft task', res.tasks.length === 1);
  const d = res.tasks[0];
  ok('unresolved: anchored SNET (start-no-earlier)', d.anchorType === 'start-no-earlier', `got ${d.anchorType}`);
  ok('unresolved: still auto-generated + ref', d.isAutoGenerated === true && d.sourceEventRef?.id === 'insp-1');
  // book-by = schedule start + lead (7 days) = 2026-09-08
  ok('unresolved: anchorDate is the computed book-by date',
    d.anchorDate === '2026-09-08', `got ${d.anchorDate}`);
  ok('unresolved: has a date (does not float)', !!d.anchorDate);
}

// ── UNRESOLVED with no startDate: SNET, no invented date ──
{
  const res = eventToScheduleWork(REQ({ gatingTaskHint: 'nope' }), schedule([task('demo')]));
  ok('unresolved+no-startDate: still SNET', res.tasks[0].anchorType === 'start-no-earlier');
  ok('unresolved+no-startDate: no invented anchorDate', res.tasks[0].anchorDate === undefined);
  ok('unresolved+no-startDate: unresolved=true', res.unresolved === true);
}

// ── hint resolution works (title substring, case-insensitive) ──
{
  const gating = task('t-fr', { title: 'Rough Framing', startDay: 15 });
  const res = eventToScheduleWork(REQ({ gatingTaskHint: 'framing' }), schedule([gating]));
  ok('hint: resolves by title substring', res.unresolved === false && res.tasks.length === 2);
}

console.log(`\n${pass} passed, ${fail} failed`);
if (fail > 0) process.exit(1);
