// validate-protections.ts — the text protections (lane PROTECT-TEXT, 2026-10-09).
//
// WHY THIS EXISTS
//
// A plaintiff's-lawyer read of this codebase (design-previews/legal/
// LIABILITY-MAP.md and PROTECTIONS-BUILD-LIST.md) found sentences that put
// MAGE ID in a seat it must not sit in: the author of a contractor's document
// ("generated by MAGE ID"), a lawyer ("legally binding ... under the federal
// E-SIGN Act"), a licensing board ("Verified Pros"), a debt collector ("Final
// notice ... to avoid further action"), a lender (a monthly payment and an APR
// the contractor typed) and a guarantor ("the more accurate your bids").
// The lane rewrote each one to what the code really does. This guard keeps
// them from growing back, and fails the build when:
//
//   P1  a document builder, an email layout or a no-account page does not carry
//       the Notice To Recipients from utils/recipientNotice.ts, or a NEW
//       document builder appears without it;
//   P2  "generated by MAGE ID" (or "Built with" on a printed document) returns;
//   P3  the agreement sentence is missing from, or sits below the buttons on,
//       a screen that can create an account;
//   P4  a banned promise or legal conclusion is in a string a user reads, in
//       English or Spanish, in the app or on the in-scope pages;
//   P5  "Verified" (or "Vetted") labels a fact nobody checked;
//   P6  a payment reminder threatens;
//   P7  a figure with no source behind it is switched back on (financing
//       monthly amount and APR, the trial badge, the Discover waitlist cards),
//       or the renewal facts sink below a buy button;
//   P8  the template notice or the safety log notice leaves its screen.
//
// Every rule is a pure function over a map of file path to text, so the same
// rule is run again on PLANTED mutations of the real files. A rule that stays
// green on its mutation fails the build.
//
// Run via: bun run scripts/validate-protections.ts

import { readFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  RECIPIENT_NOTICE_PARTS, RECIPIENT_NOTICE_PARTS_ES, RECIPIENT_NOTICE_MARK, RECIPIENT_NOTICE_NO_COMPANY,
  recipientNoticeText, recipientNoticeHtml, withRecipientNotice, hasRecipientNotice,
} from '../utils/recipientNotice';
import { pdfShell, pdfFooter, PDF_DISCLAIMERS } from '../utils/pdfDesign';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
type Files = Record<string, string>;

let pass = 0;
let fail = 0;
function ok(name: string, cond: boolean, detail = ''): void {
  if (cond) { pass++; console.log(`  ✓ ${name}`); }
  else { fail++; console.log(`  ✗ ${name}${detail ? `\n      ${detail}` : ''}`); }
}

// ── Reading ─────────────────────────────────────────────────────────────────
function walk(dir: string, out: string[] = []): string[] {
  const abs = join(ROOT, dir);
  if (!existsSync(abs)) return out;
  for (const name of readdirSync(abs)) {
    if (name === 'node_modules' || name.startsWith('.') || name === '__tests__' || name === '__snapshots__') continue;
    const p = join(abs, name);
    if (statSync(p).isDirectory()) walk(relative(ROOT, p), out);
    else out.push(relative(ROOT, p));
  }
  return out;
}
const read = (p: string): string => readFileSync(join(ROOT, p), 'utf8');

/** Drop comments so a rule reads what ships, not what a comment quotes. */
export function stripComments(src: string): string {
  return src
    .replace(/\{\/\*[\s\S]*?\*\/\}/g, '')
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/^[ \t]*\/\/.*$/gm, '')
    .replace(/([;,{}()\]])[ \t]*\/\/ .*$/gm, '$1');
}

const CODE_DIRS = ['app', 'components', 'utils', 'constants', 'contexts', 'hooks'];
const NO_ACCOUNT_PAGES = [
  'marketing/portal/index.html',
  'marketing/sub-portal/index.html',
  'marketing/bid-invite/index.html',
  'marketing/lien-waiver/index.html',
  'marketing/architect/index.html',
  'marketing/paid/index.html',
];

function loadAll(): Files {
  const files: Files = {};
  for (const d of CODE_DIRS) {
    for (const f of walk(d)) if (/\.(ts|tsx)$/.test(f) && !/\.d\.ts$/.test(f)) files[f] = read(f);
  }
  for (const f of walk('marketing')) {
    if (f.startsWith('marketing/next/') || f.startsWith('marketing/app-store-screenshots/')) continue;
    if (/\.(html|js)$/.test(f)) files[f] = read(f);
  }
  for (const f of walk('supabase/functions')) if (/\.ts$/.test(f)) files[f] = read(f);
  for (const f of walk('i18n/catalog/es')) if (/\.ts$/.test(f)) files[f] = read(f);
  return files;
}

// ═══ P1. The Notice To Recipients ═══════════════════════════════════════════

/**
 * Files that build a whole HTML document but are NOT a contractor's document
 * to a third party, each with the reason. Anything else that contains "<html"
 * must put the notice on through pdfShell() or withRecipientNotice().
 */
export const NOT_A_RECIPIENT_DOCUMENT: Record<string, string> = {
  'app/+html.tsx': 'the web app shell, not a document',
  'components/desktop/webDocument.ts': 'the web app shell, not a document',
  'utils/pdfDesign.ts': 'defines pdfShell, which puts the notice on',
  'utils/recipientNotice.ts': 'defines the notice',
  'utils/emailLayout.ts': 'an email layout: carries the notice as a footer line (checked below)',
  'utils/learn/certificateDoc.ts': 'a MAGE ID tutorial certificate issued to the user himself, not a contractor document',
  'components/SendPortalLinkModal.tsx': 'a plain message the contractor typed, with a link: no document',
};
/** Another lane owns these. The Pay Period Record prints its own long reader notice on page one. */
const HELD_PREFIXES = ['utils/proofPack/'];

export function checkDocumentBuilders(files: Files): string[] {
  const bad: string[] = [];
  for (const [f, src] of Object.entries(files)) {
    if (!/^(app|components|utils)\//.test(f)) continue;
    if (HELD_PREFIXES.some((p) => f.startsWith(p))) continue;
    const code = stripComments(src);
    if (!/<html[\s>]/i.test(code)) continue;
    if (f in NOT_A_RECIPIENT_DOCUMENT) continue;
    // Every `<html` template in the file must be inside a withRecipientNotice( call,
    // or the file must build through pdfShell only.
    const htmlStarts = [...code.matchAll(/`\s*(?:<!DOCTYPE html>|<!doctype html>)?\s*<html[\s>]/gi)].length;
    const wrapped = [...code.matchAll(/withRecipientNotice\(\s*`\s*(?:<!DOCTYPE html>|<!doctype html>)?\s*<html[\s>]/gi)].length;
    // A constant placeholder page (a "loading" window) is not a document.
    const placeholders = [...code.matchAll(/_PLACEHOLDER_HTML = `\s*<!DOCTYPE html>\s*<html[\s>]/gi)].length;
    if (htmlStarts - placeholders > wrapped) {
      bad.push(`${f}: ${htmlStarts - placeholders} HTML document(s), ${wrapped} wrapped in withRecipientNotice(`);
    }
  }
  return bad;
}

/** Files that print through pdfShell must not also hand-roll a footer brand strip. */
export function checkNoGeneratedBy(files: Files): string[] {
  const bad: string[] = [];
  for (const [f, src] of Object.entries(files)) {
    if (!/^(app|components|utils|constants|supabase\/functions)\//.test(f)) continue;
    if (HELD_PREFIXES.some((p) => f.startsWith(p))) continue;
    const code = stripComments(src);
    if (/generated (?:by|with|from) MAGE ID\b/i.test(code)) bad.push(`${f}: "generated by MAGE ID"`);
    const isDocBuilder = /pdfShell\(|withRecipientNotice\(/.test(code);
    if (isDocBuilder && /Built with\b/.test(code)) bad.push(`${f}: "Built with" on a printed document`);
    if (isDocBuilder && /(?:Powered by|Sent with|from) MAGE ID\b/.test(code)) bad.push(`${f}: a MAGE ID authorship line on a printed document`);
  }
  for (const page of NO_ACCOUNT_PAGES) {
    const code = stripComments(files[page] ?? '');
    if (/generated by MAGE ID|produced for the signer by MAGE ID/i.test(code)) bad.push(`${page}: "generated by MAGE ID"`);
  }
  return bad;
}

const PAGE_LINE_1 = `${RECIPIENT_NOTICE_PARTS.before}<span data-notice-company>your contractor</span>${RECIPIENT_NOTICE_PARTS.after} ${RECIPIENT_NOTICE_PARTS.second}`;
const PAGE_LINE_2 = 'This page is run by MAGE ID for <span data-notice-company>your contractor</span>.';

export function checkPages(files: Files): string[] {
  const bad: string[] = [];
  for (const page of NO_ACCOUNT_PAGES) {
    const src = files[page];
    if (!src) { bad.push(`${page}: missing`); continue; }
    const body = src.search(/^<body>$/m);
    const notice = src.indexOf(`<aside class="mg-notice" ${RECIPIENT_NOTICE_MARK}="1"`);
    if (notice < 0) { bad.push(`${page}: no notice block`); continue; }
    const block = src.slice(notice, src.indexOf('</aside>', notice));
    if (!block.includes(PAGE_LINE_1)) bad.push(`${page}: the notice wording is not the shared wording`);
    if (!block.includes(PAGE_LINE_2)) bad.push(`${page}: no line saying who runs the page`);
    if (!/href="https:\/\/mageid\.app\/terms"[^>]*>Terms of Service<\/a>/.test(block)) bad.push(`${page}: no Terms link`);
    if (!/href="https:\/\/mageid\.app\/privacy"[^>]*>Privacy Policy<\/a>/.test(block)) bad.push(`${page}: no Privacy Policy link`);
    // Near the top: nothing but the skip link sits between <body> and the notice.
    const between = stripComments(src.slice(src.indexOf('>', body) + 1, notice)).trim();
    if (!/^<a class="mg-skip" href="#[a-z-]+">Skip to Main Content<\/a>$/.test(between)) bad.push(`${page}: the notice is not the first thing in the page (found: ${between.slice(0, 60)})`);
    const target = (between.match(/href="#([a-z-]+)"/) ?? [])[1];
    if (target && !new RegExp(`id="${target}"`).test(src)) bad.push(`${page}: the skip link points at #${target}, which is not on the page`);
    if (!/<script src="\/protect-notice\.js\?v=[0-9-]+"><\/script>/.test(src)) bad.push(`${page}: protect-notice.js is not loaded`);
    if (!/<html lang="[a-z]{2}/.test(src)) bad.push(`${page}: no lang on <html>`);
    // Readable: body size and ink, never small grey.
    if (!/font-size:14px/.test(block) || !/color:#0B0D10/.test(block)) bad.push(`${page}: the notice is not body size in ink`);
  }
  const js = files['marketing/protect-notice.js'] ?? '';
  if (!/data-notice-company/.test(js) || !/focus-visible/.test(js) || !/aria-label/.test(js)) bad.push('marketing/protect-notice.js: missing the company fill, the focus ring or the field naming');
  if (new RegExp(RECIPIENT_NOTICE_PARTS.second.slice(0, 30)).test(stripComments(js))) bad.push('marketing/protect-notice.js: the wording lives in the pages, not in the script');
  return bad;
}

export function checkEmailLayouts(files: Files): string[] {
  const bad: string[] = [];
  const client = stripComments(files['utils/emailLayout.ts'] ?? '');
  if (!/recipientNoticeText\(opts\.sender\.name\)/.test(client) || !/\$\{RECIPIENT_NOTICE_MARK\}="1"/.test(client)) bad.push('utils/emailLayout.ts: the footer does not print the notice for a company sender');
  const server = files['supabase/functions/_shared/email.ts'] ?? '';
  const m = server.match(/return `(Prepared by \$\{who\}[^`]*)`;/);
  if (!m) bad.push('supabase/functions/_shared/email.ts: recipientNoticeText is gone');
  else if (m[1].replace('${who}', 'Acme Build') !== recipientNoticeText('Acme Build')) bad.push('supabase/functions/_shared/email.ts: the server wording differs from utils/recipientNotice.ts');
  if (!/data-recipient-notice="1"[^`]*\$\{escapeHtml\(recipientNoticeText\(opts\.preparedBy\)\)\}/.test(server)) bad.push('supabase/functions/_shared/email.ts: the footer does not print the notice');
  const dunning = stripComments(files['supabase/functions/invoice-dunning/index.ts'] ?? '');
  if (!/preparedBy: opts\.companyName/.test(dunning)) bad.push('invoice-dunning: the reminder does not pass preparedBy');
  return bad;
}

// ═══ P3. The agreement sentence ═════════════════════════════════════════════

/** screen → the notice's testID and the buttons it must sit above. */
export const AGREEMENT_SCREENS: Record<string, { notice: string; above: string[] }> = {
  'app/login.tsx': { notice: 'login-agreement', above: ['testID="login-apple"', 'testID="login-google"', 'testID="login-magic-link"', 'testID="login-email"'] },
  'app/signup.tsx': { notice: 'signup-agreement', above: ['testID="signup-apple-top"', 'testID="signup-google-top"', 'testID="signup-submit"'] },
  'app/accept-invite.tsx': { notice: 'accept-invite-agreement', above: ['Sign In to Accept'] },
  'app/claim-crew.tsx': { notice: 'claim-crew-agreement', above: ['testID="claim-send-fresh"', 'testID="claim-sign-in"'] },
};

export function checkAgreement(files: Files): string[] {
  const bad: string[] = [];
  for (const [f, spec] of Object.entries(AGREEMENT_SCREENS)) {
    const code = stripComments(files[f] ?? '');
    const at = code.indexOf(`<AgreementNotice testID="${spec.notice}"`);
    if (at < 0) { bad.push(`${f}: no agreement sentence`); continue; }
    for (const b of spec.above) {
      const bi = code.indexOf(b);
      if (bi < 0) bad.push(`${f}: cannot find ${b}`);
      else if (bi < at) bad.push(`${f}: the agreement sentence is BELOW ${b}`);
    }
  }
  // Any screen that can create an account carries it: a new one cannot skip it.
  for (const [f, src] of Object.entries(files)) {
    if (!/^(app|components)\/.*\.tsx$/.test(f)) continue;
    const code = stripComments(src);
    if (/\b(?:signInWithApple|signInWithGoogle|sendMagicLink)\(/.test(code) && !/<AgreementNotice /.test(code)) {
      bad.push(`${f}: calls an account-creating sign-in and shows no agreement sentence`);
    }
  }
  const comp = stripComments(files['components/ProtectNotices.tsx'] ?? '');
  if (!/'By continuing you agree to our'/.test(comp) || !/'Terms of Service'/.test(comp) || !/'Privacy Policy'/.test(comp)) bad.push('components/ProtectNotices.tsx: the agreement wording changed');
  if (!/TERMS_URL = 'https:\/\/mageid\.app\/terms'/.test(comp) || !/PRIVACY_URL = 'https:\/\/mageid\.app\/privacy'/.test(comp)) bad.push('components/ProtectNotices.tsx: the links changed');
  if (!/Linking\.openURL\(TERMS_URL\)/.test(comp) || !/Linking\.openURL\(PRIVACY_URL\)/.test(comp)) bad.push('components/ProtectNotices.tsx: the links do not open');
  if (!/fontSize: Type\.footnote\.fontSize/.test(comp) || !/color: colors\.text,/.test(comp)) bad.push('components/ProtectNotices.tsx: the notices are not body size in the text colour');
  if (/Checkbox|Switch|record_my_acceptance|supabase/.test(comp)) bad.push('components/ProtectNotices.tsx: this lane is text only: no checkbox, no recording');
  return bad;
}

// ═══ P4 / P5. Banned phrases ════════════════════════════════════════════════

interface Ban { re: RegExp; why: string }
export const BANNED: Ban[] = [
  // Legal conclusions in MAGE ID's voice.
  { re: /legally binding/i, why: 'legal conclusion' },
  { re: /E-?SIGN Act|Uniform Electronic Transactions Act|\bUETA\b/, why: 'cites a statute to a signer' },
  { re: /make (?:it|this) binding|Make Binding|is your binding agreement|contract is binding|Binding agreement on file|binding amendment/i, why: 'legal conclusion' },
  { re: /legalmente vinculante|acuerdo vinculante|hacerlo vinculante|hacer vinculante|contrato es vinculante/i, why: 'legal conclusion (Spanish)' },
  { re: /juridiquement contraignant|rendre exécutoire|contrat exécutoire|torná-lo vinculante|tornar vinculante|法律约束力|có giá trị pháp lý/i, why: 'legal conclusion (portal language pack)' },
  { re: /byte-level change detectable|court[- ]ready|tamper[- ]proof|admissible in court|holds up in court/i, why: 'legal conclusion' },
  // Promises.
  { re: /more accurate (?:your )?bids|the more accurate your/i, why: 'accuracy promise' },
  { re: /makes the next estimate more accurate/i, why: 'accuracy promise' },
  { re: /win more work|wins more bids|respond first win|lifts win-rates|priced to win|price that wins/i, why: 'win promise' },
  { re: /makes you the most money/i, why: 'money promise' },
  { re: /gets sharper|makes them sharper|sharper numbers|recommendation sharper|Sharpens Your Next/i, why: 'accuracy promise' },
  { re: /within 48 hours of a nudge/i, why: 'unsourced payment claim' },
  { re: /safe to let ride/i, why: 'the app judging an invoice safe' },
  { re: /Predict When This (?:Invoice Will Be|Gets) Paid|will actually clear/i, why: 'a prediction stated as fact' },
  { re: /AI confidence \{|AI confidence \$\{/i, why: 'a model self-score presented as confidence' },
  { re: /Get Paid Faster|No hidden fees|Cancel anytime in Settings/i, why: 'promise' },
  { re: /Fewer bids, higher quality/i, why: 'quality promise about contractors nobody checked' },
  // Safety.
  { re: /classifies OSHA-recordable/i, why: 'the app making a regulatory determination' },
  { re: /No hazards detected/i, why: 'an all-clear' },
  // Verified / vetted for a self-declared fact.
  { re: /Verified Pros|verified pros|Get Verified|Verified by MAGE|ID Verified|verified certs|verified roster|verified pitch|GPS-verified|Location-verified/, why: '"Verified" for a fact nobody checked' },
  { re: /\bvetted (?:sub|pro|contractor|trade|directory|network)|\bVetted\b/, why: '"vetted": nobody vets' },
  { re: /ID verificada|Identificación no verificada|lista verificada/i, why: '"Verified" for a fact nobody checked (Spanish)' },
  // Money messages.
  { re: /Final [Nn]otice|to avoid further action/, why: 'threat in a payment reminder' },
  { re: /Prefer to pay monthly|See if you prequalify/i, why: 'credit prompt to a consumer' },
  // Discover cards for products that do not exist are behind a false flag; their
  // text is allowed to sit there. The one internal note is not.
  { re: /Lower priority per the strategy doc/i, why: 'an internal planning note shown to users' },
];

/**
 * Text a rule above matches that is NOT MAGE ID speaking: a contract or
 * statutory form clause the contractor's client signs (this lane does not
 * touch clause text; the list goes to counsel), or code that is not a string a
 * user reads. Each entry: file, the exact fragment, the reason.
 */
export const BAN_EXEMPT: { file: string; has: string; why: string }[] = [
  { file: 'utils/contractEngine.ts', has: 'accept this proposal as the binding agreement', why: 'template clause on the proposal the client signs: clause text is counsel\'s to change' },
  // CONSENT TEXT, NOT CHANGED. The sentence a homeowner agrees to when he
  // counter-signs a contract in the portal. The signing RPC stores no copy of
  // it and no version, so changing it would leave no way to tell which
  // sentence a given signer saw. It stays word for word until counsel supplies
  // the replacement AND the signature record carries a consent version
  // (scripts/moments-checks/portal.ts pins its hash, rule P8).
  { file: 'marketing/portal/index.html', has: 'you accept the agreement as legally binding', why: 'unversioned contract consent text: counsel and a versioned record first' },
  { file: 'marketing/portal/index.html', has: 'acepta el acuerdo como legalmente vinculante', why: 'same, Spanish' },
  { file: 'marketing/portal/index.html', has: 'aceita o acordo como legalmente vinculante', why: 'same, Portuguese' },
  { file: 'marketing/portal/index.html', has: '具有法律约束力', why: 'same, Chinese' },
  { file: 'marketing/portal/index.html', has: 'có giá trị pháp lý', why: 'same, Vietnamese' },
  { file: 'marketing/portal/index.html', has: 'juridiquement contraignant', why: 'same, French' },
  { file: 'utils/portalLanguages.ts', has: 'contractFinePrint:', why: 'the same consent sentence in the published language packs' },
  { file: 'app/dev-seeder.tsx', has: 'verified', why: 'dev seed data' },
  { file: 'utils/instantBid.ts', has: 'APR', why: 'dead while FINANCING_FIGURES_ENABLED is false (pinned in P7)' },
];

/** In-scope surfaces for the phrase scan. */
function inPhraseScope(f: string): boolean {
  if (/^(app|components|utils|constants|contexts|hooks)\//.test(f)) return !f.startsWith('utils/proofPack/') && !/^app\/dev-/.test(f);
  if (/^i18n\/catalog\/es\//.test(f)) return true;
  if (f === 'supabase/functions/invoice-dunning/index.ts' || f === 'supabase/functions/_shared/email.ts') return true;
  if (/^marketing\/.*\.html$/.test(f)) return !/^marketing\/(terms|privacy|do-not-sell)\.html$/.test(f);
  return false;
}

export function checkBanned(files: Files): string[] {
  const bad: string[] = [];
  for (const [f, src] of Object.entries(files)) {
    if (!inPhraseScope(f)) continue;
    const code = stripComments(src);
    const lines = code.split('\n');
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      for (const b of BANNED) {
        const m = line.match(b.re);
        if (!m) continue;
        if (BAN_EXEMPT.some((e) => e.file === f && line.includes(e.has))) continue;
        // A testID, a route, a key or an identifier is not a sentence.
        const near = line.slice(Math.max(0, (m.index ?? 0) - 40), (m.index ?? 0) + m[0].length + 8);
        if (/testID=|eventKey=|\/get-verified|id: '|key: '|\.verified|Verified[A-Z(]|verified[A-Z_]|get-verified/.test(near) && !/[>'"`] ?[A-Z][a-z]+ [a-z]/.test(m[0])) {
          if (/^(?:Get Verified|ID Verified|Verified Pros|verified pros|Verified by MAGE)$/.test(m[0]) === false) continue;
        }
        bad.push(`${f}:${i + 1}: ${b.why}: "${m[0]}"`);
      }
    }
  }
  return bad;
}

/**
 * P5, the other half: every place the bare word "Verified" still reaches a
 * screen, named, with what was checked and by whom. A new one fails until it
 * is added here with a reason, which is the moment someone has to say who
 * checked what.
 */
export const VERIFIED_ALLOWED: Record<string, string> = {
  'app/(tabs)/subs/index.tsx': 'the GC records that HE checked a sub\'s licence or COI, with the date ("Verified 12d ago", "Mark Verified")',
  'app/post-rfp.tsx': 'the homeowner\'s own address check by the geocoder ("Address Verified" state), not a contractor fact',
  'app/rfp-detail.tsx': 'the address geocoder result, worded as found / not found',
  'components/TakeoffFieldVerifyButton.tsx': 'the contractor\'s own field measurement of a takeoff row',
};

export function checkVerifiedWord(files: Files): string[] {
  const bad: string[] = [];
  for (const [f, src] of Object.entries(files)) {
    if (!/^(app|components)\/.*\.tsx$/.test(f) || /^app\/dev-/.test(f)) continue;
    const code = stripComments(src);
    // "Verified" as a word a user reads: inside JSX text or a quoted label.
    const hits = [...code.matchAll(/(?:>|['"`])\s*(?:[A-Za-z ]* )?Verified\b(?![A-Za-z(_])/g)];
    if (hits.length && !(f in VERIFIED_ALLOWED)) bad.push(`${f}: "${hits[0][0].trim().slice(0, 40)}" (${hits.length} use(s)) is not on the list of checked facts`);
  }
  return bad;
}

// ═══ P6. Payment reminders ══════════════════════════════════════════════════

const THREAT = /final notice|further action|legal action|collections?\b|collection agency|last warning|last chance|consequences|or else|immediately|will be reported|credit (?:bureau|report)|attorney|lawsuit|court|lien will|suspend/i;

export function checkDunning(files: Files): string[] {
  const bad: string[] = [];
  const src = stripComments(files['supabase/functions/invoice-dunning/index.ts'] ?? '');
  const a = src.indexOf('function buildDunningHtml(');
  const b = src.indexOf('async function paymentPendingSince');
  if (a < 0 || b < 0) return ['invoice-dunning: cannot find buildDunningHtml'];
  const builder = src.slice(a, b);
  const strings = [...builder.matchAll(/`([^`]*)`|'([^'\n]*)'/g)].map((m) => m[1] ?? m[2] ?? '');
  for (const s of strings) if (THREAT.test(s)) bad.push(`invoice-dunning email: "${s.slice(0, 80)}"`);
  // The subject is built a second time where the email is sent.
  for (const m of src.matchAll(/`((?:Third reminder|Second reminder|Reminder|Final notice|Second notice)[^`]*)`/g)) {
    if (THREAT.test(m[1])) bad.push(`invoice-dunning subject: "${m[1].slice(0, 60)}"`);
  }
  if (!/Third reminder: invoice #/.test(src) || !/Second reminder: invoice #/.test(src)) bad.push('invoice-dunning: the stage 2 and 3 subjects are not plain reminders');
  // What a reminder must carry: the amount, the due date, how to pay, how to dispute.
  if (!/Amount due/.test(builder) || !/Due date/.test(builder)) bad.push('invoice-dunning: the reminder does not show the amount and the due date');
  if (!/emailButton\(`Pay \$\{amountFormatted\} now`, opts\.payUrl\)/.test(builder)) bad.push('invoice-dunning: the reminder does not show how to pay');
  if (!/you think this invoice is wrong, reply to this email to reach \$\{escapeHtml\(opts\.companyName\)\}/.test(builder)) bad.push('invoice-dunning: the reminder does not say how to dispute it');
  const labels = stripComments(files['utils/billingFlowCore.ts'] ?? '');
  if (/'Final Notice'|'Second Notice'/.test(labels)) bad.push('utils/billingFlowCore.ts: the stage labels the contractor reads still say Notice');
  return bad;
}

// ═══ P7. Figures and badges with nothing behind them ════════════════════════

export function checkFlagsAndPaywall(files: Files): string[] {
  const bad: string[] = [];
  const need = (f: string, re: RegExp, what: string) => { if (!re.test(stripComments(files[f] ?? ''))) bad.push(`${f}: ${what}`); };
  need('utils/financing.ts', /export const FINANCING_FIGURES_ENABLED: boolean = false;/, 'financing figures are on (a monthly amount and an APR nobody licensed supplied)');
  need('utils/financing.ts', /if \(!FINANCING_FIGURES_ENABLED\) return null;/, 'illustrativeMonthly no longer obeys the flag');
  need('utils/signupIntent.ts', /export const SIGNUP_TRIAL_BADGE_ENABLED: boolean = false;/, 'the URL-driven trial badge is on');
  need('constants/featureFlags.ts', /export const DISCOVER_WAITLIST_CARDS_ENABLED: boolean = false;/, 'the Discover waitlist cards are on');
  need('app/(tabs)/discover/index.tsx', /\{DISCOVER_WAITLIST_CARDS_ENABLED \? \(/, 'the waitlist cards are not behind their flag');
  const fin = stripComments(files['utils/financing.ts'] ?? '');
  const block = fin.slice(fin.indexOf('export function financingEmailBlockHtml'));
  if (/\/mo\b|APR|illustrativeMonthly\(/.test(block)) bad.push('utils/financing.ts: the invoice email block prints a monthly figure or a rate');
  for (const f of ['app/paywall.tsx', 'app/onboarding-paywall.tsx']) {
    need(f, /if \(SIGNUP_TRIAL_BADGE_ENABLED(?: && intent\.trialDays > 0)?\) (?:\{\s*)?setIntentTrialDays\(intent\.trialDays\)/, 'the trial badge is set without its flag');
  }
  const above = (f: string, facts: string, button: string) => {
    const code = stripComments(files[f] ?? '');
    const a = code.indexOf(facts);
    const b = code.indexOf(button);
    if (a < 0) bad.push(`${f}: the renewal facts are gone`);
    else if (b < 0) bad.push(`${f}: cannot find ${button}`);
    else if (b < a) bad.push(`${f}: the renewal facts are BELOW the buy button`);
  };
  above('app/paywall.tsx', 'testID="paywall-renewal-facts"', 'testID="buy-pro"');
  above('app/onboarding-paywall.tsx', 'testID="onboarding-paywall-renewal-facts"', 'testID="onboarding-paywall-cta"');
  above('components/Paywall.tsx', 'testID="paywall-modal-renewal-facts"', 'testID="paywall-upgrade-btn"');
  const pw = files['components/Paywall.tsx'] ?? '';
  const m = pw.match(/export function renewalFactsText\([\s\S]*?\n\}/);
  if (!m) bad.push('components/Paywall.tsx: renewalFactsText is gone');
  else {
    for (const word of ['price and period shown', 'renews automatically', 'until you cancel', 'To cancel,', 'free trial becomes a paid plan']) {
      if (!m[0].includes(word)) bad.push(`components/Paywall.tsx: renewalFactsText no longer says "${word}"`);
    }
  }
  return bad;
}

// ═══ P8. The template notice and the safety log notice ══════════════════════

export const TEMPLATE_SCREENS: Record<string, string> = {
  'app/contract.tsx': 'contract-template-notice',
  'app/smart-proposal.tsx': 'proposal-template-notice',
  'app/lien-waivers.tsx': 'lien-waiver-template-notice',
  'app/closeout-binder.tsx': 'closeout-forms-template-notice',
  'app/buyout-package.tsx': 'subcontract-template-notice',
};
export const SAFETY_NOTICES: Record<string, string[]> = {
  'app/safety-incidents.tsx': ['incident-record-notice', 'incident-recordability-notice', 'safety.protect.recordNotice', 'safety.protect.verdictNotice'],
  'app/safety-hazards.tsx': ['hazard-record-notice', 'safety.protect.recordNotice', 'That does not mean the site is safe'],
  'app/safety-jha.tsx': ['jha-draft-notice', 'safety.protect.aiDraftNotice'],
};

export function checkScreenNotices(files: Files): string[] {
  const bad: string[] = [];
  for (const [f, id] of Object.entries(TEMPLATE_SCREENS)) {
    if (!new RegExp(`<TemplateNotice testID="${id}"`).test(stripComments(files[f] ?? ''))) bad.push(`${f}: the template notice is gone`);
  }
  // Told to the contractor on his screen; never printed on the document his client signs.
  for (const [f, src] of Object.entries(files)) {
    if (!/^utils\//.test(f)) continue;
    if (/starting template, not legal advice/.test(stripComments(src))) bad.push(`${f}: the template notice is printed by a document builder`);
  }
  const comp = stripComments(files['components/ProtectNotices.tsx'] ?? '');
  if (!/This is a starting template, not legal advice\..*Have your own attorney review it before you use it\./.test(comp)) bad.push('components/ProtectNotices.tsx: the template notice wording changed');
  for (const [f, needles] of Object.entries(SAFETY_NOTICES)) {
    const code = stripComments(files[f] ?? '');
    for (const n of needles) if (!code.includes(n)) bad.push(`${f}: missing ${n}`);
  }
  const inc = stripComments(files['app/safety-incidents.tsx'] ?? '');
  if (!/This log is your own record\. MAGE ID does not review it\. Reporting an incident or a hazard to OSHA or any other authority is your responsibility\./.test(inc)) bad.push('app/safety-incidents.tsx: the log notice wording changed');
  // No tick beside "Not recordable": absence of a flag is never drawn as an all-clear.
  if (/liveVerdict\.recordable[\s\S]{0,160}: <Check /.test(inc)) bad.push('app/safety-incidents.tsx: a check mark is drawn beside "Not recordable"');
  return bad;
}

// ═══ Run ════════════════════════════════════════════════════════════════════

const FILES = loadAll();
const RULES: Record<string, (f: Files) => string[]> = {
  'P1a every document builder puts the notice on': checkDocumentBuilders,
  'P1b the six no-account pages carry the notice, the links and who runs the page': checkPages,
  'P1c the email layouts carry the notice': checkEmailLayouts,
  'P2 no "generated by MAGE ID" framing': checkNoGeneratedBy,
  'P3 the agreement sentence sits above the buttons on every account-creating screen': checkAgreement,
  'P4 no banned promise or legal conclusion in a string a user reads': checkBanned,
  'P5 "Verified" only where someone checked': checkVerifiedWord,
  'P6 payment reminders do not threaten': checkDunning,
  'P7 no figure or badge with nothing behind it, and renewal facts above the buy buttons': checkFlagsAndPaywall,
  'P8 the template notice and the safety log notice are on their screens': checkScreenNotices,
};

console.log('\nvalidate-protections\n');
console.log('The helper');
{
  const t = recipientNoticeText('Smith Builders');
  ok('the wording is the one wording',
    t === 'Prepared by Smith Builders using MAGE ID software. MAGE ID did not prepare, review or check this document and makes no statement to the reader about its contents.', t);
  ok('no company name: "the sender", never MAGE ID as the author',
    recipientNoticeText('') === recipientNoticeText(null) && recipientNoticeText('MAGE ID').startsWith(`Prepared by ${RECIPIENT_NOTICE_NO_COMPANY} `) && recipientNoticeText(' mage id ').includes('the sender'));
  ok('Spanish draft exists and names the company', recipientNoticeText('Smith Builders', 'es').startsWith(`${RECIPIENT_NOTICE_PARTS_ES.before}Smith Builders`) && recipientNoticeText('', 'es').includes('el remitente'));
  const html = recipientNoticeHtml('A & B <Co>');
  ok('the block escapes the company name', html.includes('A &amp; B &lt;Co&gt;') && !html.includes('<Co>'));
  ok('the block is body size, ink, not italic and not grey', /font-size:12px/.test(html) && /color:#0B0D10/.test(html) && /font-style:normal/.test(html) && !/italic|#9|#8|#a|#6b/i.test(html.replace('#0B0D10', '').replace('#0B0D10', '')));
  const doc = '<!DOCTYPE html><html><head><title>x</title></head><body><p>Form body</p></body></html>';
  const out = withRecipientNotice(doc, 'Smith "Q" Builders');
  ok('withRecipientNotice puts the block last in the body, after the form body', out.indexOf('Form body') < out.indexOf(`${RECIPIENT_NOTICE_MARK}="1"`) && out.indexOf(`${RECIPIENT_NOTICE_MARK}="1"`) < out.indexOf('</body>'));
  ok('…and a running footer for every printed page, CSS-escaped', /@page \{ @bottom-center \{ content: "Prepared by Smith \\22 Q\\22  Builders using MAGE ID software\./.test(out) && out.indexOf('@page') < out.indexOf('</head>'));
  ok('…once only: a wrapped document is returned unchanged', withRecipientNotice(out, 'Other') === out && hasRecipientNotice(out));
  ok('…and a fragment with no <body> still gets it', hasRecipientNotice(withRecipientNotice('<div>x</div>', 'Co')));
  ok('…pageFooter:false leaves the running footer to the document', !/@page/.test(withRecipientNotice(doc, 'Co', 'en', { pageFooter: false })));
  const shell = pdfShell({ bodyHtml: '<p>b</p>', branding: { companyName: 'Smith Builders' } as never, title: 't' });
  ok('pdfShell puts the notice on every PDF', hasRecipientNotice(shell) && shell.includes(recipientNoticeText('Smith Builders')));
  const foot = pdfFooter({ companyName: 'Smith Builders' } as never, 'Invoice #4', PDF_DISCLAIMERS.invoice);
  ok('pdfFooter no longer draws a brand strip or a 9.5px grey italic line', !/Built with|mageid\.app|italic|9\.5px/.test(foot) && foot.includes('Invoice #4'));
  ok('no disclaimer says "generated by MAGE ID"', !Object.values(PDF_DISCLAIMERS).some((d) => /generated by MAGE ID|binding amendment/i.test(d)));
}

console.log('\nThe shipped tree');
for (const [name, rule] of Object.entries(RULES)) {
  const bad = rule(FILES);
  ok(name, bad.length === 0, bad.slice(0, 12).join('\n      ') + (bad.length > 12 ? `\n      … and ${bad.length - 12} more` : ''));
}

// ── Planted mutations: each must turn its rule red ──────────────────────────
console.log('\nPlanted mutations');
interface Mutation { what: string; rule: keyof typeof RULES; edit: (f: Files) => void }
const sub = (f: Files, path: string, from: string | RegExp, to: string): void => {
  const before = f[path] ?? '';
  const after = typeof from === 'string' ? before.split(from).join(to) : before.replace(from, to);
  if (after === before) throw new Error(`mutation did not apply: ${path}`);
  f[path] = after;
};
const MUTATIONS: Mutation[] = [
  { what: 'a builder returns its HTML without the notice (the OSHA log)', rule: 'P1a every document builder puts the notice on', edit: (f) => sub(f, 'utils/safety/oshaLog.ts', 'return withRecipientNotice(`<!doctype html>', 'return (`<!doctype html>') },
  { what: 'the pay application loses the notice', rule: 'P1a every document builder puts the notice on', edit: (f) => sub(f, 'utils/aiaBilling.ts', 'return withRecipientNotice(`<!DOCTYPE html>', 'return (`<!DOCTYPE html>') },
  { what: 'a NEW document type is added without it', rule: 'P1a every document builder puts the notice on', edit: (f) => { f['utils/newWarrantyLetter.ts'] = 'export const build = () => `<!DOCTYPE html><html><body>Warranty</body></html>`;'; } },
  { what: 'a page changes the wording', rule: 'P1b the six no-account pages carry the notice, the links and who runs the page', edit: (f) => sub(f, 'marketing/sub-portal/index.html', 'MAGE ID did not prepare, review or check this document', 'MAGE ID reviewed this document') },
  { what: 'a page drops the Terms link', rule: 'P1b the six no-account pages carry the notice, the links and who runs the page', edit: (f) => sub(f, 'marketing/lien-waiver/index.html', '>Terms of Service</a>', '>Terms</a>') },
  { what: 'a page moves the notice below its content', rule: 'P1b the six no-account pages carry the notice, the links and who runs the page', edit: (f) => sub(f, 'marketing/paid/index.html', /<body>\n/, '<body>\n<h1>Paid</h1>\n') },
  { what: 'a page loses the notice', rule: 'P1b the six no-account pages carry the notice, the links and who runs the page', edit: (f) => sub(f, 'marketing/bid-invite/index.html', '<aside class="mg-notice"', '<aside class="mg-gone"') },
  { what: 'the server email wording drifts', rule: 'P1c the email layouts carry the notice', edit: (f) => sub(f, 'supabase/functions/_shared/email.ts', 'makes no statement to the reader about its contents.`;', 'makes no promises.`;') },
  { what: 'the client email footer drops the notice', rule: 'P1c the email layouts carry the notice', edit: (f) => sub(f, 'utils/emailLayout.ts', 'recipientNoticeText(opts.sender.name)', "''") },
  { what: '"Generated by MAGE ID" returns to a schedule export', rule: 'P2 no "generated by MAGE ID" framing', edit: (f) => sub(f, 'utils/exportSchedulePdf.ts', '<footer>Schedule printed', '<footer>Generated by MAGE ID ·') },
  { what: '"Built with MAGE ID" returns to the PDF footer', rule: 'P2 no "generated by MAGE ID" framing', edit: (f) => sub(f, 'utils/pdfDesign.ts', "if (!extra && !disclaimer) return '';", "if (!extra && !disclaimer) return 'Built with MAGE ID';") },
  { what: 'Log In loses the agreement sentence', rule: 'P3 the agreement sentence sits above the buttons on every account-creating screen', edit: (f) => sub(f, 'app/login.tsx', '<AgreementNotice testID="login-agreement"', '<Text testID="login-agreement-gone"') },
  { what: 'Sign Up moves it below the Apple button', rule: 'P3 the agreement sentence sits above the buttons on every account-creating screen', edit: (f) => { const s = f['app/signup.tsx']; const i = s.indexOf('<AgreementNotice testID="signup-agreement"'); const j = s.indexOf('/>', i) + 2; const tag = s.slice(i, j); f['app/signup.tsx'] = s.slice(0, i) + s.slice(j).replace('testID="signup-google-top"', `testID="signup-google-top"\n${tag}`); } },
  { what: 'a new screen signs people in with Google and no sentence', rule: 'P3 the agreement sentence sits above the buttons on every account-creating screen', edit: (f) => { f['app/quick-start.tsx'] = 'export default function Q() { const go = async () => { await signInWithGoogle(); }; return null; }'; } },
  { what: 'the sentence turns into a recording checkbox', rule: 'P3 the agreement sentence sits above the buttons on every account-creating screen', edit: (f) => sub(f, 'components/ProtectNotices.tsx', "import React from 'react';", "import React from 'react';\nimport { Switch } from 'react-native';") },
  { what: '"legally binding" returns to the portal', rule: 'P4 no banned promise or legal conclusion in a string a user reads', edit: (f) => sub(f, 'marketing/portal/index.html', "contractSignedDisclaimer: 'This is the agreement you signed. Keep a copy for your records.'", "contractSignedDisclaimer: 'Your signature is legally binding. Keep it for your records.'") },
  { what: 'the E-SIGN sentence returns to the waiver page', rule: 'P4 no banned promise or legal conclusion in a string a user reads', edit: (f) => sub(f, 'marketing/lien-waiver/index.html', 'I intend this to be my signature.', 'It is binding under the federal E-SIGN Act.') },
  { what: 'Spanish "legalmente vinculante" returns', rule: 'P4 no banned promise or legal conclusion in a string a user reads', edit: (f) => sub(f, 'utils/portalLanguages.ts', 'Revise el contrato y fírmelo.', 'Revise el contrato y fírmelo para hacerlo vinculante.') },
  { what: 'an accuracy promise returns to Post a Project', rule: 'P4 no banned promise or legal conclusion in a string a user reads', edit: (f) => sub(f, 'app/post-rfp.tsx', 'More detail helps contractors price your job.', 'The more details you add, the more accurate your bids.') },
  { what: '"Verified Pros" returns', rule: 'P4 no banned promise or legal conclusion in a string a user reads', edit: (f) => sub(f, 'app/post-rfp.tsx', 'Notify Only Contractors With a License on File', 'Notify Verified Pros Only') },
  { what: '"vetted sub directory" returns to pricing', rule: 'P4 no banned promise or legal conclusion in a string a user reads', edit: (f) => sub(f, 'marketing/pricing.html', '<li class="muted">Sub directory</li>', '<li class="muted">Vetted sub directory</li>') },
  { what: 'Spanish "ID verificada" returns', rule: 'P4 no banned promise or legal conclusion in a string a user reads', edit: (f) => sub(f, 'i18n/catalog/es/field/crew.ts', '"ID en archivo"', '"ID verificada"') },
  { what: 'a hazard scan says "No hazards detected"', rule: 'P4 no banned promise or legal conclusion in a string a user reads', edit: (f) => sub(f, 'app/safety-hazards.tsx', 'The AI did not pick out a hazard in that photo.', 'No hazards detected in that photo.') },
  { what: 'a new screen badges a contractor "Verified"', rule: 'P5 "Verified" only where someone checked', edit: (f) => { f['app/pro-card.tsx'] = 'export default function P() { return <Text>Verified</Text>; }'; } },
  { what: 'stage 3 is a "Final notice" again', rule: 'P6 payment reminders do not threaten', edit: (f) => sub(f, 'supabase/functions/invoice-dunning/index.ts', "opts.stage === 3 ? 'Third reminder' :", "opts.stage === 3 ? 'Final notice' :") },
  { what: 'the body threatens "further action"', rule: 'P6 payment reminders do not threaten', edit: (f) => sub(f, 'supabase/functions/invoice-dunning/index.ts', 'This is the third reminder about the invoice below.', 'Pay now to avoid further action.') },
  { what: 'the body mentions collections', rule: 'P6 payment reminders do not threaten', edit: (f) => sub(f, 'supabase/functions/invoice-dunning/index.ts', 'This is the second reminder about the invoice below.', 'This account may be sent to collections.') },
  { what: 'the dispute line is dropped', rule: 'P6 payment reminders do not threaten', edit: (f) => sub(f, 'supabase/functions/invoice-dunning/index.ts', 'you think this invoice is wrong, reply to this email to reach', 'reply to reach') },
  { what: 'financing figures are switched on', rule: 'P7 no figure or badge with nothing behind it, and renewal facts above the buy buttons', edit: (f) => sub(f, 'utils/financing.ts', 'FINANCING_FIGURES_ENABLED: boolean = false', 'FINANCING_FIGURES_ENABLED: boolean = true') },
  { what: 'the trial badge is switched on', rule: 'P7 no figure or badge with nothing behind it, and renewal facts above the buy buttons', edit: (f) => sub(f, 'utils/signupIntent.ts', 'SIGNUP_TRIAL_BADGE_ENABLED: boolean = false', 'SIGNUP_TRIAL_BADGE_ENABLED: boolean = true') },
  { what: 'the Discover waitlist cards are switched on', rule: 'P7 no figure or badge with nothing behind it, and renewal facts above the buy buttons', edit: (f) => sub(f, 'constants/featureFlags.ts', 'DISCOVER_WAITLIST_CARDS_ENABLED: boolean = false', 'DISCOVER_WAITLIST_CARDS_ENABLED: boolean = true') },
  { what: 'the renewal facts sink below the buy buttons', rule: 'P7 no figure or badge with nothing behind it, and renewal facts above the buy buttons', edit: (f) => { const s = f['app/paywall.tsx']; const i = s.indexOf('<Text style={styles.renewalFacts}'); const j = s.indexOf('</Text>', i) + 7; const tag = s.slice(i, j); f['app/paywall.tsx'] = s.slice(0, i) + s.slice(j).replace('<View style={styles.legalRow}>', `${tag}\n<View style={styles.legalRow}>`); } },
  { what: 'the renewal sentence stops saying it renews', rule: 'P7 no figure or badge with nothing behind it, and renewal facts above the buy buttons', edit: (f) => sub(f, 'components/Paywall.tsx', 'It renews automatically at that price until you cancel.', 'Cancel anytime.') },
  { what: 'the contract screen loses the template notice', rule: 'P8 the template notice and the safety log notice are on their screens', edit: (f) => sub(f, 'app/contract.tsx', '<TemplateNotice testID="contract-template-notice"', '<Text testID="x"') },
  { what: 'the template notice is printed on a document', rule: 'P8 the template notice and the safety log notice are on their screens', edit: (f) => sub(f, 'utils/contractEngine.ts', 'const DEFAULT_TERMS = `', 'const DEFAULT_TERMS = `This is a starting template, not legal advice.') },
  { what: 'the incident form loses the log notice', rule: 'P8 the template notice and the safety log notice are on their screens', edit: (f) => sub(f, 'app/safety-incidents.tsx', 'testID="incident-record-notice"', 'testID="gone"') },
  { what: 'a tick returns beside "Not recordable"', rule: 'P8 the template notice and the safety log notice are on their screens', edit: (f) => sub(f, 'app/safety-incidents.tsx', ': <Minus size={14}', ': <Check size={14}') },
];
for (const m of MUTATIONS) {
  const copy: Files = { ...FILES };
  let applied = true;
  try { m.edit(copy); } catch (e) { applied = false; ok(`mutation applies: ${m.what}`, false, (e as Error).message); }
  if (!applied) continue;
  const bad = RULES[m.rule](copy);
  ok(`red on: ${m.what}`, bad.length > 0);
}

console.log(`\n${fail === 0 ? '✓' : '✗'} validate-protections: ${pass} passed, ${fail} failed (${MUTATIONS.length} planted mutations)\n`);
process.exit(fail === 0 ? 0 : 1);
