// components/automation/AutoScheduleReviewSheet.tsx
//
// THE REVIEW SHEET — the confirm gate between the automation engine's DRAFT
// output and a real schedule mutation. Spec Component 5 + 6.
//
// "These N inspections will be added to your schedule; confirm." Draft tasks
// (isAutoGenerated, produced by eventToScheduleWork via roadmapToScheduleWork)
// are listed with their lead-time provenance chip. NOTHING commits until the
// contractor presses Confirm:
//
//   • onConfirm is the ONLY path that fires the caller's commit. Rendering the
//     sheet, toggling rows, dismissing — none of them commit. (Test asserts.)
//
//   • ZONING CONFIRM-GATE: when the project's zoning is a GUESS (not yet
//     confirmed), the whole auto-schedule flow is BLOCKED. The Confirm button
//     is disabled and a "Confirm zoning to enable" banner explains why —
//     because auto-scheduling grounded on an unconfirmed district would be
//     presenting a guess as truth. Confirming zoning (onConfirmZoning) unblocks
//     the flow. (Test asserts confirm is inert while blocked.)
//
// Tokens only (constants/colors + typography + designTokens). No hex literals,
// no inline fontSize. Pure presentational — all state/commit lives in the
// caller; this component decides only what is *renderable* and *pressable*.

import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ScrollView,
} from 'react-native';
import {
  CalendarClock,
  ShieldQuestion,
  ShieldCheck,
  Link2Off,
  Sparkles,
} from 'lucide-react-native';
import { Colors, type ThemeColors } from '@/constants/colors';
import { useThemedStyles } from '@/hooks/useThemedStyles';
import { useTheme } from '@/contexts/ThemeContext';
import { Type } from '@/constants/typography';
import { Tokens } from '@/constants/designTokens';
import type { LeadTimeSource, LeadTimeConfidence } from '@/utils/automation/leadTimeLibrary';
import type { ReviewLine } from '@/utils/automation/roadmapToScheduleWork';

/**
 * Zoning gate state, lifted from the project's structuredAddress by the caller.
 * When `status === 'guess'` (or absent) the whole flow is blocked until
 * confirmed — a guessed district must never silently drive auto-scheduling.
 */
export interface ZoningGate {
  district?: string;
  status: 'guess' | 'confirmed';
}

export interface AutoScheduleReviewSheetProps {
  /** The draft lines to review, one per roadmap inspection. */
  lines: ReviewLine[];
  /** Zoning provenance + confirmation state. Absent = treated as an
   *  unconfirmed guess (blocked), because no confirmation is the same risk as
   *  an unconfirmed guess. */
  zoning?: ZoningGate;
  /** Fired ONLY when the contractor presses Confirm while the flow is
   *  unblocked. The single commit path. */
  onConfirm: (lines: ReviewLine[]) => void;
  /** Dismiss without committing. */
  onCancel: () => void;
  /** Confirm the guessed zoning district (unblocks the flow). Surfaced only
   *  while the gate is blocking. */
  onConfirmZoning?: () => void;
}

const SOURCE_LABEL: Record<LeadTimeSource, string> = {
  default: 'Typical',
  jurisdiction: 'Jurisdiction',
  learned: 'Learned',
};

const CONFIDENCE_LABEL: Record<LeadTimeConfidence, string> = {
  low: 'low confidence',
  med: 'medium confidence',
  high: 'high confidence',
};

/** Provenance chip for a lead time — source + confidence, never a bare number.
 *  This is the "guess carries provenance" discipline made visible. */
function LeadTimeChip({
  line,
  styles,
}: {
  line: ReviewLine;
  styles: ReturnType<typeof makeStyles>;
}): React.JSX.Element {
  const { source, confidence, days } = line.leadTime;
  return (
    <View style={styles.chip} testID="lead-time-chip">
      <Text style={styles.chipText}>
        {`${days}d lead · ${SOURCE_LABEL[source]} · ${CONFIDENCE_LABEL[confidence]}`}
      </Text>
    </View>
  );
}

export function AutoScheduleReviewSheet(
  props: AutoScheduleReviewSheetProps,
): React.JSX.Element {
  const { lines, zoning, onConfirm, onCancel, onConfirmZoning } = props;
  const { colors } = useTheme();
  const styles = useThemedStyles(makeStyles);

  // BLOCKED when zoning is anything other than an explicit 'confirmed'. Absent
  // zoning is treated as a guess (fail-closed) — we never auto-schedule on an
  // unconfirmed district.
  const zoningBlocked = !zoning || zoning.status !== 'confirmed';

  const count = lines.length;
  const unresolvedCount = lines.filter((l) => l.unresolved).length;

  const handleConfirm = () => {
    // Guard in code too — not only via the disabled prop — so the commit path
    // is provably inert while blocked, independent of the button's styling.
    if (zoningBlocked) return;
    onConfirm(lines);
  };

  return (
    <View style={styles.sheet} testID="auto-schedule-review-sheet">
      <View style={styles.header}>
        <View style={styles.headerIconWrap}>
          <Sparkles {...Tokens.iconSize.default} color={colors.accent} />
        </View>
        <View style={styles.headerTextWrap}>
          <Text style={styles.eyebrow}>Auto-scheduled</Text>
          <Text style={styles.title} testID="review-sheet-title">
            {count === 1
              ? `1 inspection will be added to your schedule`
              : `${count} inspections will be added to your schedule`}
          </Text>
          <Text style={styles.subtitle}>
            Draft only — nothing changes until you confirm.
          </Text>
        </View>
      </View>

      {/* ── ZONING CONFIRM-GATE ── */}
      {zoningBlocked ? (
        <View style={styles.zoningBanner} testID="zoning-gate-banner">
          <ShieldQuestion {...Tokens.iconSize.default} color={colors.warningLabel} />
          <View style={styles.zoningTextWrap}>
            <Text style={styles.zoningTitle}>
              {zoning?.district
                ? `Confirm zoning: ${zoning.district}?`
                : 'Confirm zoning to enable'}
            </Text>
            <Text style={styles.zoningBody}>
              {zoning?.district
                ? `We guessed ${zoning.district} from the address. Confirm it to enable auto-scheduling — we won't schedule on a guess.`
                : `We can't auto-schedule until the jurisdiction's zoning is confirmed.`}
            </Text>
          </View>
          {onConfirmZoning ? (
            <TouchableOpacity
              onPress={onConfirmZoning}
              style={styles.zoningConfirmBtn}
              accessibilityRole="button"
              accessibilityLabel="Confirm zoning"
              testID="confirm-zoning-btn"
            >
              <ShieldCheck {...Tokens.iconSize.small} color={colors.accentFill} />
              <Text style={styles.zoningConfirmText}>Confirm</Text>
            </TouchableOpacity>
          ) : null}
        </View>
      ) : (
        <View style={styles.zoningConfirmed} testID="zoning-confirmed-chip">
          <ShieldCheck {...Tokens.iconSize.small} color={colors.successLabel} />
          <Text style={styles.zoningConfirmedText}>
            {zoning?.district
              ? `Zoning confirmed: ${zoning.district}`
              : 'Zoning confirmed'}
          </Text>
        </View>
      )}

      <ScrollView style={styles.list} testID="review-sheet-list">
        {lines.map((line) => (
          <View
            key={line.draftTask.id}
            style={styles.row}
            testID={`review-row-${line.inspection.id}`}
          >
            <View style={styles.rowIconWrap}>
              {line.unresolved ? (
                <Link2Off {...Tokens.iconSize.default} color={colors.warningLabel} />
              ) : (
                <CalendarClock {...Tokens.iconSize.default} color={colors.accent} />
              )}
            </View>
            <View style={styles.rowTextWrap}>
              <Text style={styles.rowTitle} testID={`review-row-title-${line.inspection.id}`}>
                {line.draftTask.title}
              </Text>
              {line.inspection.description ? (
                <Text style={styles.rowDesc} numberOfLines={2}>
                  {line.inspection.description}
                </Text>
              ) : null}
              <View style={styles.rowMeta}>
                <LeadTimeChip line={line} styles={styles} />
                {line.unresolved ? (
                  <View style={styles.unresolvedChip} testID={`review-row-unresolved-${line.inspection.id}`}>
                    <Text style={styles.unresolvedChipText}>couldn&apos;t link — pick a predecessor</Text>
                  </View>
                ) : null}
              </View>
            </View>
          </View>
        ))}
      </ScrollView>

      {unresolvedCount > 0 ? (
        <Text style={styles.unresolvedNote} testID="unresolved-note">
          {unresolvedCount === 1
            ? `1 task couldn't be linked — it's anchored to its book-by date until you pick a predecessor.`
            : `${unresolvedCount} tasks couldn't be linked — they're anchored to their book-by dates until you pick predecessors.`}
        </Text>
      ) : null}

      <View style={styles.actions}>
        <TouchableOpacity
          onPress={onCancel}
          style={styles.cancelBtn}
          accessibilityRole="button"
          accessibilityLabel="Cancel"
          testID="review-cancel-btn"
        >
          <Text style={styles.cancelText}>Cancel</Text>
        </TouchableOpacity>
        <TouchableOpacity
          onPress={handleConfirm}
          disabled={zoningBlocked}
          style={[styles.confirmBtn, zoningBlocked && styles.confirmBtnDisabled]}
          accessibilityRole="button"
          accessibilityState={{ disabled: zoningBlocked }}
          accessibilityLabel={
            zoningBlocked ? 'Confirm zoning to enable' : `Confirm and add ${count} to schedule`
          }
          testID="review-confirm-btn"
        >
          <Text style={[styles.confirmText, zoningBlocked && styles.confirmTextDisabled]}>
            {zoningBlocked
              ? 'Confirm zoning to enable'
              : count === 1
                ? 'Add to schedule'
                : `Add ${count} to schedule`}
          </Text>
        </TouchableOpacity>
      </View>
    </View>
  );
}

const makeStyles = (t: ThemeColors) =>
  StyleSheet.create({
    sheet: {
      backgroundColor: t.surface,
      borderTopLeftRadius: Tokens.radius.xl,
      borderTopRightRadius: Tokens.radius.xl,
      paddingHorizontal: Tokens.spacing.md,
      paddingTop: Tokens.spacing.lg,
      paddingBottom: Tokens.spacing.md,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: Tokens.spacing.sm,
      marginBottom: Tokens.spacing.md,
    },
    headerIconWrap: {
      width: Tokens.touchTarget.min,
      height: Tokens.touchTarget.min,
      borderRadius: Tokens.radius.card,
      backgroundColor: t.accentSoft,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTextWrap: { flex: 1 },
    eyebrow: { ...Type.eyebrow, color: t.accentLabel, marginBottom: Tokens.spacing.xxs },
    title: { ...Type.title3, color: t.text },
    subtitle: { ...Type.footnote, color: t.textSecondary, marginTop: Tokens.spacing.xxs },

    zoningBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Tokens.spacing.sm,
      backgroundColor: t.warningSoft,
      borderRadius: Tokens.radius.card,
      padding: Tokens.spacing.sm,
      marginBottom: Tokens.spacing.sm,
    },
    zoningTextWrap: { flex: 1 },
    zoningTitle: { ...Type.subheadEmphasized, color: t.warningLabel },
    zoningBody: { ...Type.footnote, color: t.textSecondary, marginTop: Tokens.spacing.hairline },
    zoningConfirmBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Tokens.spacing.xxs,
      backgroundColor: t.surface,
      borderRadius: Tokens.radius.sm,
      paddingHorizontal: Tokens.spacing.sm,
      paddingVertical: Tokens.spacing.xs,
      borderWidth: 1,
      borderColor: t.line,
    },
    zoningConfirmText: { ...Type.footnoteEmphasized, color: t.accentLabel },

    zoningConfirmed: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Tokens.spacing.xxs,
      backgroundColor: t.successSoft,
      borderRadius: Tokens.radius.sm,
      paddingHorizontal: Tokens.spacing.sm,
      paddingVertical: Tokens.spacing.xs,
      alignSelf: 'flex-start',
      marginBottom: Tokens.spacing.sm,
    },
    zoningConfirmedText: { ...Type.footnoteEmphasized, color: t.successLabel },

    list: { maxHeight: 340 },
    row: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: Tokens.spacing.sm,
      paddingVertical: Tokens.spacing.sm,
      borderBottomWidth: 1,
      borderBottomColor: t.line,
    },
    rowIconWrap: {
      width: Tokens.iconSize.large.size + Tokens.spacing.xs,
      height: Tokens.iconSize.large.size + Tokens.spacing.xs,
      borderRadius: Tokens.radius.sm,
      backgroundColor: t.surfaceAlt,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: Tokens.spacing.hairline,
    },
    rowTextWrap: { flex: 1 },
    rowTitle: { ...Type.subheadEmphasized, color: t.text },
    rowDesc: { ...Type.footnote, color: t.textSecondary, marginTop: Tokens.spacing.hairline },
    rowMeta: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: Tokens.spacing.xs,
      marginTop: Tokens.spacing.xs,
    },
    chip: {
      backgroundColor: t.surfaceAlt,
      borderRadius: Tokens.radius.xs,
      paddingHorizontal: Tokens.spacing.xs,
      paddingVertical: Tokens.spacing.hairline,
    },
    chipText: { ...Type.caption1, color: t.textSecondary },
    unresolvedChip: {
      backgroundColor: t.warningSoft,
      borderRadius: Tokens.radius.xs,
      paddingHorizontal: Tokens.spacing.xs,
      paddingVertical: Tokens.spacing.hairline,
    },
    unresolvedChipText: { ...Type.caption1, color: t.warningLabel },

    unresolvedNote: {
      ...Type.footnote,
      color: t.warningLabel,
      marginTop: Tokens.spacing.sm,
    },

    actions: {
      flexDirection: 'row',
      gap: Tokens.spacing.sm,
      marginTop: Tokens.spacing.md,
    },
    cancelBtn: {
      flex: 1,
      minHeight: Tokens.touchTarget.comfortable,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: Tokens.radius.card,
      borderWidth: 1,
      borderColor: t.line,
    },
    cancelText: { ...Type.bodyEmphasized, color: t.text },
    confirmBtn: {
      flex: 2,
      minHeight: Tokens.touchTarget.comfortable,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: Tokens.radius.card,
      backgroundColor: t.accentFill,
    },
    confirmBtnDisabled: { backgroundColor: t.surfaceAlt },
    // White ink on the accent fill — static token (t.surface would flip dark).
    confirmText: { ...Type.bodyEmphasized, color: Colors.textOnAccent },
    confirmTextDisabled: { color: t.textMuted },
  });
