// utils/codeFlags/fixtures.ts — Code Flags: example lines with the answer each
// must give. Realistic residential and small commercial change order and
// estimate lines. scripts/validate-code-flags.ts runs every one and fails on
// any difference, in either direction: a negative that starts to flag is as
// much a failure as a positive that stops.
//
// `expect` is the EXACT set of families (order does not matter): the permit
// kinds the line's own chip carries (match.flagLine) together with the
// building-age kinds a change order holding ONLY this line would show in its
// one row (match.flagBuildingAge). `ctx` names a place and a year where the
// answer depends on one; without it the line is read with no project (no
// place, no year, residential).
//
// Every line the independent review quoted is here, under "review item N".
//
// Pure data. Imported by the validator and the smoke test only.
import type { CodeFlagFamilyId } from '@/utils/codeFlags/rules';
import type { CodeFlagPlaceId } from '@/utils/codeFlags/place';

export interface CodeFlagFixture {
  line: { name: string; description?: string; category?: string; csiDivision?: string };
  expect: CodeFlagFamilyId[];
  ctx?: { place?: CodeFlagPlaceId; yearBuilt?: number | null; jobKind?: 'residential' | 'commercial' };
  /** Why this line is here, for the person reading a failure. */
  note?: string;
}

const NYC_1931 = { place: 'nyc' as const, yearBuilt: 1931 };
const NYC_1995 = { place: 'nyc' as const, yearBuilt: 1995 };
const BC_1920 = { place: 'baltimore_city' as const, yearBuilt: 1920 };

export const CODE_FLAG_POSITIVES: readonly CodeFlagFixture[] = [
  // ── exits and ways out ──
  { line: { name: 'Add egress window at basement bedroom' }, expect: ['egress'] },
  { line: { name: 'Install exit sign and emergency lighting at rear corridor' }, expect: ['egress'] },
  { line: { name: 'Panic hardware on rear exit door' }, expect: ['egress'] },
  { line: { name: 'Cut in window well for cellar' }, expect: ['egress'] },
  { line: { name: 'Relocate stair to rear of unit' }, expect: ['egress'] },
  { line: { name: 'Infill door at side yard and patch brick' }, expect: ['egress'] },
  { line: { name: 'Repair fire escape drop ladder' }, expect: ['egress'] },
  { line: { name: 'Add exterior door to mudroom', description: 'new exterior door with landing' }, expect: ['egress'] },
  // ── fire-rated walls, doors and ceilings ──
  { line: { name: '1-hour rated demising wall between tenants' }, expect: ['fire_rating'] },
  { line: { name: 'Furnish and install 90 minute door at stair' }, expect: ['fire_rating'] },
  { line: { name: 'Firestopping at pipe penetrations' }, expect: ['fire_rating'] },
  { line: { name: '5/8 Type X drywall at garage ceiling' }, expect: ['fire_rating'] },
  { line: { name: 'Fire damper at duct through corridor wall' }, expect: ['fire_rating'] },
  { line: { name: 'Shaft wall liner at new chase' }, expect: ['fire_rating'] },
  { line: { name: 'Replace fire door closer and gasketing', description: 'self-closing, 45 minute rated' }, expect: ['fire_rating'] },
  { line: { name: 'Intumescent paint on exposed steel' }, expect: ['fire_rating'], note: 'no year on file, so the lead rule stays quiet on "paint"' },
  // ── sprinklers, alarms and hood suppression ──
  { line: { name: 'Relocate 4 sprinkler heads for new ceiling layout' }, expect: ['fire_protection'] },
  { line: { name: 'Add fire alarm pull station at new exit' }, expect: ['fire_protection'] },
  { line: { name: 'Hardwired smoke detectors, interconnected' }, expect: ['fire_protection'] },
  { line: { name: 'Ansul system for cooking line' }, expect: ['fire_protection'] },
  { line: { name: 'Type I hood with suppression system' }, expect: ['fire_protection'] },
  { line: { name: 'Carbon monoxide alarm at boiler room' }, expect: ['fire_protection'], note: 'a boiler room is a room, not boiler work' },
  // ── bearing walls, beams and foundations ──
  { line: { name: 'Remove load bearing wall between kitchen and dining' }, expect: ['structural'] },
  { line: { name: 'Install LVL beam and posts' }, expect: ['structural'] },
  { line: { name: 'Sister floor joists at bathroom' }, expect: ['structural'] },
  { line: { name: 'New footing for lally column' }, expect: ['structural'] },
  { line: { name: 'Steel lintel at enlarged opening' }, expect: ['structural'] },
  { line: { name: 'Rear addition framing' }, expect: ['structural'] },
  { line: { name: 'Shed dormer at attic' }, expect: ['structural'] },
  { line: { name: 'Underpinning at party wall' }, expect: ['structural'], ctx: { place: 'baltimore_city' }, note: 'carries the one Baltimore City section number on file' },
  { line: { name: 'Widen doorway to 36 in. at kitchen' }, expect: ['structural'] },
  { line: { name: 'Retaining wall at rear yard, 5 ft' }, expect: ['structural'] },
  // ── electrical service, panels and big new loads ──
  { line: { name: 'Upgrade service to 200 amp' }, expect: ['electrical_service'] },
  { line: { name: 'Add subpanel in garage' }, expect: ['electrical_service'] },
  { line: { name: 'Replace electrical panel' }, expect: ['electrical_service'] },
  { line: { name: 'Panel', category: 'electrical' }, expect: ['electrical_service'], note: 'bare "panel" counts only on an Electrical line' },
  { line: { name: 'Dedicated circuit for microwave' }, expect: ['electrical_service'] },
  { line: { name: 'EV charger, level 2, at driveway' }, expect: ['electrical_service'] },
  { line: { name: 'Standby generator and transfer switch' }, expect: ['electrical_service'] },
  { line: { name: 'Rewire second floor, remove knob and tube' }, expect: ['electrical_service'] },
  { line: { name: 'Induction range, 240V feed' }, expect: ['electrical_service'] },
  { line: { name: 'Relocate meter to exterior', csiDivision: '26 0500' }, expect: ['electrical_service'] },
  // ── added or moved plumbing ──
  { line: { name: 'Add half bath under stairs' }, expect: ['plumbing'] },
  { line: { name: 'Relocate toilet 3 ft to north wall' }, expect: ['plumbing'] },
  { line: { name: 'Wet bar with bar sink in basement' }, expect: ['plumbing'] },
  { line: { name: 'Replace water heater, 50 gal' }, expect: ['plumbing'] },
  { line: { name: 'New sewer line to street' }, expect: ['plumbing'] },
  { line: { name: 'Rough plumbing for added laundry' }, expect: ['plumbing'] },
  { line: { name: 'Convert tub to shower' }, expect: ['plumbing'] },
  { line: { name: 'Backflow preventer at water service' }, expect: ['plumbing'] },
  { line: { name: 'Rough in', category: 'plumbing' }, expect: ['plumbing'], note: 'bare "rough in" counts only on a Plumbing line' },
  { line: { name: 'Grease trap for prep kitchen' }, expect: ['plumbing'] },
  // ── gas ──
  { line: { name: 'Run gas line to new range' }, expect: ['gas'] },
  { line: { name: 'Gas fireplace insert' }, expect: ['gas'] },
  { line: { name: 'Oil to gas conversion' }, expect: ['gas'] },
  { line: { name: 'Pressure test gas piping' }, expect: ['gas'] },
  { line: { name: 'Propane tank and regulator for generator' }, expect: ['gas', 'electrical_service'] },
  { line: { name: 'CSST to rooftop unit' }, expect: ['gas', 'mechanical'] },
  // ── mechanical equipment, ventilation and venting ──
  { line: { name: 'Replace boiler with high efficiency unit' }, expect: ['mechanical'] },
  { line: { name: 'New bath exhaust fan ducted to exterior' }, expect: ['mechanical'] },
  { line: { name: 'Range hood, 600 cfm, with makeup air' }, expect: ['mechanical'] },
  { line: { name: 'Mini split, two zones' }, expect: ['mechanical'] },
  { line: { name: 'Stainless chimney liner' }, expect: ['mechanical'] },
  { line: { name: 'Reroute dryer vent to side wall' }, expect: ['mechanical'] },
  { line: { name: 'Heat pump water heater' }, expect: ['mechanical', 'electrical_service', 'plumbing'] },
  { line: { name: 'New ductwork for second floor' }, expect: ['mechanical'] },
  // ── change of use ──
  { line: { name: 'Garage conversion to living space' }, expect: ['change_of_use'] },
  { line: { name: 'Legalize basement apartment' }, expect: ['change_of_use'] },
  { line: { name: 'Finish basement, 600 sq ft' }, expect: ['change_of_use'] },
  { line: { name: 'Convert storefront to restaurant', description: 'change of use' }, expect: ['change_of_use'] },
  { line: { name: 'Add bedroom at attic' }, expect: ['change_of_use'] },
  { line: { name: 'ADU over detached garage' }, expect: ['change_of_use'] },
  // ── energy code tests ──
  { line: { name: 'Blower door test' }, expect: ['energy_tests'] },
  { line: { name: 'Duct leakage test and report' }, expect: ['energy_tests'] },
  { line: { name: 'Manual J for new system' }, expect: ['energy_tests'] },
  // ── decks, stairs, guards and railings ──
  { line: { name: 'New deck, 12 x 16, pressure treated' }, expect: ['decks_stairs'] },
  { line: { name: 'Replace ledger board and flash' }, expect: ['decks_stairs'] },
  { line: { name: 'Guardrail at roof deck' }, expect: ['decks_stairs'] },
  { line: { name: 'Add handrail at front steps' }, expect: ['decks_stairs'] },
  { line: { name: 'Rebuild porch roof' }, expect: ['decks_stairs'] },
  { line: { name: 'New staircase to basement' }, expect: ['decks_stairs'] },
  // ── building age ──
  { line: { name: 'Replace 6 windows' }, expect: ['lead_age'], ctx: BC_1920, note: 'built before 1978, residential' },
  { line: { name: 'Scrape and paint exterior trim' }, expect: ['lead_age'], ctx: { place: 'other', yearBuilt: 1962 }, note: 'lead is federal: it shows outside the three places, with no local link' },
  { line: { name: 'Demo plaster ceiling at kitchen' }, expect: ['lead_age', 'asbestos_age'], ctx: NYC_1931 },
  { line: { name: 'Demo plaster ceiling at kitchen' }, expect: ['lead_age'], ctx: BC_1920, note: 'the asbestos rule is New York City only' },
  { line: { name: 'Remove pipe insulation at boiler room' }, expect: ['asbestos_age'], ctx: NYC_1931 },
  { line: { name: 'Upgrade service to 200 amp' }, expect: ['electrical_service', 'asbestos_age'], ctx: NYC_1931, note: 'asbestos rides along with a permit flag in New York City' },
  { line: { name: 'Gut renovation of bathroom', description: 'full gut to studs' }, expect: ['asbestos_age'], ctx: { place: 'nyc', yearBuilt: 1987 }, note: '1987 itself still fires' },
  // ── review item 1: a verb and its noun a few words apart ──
  { line: { name: 'Remove the wall' }, expect: ['structural'] },
  { line: { name: 'Take down the kitchen wall' }, expect: ['structural'] },
  { line: { name: 'Open up wall between LR and DR' }, expect: ['structural'] },
  { line: { name: 'Move the toilet 2 ft to the left' }, expect: ['plumbing'] },
  { line: { name: 'Relocate kitchen sink to island' }, expect: ['plumbing'] },
  { line: { name: 'Enlarge door opening to 36 in' }, expect: ['structural'] },
  { line: { name: 'Replace cast iron stack' }, expect: ['plumbing'] },
  { line: { name: 'Rebuild front steps' }, expect: ['decks_stairs'] },
  { line: { name: 'Rebuild front porch' }, expect: ['decks_stairs'] },
  { line: { name: 'Knock down the existing rear wall' }, expect: ['structural'] },
  { line: { name: 'Demo the old dining room wall' }, expect: ['structural'] },
  { line: { name: 'Move existing powder room toilet' }, expect: ['plumbing'] },
  { line: { name: 'Add a second floor bathroom' }, expect: ['plumbing'] },
  { line: { name: 'Install new 20A circuits' }, expect: ['electrical_service'] },
  { line: { name: 'Relocate the basement stair' }, expect: ['egress'] },
  { line: { name: 'Cut new window opening at rear' }, expect: ['structural'] },
  { line: { name: 'Install new header over opening' }, expect: ['structural'] },
  { line: { name: 'Replace the rear deck' }, expect: ['decks_stairs'] },
  { line: { name: 'New front stoop' }, expect: ['decks_stairs'] },
  { line: { name: 'Build new roof deck' }, expect: ['decks_stairs'] },
  // ── review item 2: plurals ──
  { line: { name: 'Replace roof trusses' }, expect: ['structural'] },
  { line: { name: 'Rebuild porches at units 1 and 2' }, expect: ['decks_stairs'] },
  { line: { name: 'Repair balconies' }, expect: ['decks_stairs'] },
  { line: { name: 'Sister joists and add footings' }, expect: ['structural'] },
  { line: { name: 'Replace two boilers' }, expect: ['mechanical'] },
  { line: { name: 'Rebuild both rear stairways' }, expect: ['decks_stairs'] },
  { line: { name: 'Fire dampers at corridor' }, expect: ['fire_rating'] },
  // ── review item 3: real sprinkler work on a garden level ──
  { line: { name: 'Relocate sprinkler heads at garden level' }, expect: ['fire_protection'] },
  { line: { name: 'Garden level fire alarm devices' }, expect: ['fire_protection'] },
  { line: { name: 'Add sprinkler heads at garden apartment' }, expect: ['fire_protection'] },
  { line: { name: 'Sprinkler main at rear yard extension' }, expect: ['fire_protection'] },
  // ── review item 4: Spanish ──
  { line: { name: 'Nueva línea de gas para la estufa' }, expect: ['gas'] },
  { line: { name: 'Nueva linea de gas para la estufa' }, expect: ['gas'], note: 'typed with no accent' },
  { line: { name: 'Mover el inodoro' }, expect: ['plumbing'] },
  { line: { name: 'Reubicar el fregadero de la cocina' }, expect: ['plumbing'] },
  { line: { name: 'Quitar la pared de la cocina' }, expect: ['structural'] },
  { line: { name: 'Tumbar pared de carga' }, expect: ['structural'] },
  { line: { name: 'Cambio de panel eléctrico' }, expect: ['electrical_service'] },
  { line: { name: 'Agregar 4 circuitos nuevos' }, expect: ['electrical_service'] },
  { line: { name: 'Instalar calentador de agua' }, expect: ['plumbing'] },
  { line: { name: 'Detectores de humo en los dormitorios' }, expect: ['fire_protection'] },
  { line: { name: 'Caldera nueva' }, expect: ['mechanical'] },
  { line: { name: 'Instalar aire acondicionado central' }, expect: ['mechanical'] },
  { line: { name: 'Legalizar apartamento en el sótano' }, expect: ['change_of_use'] },
  { line: { name: 'Pasamanos en la escalera' }, expect: ['decks_stairs'] },
  { line: { name: 'Reconstruir escalones del frente' }, expect: ['decks_stairs'] },
  { line: { name: 'Puerta cortafuego en el pasillo' }, expect: ['fire_rating'] },
  { line: { name: 'Salida de emergencia trasera' }, expect: ['egress'] },
  { line: { name: 'Prueba de fugas en ductos' }, expect: ['energy_tests'] },
  { line: { name: 'Quitar tabique del closet' }, expect: ['layout_change'] },
  { line: { name: 'Instalar viga de acero' }, expect: ['structural'] },
  { line: { name: 'Tubería de gas a la caldera' }, expect: ['gas', 'mechanical'] },
  // ── review item 5: "by others" still flags ──
  { line: { name: 'Electrical panel by others' }, expect: ['electrical_service'] },
  { line: { name: 'Gas piping by others' }, expect: ['gas'] },
  { line: { name: 'Self closing door at garage entry' }, expect: ['fire_rating'] },
  { line: { name: 'Install standby generator' }, expect: ['electrical_service'] },
  { line: { name: 'New shower in basement' }, expect: ['plumbing'] },
  { line: { name: 'New drain line for island sink' }, expect: ['plumbing'] },
  { line: { name: 'Run 3/4 black pipe to range' }, expect: ['gas'] },
  { line: { name: 'Propane line to grill' }, expect: ['gas'] },
  // ── review item 6: layout changes ──
  { line: { name: 'Remove non-load-bearing partition' }, expect: ['layout_change'] },
  { line: { name: 'Remove non load bearing wall' }, expect: ['layout_change'] },
  { line: { name: 'Demo partition walls' }, expect: ['layout_change'] },
  { line: { name: 'Remove non-load-bearing partition at closet' }, expect: ['layout_change'] },
  { line: { name: 'Frame new partition at bedroom closet' }, expect: ['layout_change'] },
  { line: { name: 'Build new wall to split bedroom' }, expect: ['layout_change'] },
  { line: { name: 'Relocate partition 2 ft' }, expect: ['layout_change'] },
  { line: { name: 'Install partitions per plan' }, expect: ['layout_change'] },
  // ── review item 7: abbreviations and misspellings ──
  { line: { name: 'Replace elec. panel' }, expect: ['electrical_service'] },
  { line: { name: 'Add (4) 20A circuits for kitchen' }, expect: ['electrical_service'] },
  { line: { name: 'Electric svc' }, expect: ['electrical_service'] },
  { line: { name: 'Replace W/H with 50 gal' }, expect: ['plumbing'] },
  { line: { name: 'Replace HVAC' }, expect: ['mechanical'] },
  { line: { name: 'Vent dryer to exterior' }, expect: ['mechanical'] },
  { line: { name: 'Convert stove from electric to gas' }, expect: ['gas'] },
  { line: { name: 'Tesla wall connector install' }, expect: ['electrical_service'] },
  { line: { name: 'Subpannel' }, expect: ['electrical_service'] },
  { line: { name: 'AC condensor' }, expect: ['mechanical'] },
  { line: { name: 'Reline chimney' }, expect: ['mechanical'] },
  { line: { name: 'Core drill 2-hr slab' }, expect: ['fire_rating'] },
  { line: { name: 'Close off rear door' }, expect: ['egress'] },
  { line: { name: 'New A/C unit at roof' }, expect: ['mechanical'] },
  { line: { name: 'Upgrade elec svc to 200A' }, expect: ['electrical_service'] },
  { line: { name: 'Replace HWH' }, expect: ['plumbing'] },
  { line: { name: 'Install EVSE in garage' }, expect: ['electrical_service'] },
  { line: { name: 'Brick up door at rear' }, expect: ['egress'] },
  { line: { name: 'Replace AC' }, expect: ['mechanical'] },
];

export const CODE_FLAG_NEGATIVES: readonly CodeFlagFixture[] = [
  // ── close to exits ──
  { line: { name: 'Exit interview with homeowner' }, expect: [] },
  { line: { name: 'Final exit cleaning' }, expect: [] },
  { line: { name: 'Interior door slab, 2 panel, primed' }, expect: [] },
  { line: { name: 'Stair runner carpet' }, expect: [] },
  { line: { name: 'Door hardware, satin nickel' }, expect: [] },
  // ── close to fire rating ──
  { line: { name: 'Fire pit' }, expect: [] },
  { line: { name: 'Gas fire pit kit with lava rock' }, expect: [], note: '"fire pit" is not fire rating, and a kit is not gas piping' },
  { line: { name: 'Fireplace mantel, reclaimed oak' }, expect: [] },
  { line: { name: 'Network firewall for office IT closet' }, expect: [] },
  { line: { name: 'Energy Star rated dishwasher' }, expect: [] },
  { line: { name: '2 hour minimum labor charge' }, expect: [] },
  { line: { name: 'Fire extinguisher, 5 lb ABC' }, expect: [] },
  { line: { name: 'Standard 1/2 in. drywall at closet' }, expect: [] },
  // ── close to sprinklers and alarms ──
  { line: { name: 'Lawn sprinkler system, 6 zones' }, expect: [] },
  { line: { name: 'Replace irrigation sprinkler heads' }, expect: [] },
  { line: { name: 'Sprinkler system for the garden beds' }, expect: [] },
  { line: { name: 'Alarm clock radio for model unit' }, expect: [] },
  // ── close to structural ──
  { line: { name: 'Faux beam at living room ceiling' }, expect: [] },
  { line: { name: 'In addition to base scope, extra coat of sealer' }, expect: [] },
  { line: { name: 'Foundation planting bed and mulch' }, expect: [] },
  { line: { name: 'Laser beam level rental' }, expect: [] },
  { line: { name: 'Post light at driveway' }, expect: [] },
  { line: { name: 'Column of tile at shower niche' }, expect: [] },
  { line: { name: 'Hang wall cabinets' }, expect: [] },
  { line: { name: 'Structural Screw 3 in. Hex (50ct)', category: 'hardware' }, expect: [], note: 'a box of screws is not structural work' },
  { line: { name: 'Joist Hanger LUS26 (50ct)', category: 'hardware' }, expect: [] },
  // ── close to electrical ──
  { line: { name: 'Panel door' }, expect: [] },
  { line: { name: 'Six panel door slab, solid core' }, expect: [] },
  { line: { name: 'Tub access panel' }, expect: [] },
  { line: { name: 'Raised panel wainscot' }, expect: [] },
  { line: { name: 'Panel', category: 'doors' }, expect: [], note: 'bare "panel" off an Electrical line is nothing' },
  { line: { name: 'Service call fee' }, expect: [] },
  { line: { name: 'Bird feeder post' }, expect: [] },
  { line: { name: 'Steam generator for shower' }, expect: [] },
  { line: { name: 'Solar shade at patio door' }, expect: [] },
  { line: { name: 'Replace outlet covers, white' }, expect: [] },
  { line: { name: 'Portable generator rental for site power' }, expect: [] },
  { line: { name: 'LED recessed light, 6 in.', category: 'electrical' }, expect: [] },
  { line: { name: 'Cabinet end panel and filler panel' }, expect: [] },
  { line: { name: '20A circuit breaker, single pole', category: 'electrical' }, expect: [], note: 'a breaker is a part, not a new circuit' },
  // ── close to plumbing ──
  { line: { name: 'Replace faucet at kitchen sink' }, expect: [] },
  { line: { name: 'Toilet seat, elongated' }, expect: [] },
  { line: { name: 'New shower curtain rod' }, expect: [] },
  { line: { name: 'New shower door, frameless' }, expect: [] },
  { line: { name: 'Drain cleaning' }, expect: [] },
  { line: { name: 'New light fixture at vanity' }, expect: [] },
  { line: { name: 'Caulk tub surround' }, expect: [] },
  { line: { name: 'Rough in', category: 'electrical' }, expect: [], note: 'bare "rough in" off a Plumbing line is nothing' },
  // ── close to gas ──
  { line: { name: 'Gas mileage and travel' }, expect: [] },
  { line: { name: 'Argon gas filled insulated glass unit' }, expect: [] },
  { line: { name: 'Gas strut for attic hatch' }, expect: [] },
  { line: { name: 'Gas powered compressor rental' }, expect: [] },
  { line: { name: 'Wax gasket for toilet' }, expect: [] },
  // ── close to mechanical ──
  { line: { name: 'Ridge vent at reroof' }, expect: [] },
  { line: { name: 'Dryer vent cleaning' }, expect: [] },
  { line: { name: 'Furnace filter change' }, expect: [] },
  { line: { name: 'Ceiling fan install' }, expect: [] },
  { line: { name: 'Window air conditioner sleeve' }, expect: [] },
  { line: { name: 'Soffit vent strip' }, expect: [] },
  { line: { name: 'Vent cover, white, 4 x 10' }, expect: [] },
  // ── close to change of use ──
  { line: { name: 'Convert to LED lighting' }, expect: [] },
  { line: { name: 'Bedroom door hardware' }, expect: [] },
  { line: { name: 'Carpet at bedroom' }, expect: [] },
  // ── close to energy tests ──
  { line: { name: 'His and hers vanity' }, expect: [] },
  { line: { name: 'Energy Star refrigerator' }, expect: [] },
  { line: { name: 'Attic insulation, R-38 blown' }, expect: [] },
  // ── close to decks and stairs ──
  { line: { name: 'Deck stain and seal' }, expect: [] },
  { line: { name: 'Replace deck boards' }, expect: [] },
  { line: { name: 'Ledger stone veneer at fireplace' }, expect: [] },
  { line: { name: 'Replace roof decking, 4 sheets' }, expect: [] },
  { line: { name: 'Power wash the deck' }, expect: [] },
  // ── building age: the year, the place and the job decide ──
  { line: { name: 'Replace 6 windows' }, expect: [], ctx: { place: 'baltimore_city', yearBuilt: 1985 }, note: 'built after 1977' },
  { line: { name: 'Replace 6 windows' }, expect: [], ctx: { place: 'baltimore_city', yearBuilt: null }, note: 'no year on file: nothing fires' },
  { line: { name: 'Replace 6 windows' }, expect: [], ctx: { place: 'nyc', yearBuilt: 1931, jobKind: 'commercial' }, note: 'the lead rule is residential' },
  { line: { name: 'Demo plaster ceiling at kitchen' }, expect: [], ctx: NYC_1995, note: 'built after 1987 and after 1977' },
  { line: { name: 'Window treatment install' }, expect: [], ctx: NYC_1931 },
  { line: { name: 'Trim trees along the fence' }, expect: [], ctx: NYC_1931 },
  { line: { name: 'Gutter cleaning' }, expect: [], ctx: NYC_1931 },
  { line: { name: 'Snow removal' }, expect: [], ctx: NYC_1931 },
  // ── ordinary lines ──
  { line: { name: 'Kitchen cabinets, shaker, white' }, expect: [], note: 'a room name alone is not a flag' },
  { line: { name: 'Quartz countertop, 42 sq ft' }, expect: [] },
  { line: { name: 'Tile backsplash' }, expect: [] },
  { line: { name: 'Hardwood floor refinish' }, expect: [] },
  { line: { name: 'Bathroom vanity, 36 in.' }, expect: [] },
  { line: { name: 'Dumpster, 20 yd' }, expect: [] },
  { line: { name: 'Permit fee allowance' }, expect: [] },
  { line: { name: 'Project management and supervision' }, expect: [] },
  { line: { name: '' }, expect: [] },
  // ── review item 5: loose words ──
  { line: { name: 'Addition of 6 recessed lights' }, expect: [] },
  { line: { name: 'Addition of crown molding' }, expect: [] },
  { line: { name: 'No structural work' }, expect: [] },
  { line: { name: 'Not including electrical panel' }, expect: [] },
  { line: { name: 'Excluding gas piping' }, expect: [] },
  { line: { name: 'No new circuits' }, expect: [] },
  { line: { name: 'Sin trabajo estructural' }, expect: [] },
  { line: { name: 'No incluye panel eléctrico' }, expect: [] },
  { line: { name: 'Header board for bed' }, expect: [] },
  { line: { name: 'Header: Kitchen' }, expect: [] },
  { line: { name: 'Self closing cabinet hinges' }, expect: [] },
  { line: { name: 'Soft/self-closing drawer slides' }, expect: [] },
  { line: { name: 'toilet seat (self closing)' }, expect: [] },
  { line: { name: 'Replace rotted roof deck plywood' }, expect: [] },
  { line: { name: 'Roof deck sheathing 1/2 CDX' }, expect: [] },
  { line: { name: 'Ledger entry adjustment' }, expect: [] },
  { line: { name: 'Temporary guardrail at stair opening' }, expect: [] },
  { line: { name: 'New shower tile' }, expect: [] },
  { line: { name: 'New shower valve trim' }, expect: [] },
  { line: { name: 'Snake drain line' }, expect: [] },
  { line: { name: 'Clear main drain line clog' }, expect: [] },
  { line: { name: 'Propane for temp heaters' }, expect: [] },
  { line: { name: 'Black pipe shelf brackets' }, expect: [] },
  { line: { name: 'Boiler plate contract language' }, expect: [] },
  { line: { name: 'Boiler room door paint' }, expect: [] },
  { line: { name: 'Generator for temp power' }, expect: [] },
  { line: { name: 'Hot tub cover' }, expect: [] },
  { line: { name: 'Induction cooktop delivery' }, expect: [] },
  { line: { name: 'Recessed light trim panel', category: 'electrical' }, expect: [] },
  { line: { name: 'Low voltage panel cover', category: 'electrical' }, expect: [] },
  { line: { name: 'Exit sign sticker' }, expect: [] },
  // ── review item 7: a bare heading is not a flag ──
  { line: { name: 'HVAC' }, expect: [] },
  { line: { name: 'Electrical' }, expect: [] },
  { line: { name: 'Plumbing' }, expect: [] },
  // ── the verb-and-noun window: what must NOT reach ──
  { line: { name: 'Remove wall tile at backsplash' }, expect: [] },
  { line: { name: 'Remove cabinets and patch wall' }, expect: [] },
  { line: { name: 'Remove cabinets, patch wall' }, expect: [] },
  { line: { name: 'Remove wallpaper at dining room' }, expect: [] },
  { line: { name: 'Install wall cabinets' }, expect: [] },
  { line: { name: 'New wall sconce at hallway' }, expect: [] },
  { line: { name: 'Paint the wall at stair' }, expect: [] },
  { line: { name: 'Replace stair treads' }, expect: [] },
  { line: { name: 'Replace step flashing at chimney wall' }, expect: [] },
  { line: { name: 'Replace HVAC filter' }, expect: [] },
  { line: { name: 'Add circuit breaker lock' }, expect: [] },
  { line: { name: 'Move sink faucet order to next week' }, expect: [] },
  { line: { name: 'New bath accessories' }, expect: [] },
  { line: { name: 'New bathroom vanity, 36 in.' }, expect: [] },
  { line: { name: 'Relocate toilet paper holder' }, expect: [] },
  { line: { name: 'Remove door and rehang after flooring' }, expect: [] },
  { line: { name: 'Temporary dust partition at kitchen' }, expect: [] },
  { line: { name: 'Toilet partitions, powder coated' }, expect: [] },
  { line: { name: 'New stone wall at garden bed' }, expect: [] },
  { line: { name: 'Replace deck board at stair' }, expect: [] },
  { line: { name: 'Clean dryer vent' }, expect: [] },
  { line: { name: 'Line set cover' }, expect: [] },
  // ── Spanish that must stay quiet ──
  { line: { name: 'Pintar la pared de la sala' }, expect: [] },
  { line: { name: 'Limpieza de drenaje' }, expect: [] },
  { line: { name: 'Aire acondicionado de ventana' }, expect: [] },
  { line: { name: 'Gabinetes de cocina' }, expect: [] },
  { line: { name: 'Azulejo de pared en el baño' }, expect: [] },
  { line: { name: 'Destapar drenaje de la cocina' }, expect: [] },
  // ── more ordinary lines ──
  { line: { name: 'Drip irrigation line at planters' }, expect: [] },
  { line: { name: 'Garden hose reel' }, expect: [] },
  { line: { name: 'Yard cleanup and haul away' }, expect: [] },
  { line: { name: 'Wall mounted TV bracket' }, expect: [] },
  { line: { name: 'Shower wall tile, 3 x 6 subway' }, expect: [] },
  { line: { name: 'Closet door hardware' }, expect: [] },
  { line: { name: 'Final cleaning' }, expect: [] },
  { line: { name: 'Appliance delivery and placement' }, expect: [] },
  { line: { name: 'Fire door label' }, expect: [] },
  { line: { name: 'Hand sanding of floors' }, expect: [] },
  { line: { name: 'Stair tread carpet' }, expect: [] },
  { line: { name: 'Punch list and touch up' }, expect: [] },
];
