-- 20261002161000_job_fact_links.sql
--
-- public.job_fact_links: one read-only "job facts" link per job (lane FACTS).
--
-- WHAT A ROW MEANS. The GC picked some sections of one job (permits,
-- inspections, the change-order trail, finished milestones, chosen photos,
-- closeout and warranties) and published them as a page at
-- https://mageid.app/facts/<code>. `payload` is the snapshot his phone built
-- with utils/jobFacts/buildJobFacts.ts, an allowlist builder: plain recorded
-- facts, each with its source record and its date. No cost, no notes, no
-- emails, no storage paths, no predictions. A Refresh rewrites the same row,
-- so the link the GC already sent keeps working and the page says "as of
-- <published_at>".
--
-- WHO WRITES. The owner of the job, from the app, through RLS: insert and
-- update own rows on a project he owns. Column grants limit what he can write:
-- INSERT (project_id, sections, payload) and UPDATE (sections, payload,
-- revoked_at). He can never write `code` (server-generated by
-- public.job_fact_code(), crypto random), `user_id` (defaults to auth.uid()),
-- `published_at` (the trigger stamps it when the payload changes, so the page's
-- "as of" date cannot be forged) or `last_viewed_at` (the view function's).
-- The edge function job-facts-view (service role) writes last_viewed_at only.
--
-- WHO READS. The owner, through RLS (select own). The public page reads one
-- row by its code through job-facts-view (service role, named columns only),
-- which answers the same 404 {live:false} for an unknown code and a revoked one
-- and never returns user_id, project_id or the row id. anon has no privilege.
--
-- ONE LIVE LINK PER JOB. A partial unique index on (project_id) where
-- revoked_at is null. Revoke, then publish again, mints a new code.
--
-- REVOKE. An update that sets revoked_at (the trigger stamps now(), so it
-- cannot be back-dated). A revoked link is final: the trigger refuses every
-- later update of that row, so it can never be un-revoked or refilled. There
-- is no delete policy; the account-deletion and project-deletion cascades
-- remove the rows with the login or the job.
--   support, by hand, at the GC's request:
--   update public.job_fact_links set revoked_at = now() where code = 'XXXXXXXXXXXX' and revoked_at is null;
--
-- DEPLOY ORDER: apply this BEFORE deploying job-facts-view (it would 502 on a
-- missing table) and before the OTA that ships app/job-facts.tsx.
--
-- VERIFY AFTER
--   select relrowsecurity from pg_class where oid = 'public.job_fact_links'::regclass;   -- true
--   select policyname, roles, cmd from pg_policies
--    where schemaname = 'public' and tablename = 'job_fact_links' order by policyname;
--     -- exactly three, all {authenticated}: job_fact_links_insert_own INSERT,
--     -- job_fact_links_select_own SELECT, job_fact_links_update_own UPDATE
--   select has_table_privilege('authenticated', 'public.job_fact_links', 'SELECT'),                   -- true
--          has_column_privilege('authenticated', 'public.job_fact_links', 'payload', 'INSERT'),       -- true
--          has_column_privilege('authenticated', 'public.job_fact_links', 'code', 'INSERT'),          -- false
--          has_column_privilege('authenticated', 'public.job_fact_links', 'user_id', 'INSERT'),       -- false
--          has_column_privilege('authenticated', 'public.job_fact_links', 'revoked_at', 'UPDATE'),    -- true
--          has_column_privilege('authenticated', 'public.job_fact_links', 'last_viewed_at', 'UPDATE'),-- false
--          has_column_privilege('authenticated', 'public.job_fact_links', 'published_at', 'UPDATE'),  -- false
--          has_table_privilege('authenticated', 'public.job_fact_links', 'DELETE'),                   -- false
--          has_table_privilege('authenticated', 'public.job_fact_links', 'TRUNCATE'),                 -- false
--          has_any_column_privilege('anon', 'public.job_fact_links', 'SELECT');                       -- false
--   select indexname from pg_indexes where tablename = 'job_fact_links' order by indexname;
--     -- includes job_fact_links_code_key, job_fact_links_one_live_per_project
--   select public.job_fact_code() ~ '^[A-HJ-NP-Z2-9]{12}$';   -- true
--
-- Idempotent: create ... if not exists / or replace, drop policy / trigger if
-- exists, and grants that are no-ops the second time.

-- ── code generator ───────────────────────────────────────────────────────────
-- 12 characters from the 32-character skills alphabet (no I, O, 0, 1), one
-- crypto-random byte per character: byte & 31 is uniform because 256 / 32 = 8.
-- 2^60 values; the unique constraint turns a (vanishing) collision into an
-- insert error the app reports, never a shared code. SECURITY DEFINER with an
-- empty search_path so the default works for the inserting role without it
-- needing EXECUTE on pgcrypto.
create or replace function public.job_fact_code()
returns text
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  b bytea := extensions.gen_random_bytes(12);
  result text := '';
begin
  for i in 0..11 loop
    result := result || substr(alphabet, (get_byte(b, i) & 31) + 1, 1);
  end loop;
  return result;
end;
$$;

revoke all on function public.job_fact_code() from public, anon;
grant execute on function public.job_fact_code() to authenticated, service_role;

-- ── table ────────────────────────────────────────────────────────────────────
create table if not exists public.job_fact_links (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  project_id uuid not null references public.projects(id) on delete cascade,
  code text not null default public.job_fact_code(),
  sections jsonb not null,
  payload jsonb not null,
  published_at timestamptz not null default now(),
  revoked_at timestamptz,
  last_viewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint job_fact_links_code_key unique (code),
  constraint job_fact_links_code_format check (code ~ '^[A-HJ-NP-Z2-9]{12}$'),
  constraint job_fact_links_sections_array check (jsonb_typeof(sections) = 'array'),
  constraint job_fact_links_payload_object check (jsonb_typeof(payload) = 'object'),
  constraint job_fact_links_payload_size check (pg_column_size(payload) < 512000)
);

-- At most one live link per job.
create unique index if not exists job_fact_links_one_live_per_project
  on public.job_fact_links (project_id) where revoked_at is null;

create index if not exists job_fact_links_user_idx
  on public.job_fact_links (user_id, created_at desc);

-- ── trigger: server-owned dates, no project moves, revoke is final ─────────
create or replace function public.job_fact_links_guard()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    new.published_at := now();
    new.revoked_at := null;
    new.last_viewed_at := null;
    new.created_at := now();
    new.updated_at := now();
    return new;
  end if;

  -- UPDATE
  if old.revoked_at is not null then
    raise exception 'job_fact_links: a revoked link is final (it cannot be turned back on or refilled)'
      using errcode = '42501';
  end if;
  if new.project_id is distinct from old.project_id then
    raise exception 'job_fact_links: a link cannot move to another project' using errcode = '42501';
  end if;
  if new.user_id is distinct from old.user_id or new.code is distinct from old.code
     or new.created_at is distinct from old.created_at then
    raise exception 'job_fact_links: owner, code and creation date are fixed' using errcode = '42501';
  end if;

  if new.revoked_at is not null then
    new.revoked_at := now();           -- never back-dated by the client
  end if;
  if new.payload is distinct from old.payload or new.sections is distinct from old.sections then
    new.published_at := now();         -- the page's "as of" is the server's clock
  else
    new.published_at := old.published_at;
  end if;
  if new.payload is distinct from old.payload or new.sections is distinct from old.sections
     or new.revoked_at is distinct from old.revoked_at then
    new.updated_at := now();
  else
    new.updated_at := old.updated_at;  -- a view (last_viewed_at) is not an edit
  end if;
  return new;
end;
$$;

drop trigger if exists job_fact_links_guard on public.job_fact_links;
create trigger job_fact_links_guard
  before insert or update on public.job_fact_links
  for each row execute function public.job_fact_links_guard();

-- ── RLS ──────────────────────────────────────────────────────────────────────
alter table public.job_fact_links enable row level security;

drop policy if exists job_fact_links_select_own on public.job_fact_links;
create policy job_fact_links_select_own on public.job_fact_links
  for select to authenticated
  using (
    auth.uid() = user_id
    and exists (select 1 from public.projects p where p.id = project_id and p.user_id = auth.uid())
  );

drop policy if exists job_fact_links_insert_own on public.job_fact_links;
create policy job_fact_links_insert_own on public.job_fact_links
  for insert to authenticated
  with check (
    auth.uid() = user_id
    and exists (select 1 from public.projects p where p.id = project_id and p.user_id = auth.uid())
  );

drop policy if exists job_fact_links_update_own on public.job_fact_links;
create policy job_fact_links_update_own on public.job_fact_links
  for update to authenticated
  using (
    auth.uid() = user_id
    and exists (select 1 from public.projects p where p.id = project_id and p.user_id = auth.uid())
  )
  with check (
    auth.uid() = user_id
    and exists (select 1 from public.projects p where p.id = project_id and p.user_id = auth.uid())
  );

-- No delete policy: revoke is an update.
drop policy if exists job_fact_links_delete_own on public.job_fact_links;

-- ── grants ───────────────────────────────────────────────────────────────────
-- Column grants: the client writes exactly what the owner screen sends.
-- TRUNCATE is not subject to RLS, so it is revoked explicitly (20260926190000
-- hygiene). service_role keeps its full rights (job-facts-view).
revoke all on public.job_fact_links from anon, public;
revoke all on public.job_fact_links from authenticated;
grant select on public.job_fact_links to authenticated;
grant insert (project_id, sections, payload) on public.job_fact_links to authenticated;
grant update (sections, payload, revoked_at) on public.job_fact_links to authenticated;
grant all on public.job_fact_links to service_role;

-- Postgres 17+ (prod is 17.6): MAINTAIN lets LOCK TABLE ignore RLS. Older
-- servers (PGlite) have no MAINTAIN and skip it.
do $$
begin
  if current_setting('server_version_num')::int >= 170000 then
    execute 'revoke maintain on public.job_fact_links from authenticated';
  end if;
end;
$$;

-- ── self-check ───────────────────────────────────────────────────────────────
-- Fail the apply, not a later request, if the grants did not land as written.
do $$
begin
  if not (select relrowsecurity from pg_class where oid = 'public.job_fact_links'::regclass) then
    raise exception '[facts] verify: row level security is off on job_fact_links';
  end if;
  if has_table_privilege('authenticated', 'public.job_fact_links', 'insert')
     or has_table_privilege('authenticated', 'public.job_fact_links', 'update')
     or has_table_privilege('authenticated', 'public.job_fact_links', 'delete')
     or has_table_privilege('authenticated', 'public.job_fact_links', 'truncate') then
    raise exception '[facts] verify: authenticated holds a table-wide insert, update, delete or truncate on job_fact_links';
  end if;
  if has_column_privilege('authenticated', 'public.job_fact_links', 'code', 'insert')
     or has_column_privilege('authenticated', 'public.job_fact_links', 'code', 'update')
     or has_column_privilege('authenticated', 'public.job_fact_links', 'user_id', 'insert')
     or has_column_privilege('authenticated', 'public.job_fact_links', 'user_id', 'update')
     or has_column_privilege('authenticated', 'public.job_fact_links', 'last_viewed_at', 'insert')
     or has_column_privilege('authenticated', 'public.job_fact_links', 'last_viewed_at', 'update')
     or has_column_privilege('authenticated', 'public.job_fact_links', 'published_at', 'update')
     or has_column_privilege('authenticated', 'public.job_fact_links', 'project_id', 'update') then
    raise exception '[facts] verify: authenticated can write a server-owned column of job_fact_links';
  end if;
  if has_any_column_privilege('anon', 'public.job_fact_links', 'select')
     or has_any_column_privilege('anon', 'public.job_fact_links', 'insert')
     or has_any_column_privilege('anon', 'public.job_fact_links', 'update') then
    raise exception '[facts] verify: anon holds a privilege on job_fact_links';
  end if;
end;
$$;
